### ISSUE TITLE
All aircraft are currently assigned to the open class in terms of filter options

### ISSUE THREAD

**Issue by CarstenSon** [weglide/bugtracker#10]
**Describe the bug**
All aircraft are currently assigned to the open class in terms of filter options

**To Reproduce**
1. Choose any competition
2. Change class to 15m/18m/Doubleseater/Club/Standard
3. See no results in table
4. Change back to "Open" or "All"
5. See all results in table

**Expected behavior**
The respective aircraft of a class should appear in the table if the filter is set accordingly

**Screenshots**

**Device (please complete the following information):**
 - Device: Computer
 - OS: Windows 20H2
 - Browser Firefox 84.0.1 (64 bit)

**Comment by moldhouse** [comment]
Thanks for reporting - we have fixed it :)
