### ISSUE TITLE
Filter function (names) not precisly working

### ISSUE THREAD

**Issue by Wisbacher** [weglide/bugtracker#100]
**Describe the bug**
If I select my own flights (juergen wisbacher) some additional flights of my son Michael appear in the list as well

1. Go to filter function for flights
2. add Jürgen Wisbacher
3. Select list view
4. 2 flights from Michael Wisbacher will appear in the list
![2021-02-16_11-39-10](https://user-images.githubusercontent.com/79142568/108054950-9df8fd00-704f-11eb-853e-c4967bd623a7.jpg)

 - Device: Think Pad Notebook
 - OS: Windows 10
 - Browser chrome

**Comment by Wisbacher** [comment]
I noticed that I was registered as Co Pilot for that flights

**Comment by samuel-git** [comment]
Should also work for Co Pilots now.
