### ISSUE TITLE
Declared task is missing in task overview

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#101]
**Describe the bug**
When no task is declared, this is shown in the task overview, see screenshot 1.
After declaring a task, the declared task is missing in the task overview, see screenshot 2.
You have to know the declared task and open that task to delete the declaration.

**To Reproduce**
1. Declare task
2. Go to task overview
3. See that declaration missing

**Expected behavior**
A declared task should be shown in the task overview.
I remember some days ago this has still worked..... Maybe something has been broken with the new declare XX days feature?

**Screenshots**
No task declared: Declaration info is shown
![image](https://user-images.githubusercontent.com/47079209/108549111-04e71200-72ed-11eb-9eaa-167a288a19e2.png)

Task is declared: Declaration info missing
![image](https://user-images.githubusercontent.com/47079209/108549153-16301e80-72ed-11eb-803c-97143e80520b.png)

**Comment by frantzheld** [comment]
![Screenshot_20210219_200500_com android chrome](https://user-images.githubusercontent.com/47079209/108549750-e46b8780-72ed-11eb-92cf-5192d465bb05.jpg)

Should look like this.
(I had old cache on my smartphone...)

**Comment by samuel-git** [comment]
Thanks, I will investigate. Should be easy to fix.

**Comment by samuel-git** [comment]
Fixed for next release.
