### ISSUE TITLE
Just  a wrong writing of our club

### ISSUE THREAD

**Issue by jokoGD** [weglide/bugtracker#102]
**Describe the bug**
FG Schwäbisch Gmund is correct FG Schwäbisch Gmünd
the ü (or ue) is very important for our press people...-:)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - OS: [e.g. Windows]

**Comment by samuel-git** [comment]
Thanks @jokoGD, we will fix this.

**Comment by jokoGD** [comment]
Hi Samuel,
sorry to bother you with this again, but the **ü** in Gmünd is still missing.
It was not about FG or FLG it was about Gm**ü**nd instead of Gmund... 
Anyway great job you are doing here, keep going, stay healthy

**Comment by samuel-git** [comment]
Looks fine now, thanks you too!
