### ISSUE TITLE
User generated title media

### ISSUE THREAD

**Issue by samuel-git** [weglide/bugtracker#103]
![image](https://user-images.githubusercontent.com/47079209/108620871-45e73f80-742f-11eb-9f4e-c8ba4e749308.png)

### Exchange static title picture by "picture of the month".

Your title picture is really beautiful! But if you see the same picture again and again it will get boring at some time.
Users have uploaded thousands of amazing photos to their stories.
At the moment I have no idea how to use them, but maybe someone else has an idea...
Something like a voting for the picture of the month or maybe if it will be possible to like single story pictures, show the picture with the most likes of the month....

I think this feature is very low prio, but maybe you'll have a good idea of implementation at some time in the future.

__Originally posted by @frantzheld in https://github.com/weglide/bugtracker/issues/80#issuecomment-782828368__

**Comment by moldhouse** [comment]
I think this is a very good idea. It could also be picture of the week. We could rate based on the like of the flight. Of course, we could also implement liking individual pictures but this could be overkill and confusing. Also we need a way to handle if the user deletes the picture.

**Comment by moldhouse** [comment]
If we only use the API to select a random picture from the most liked flight, we could end up with a selfie of a user which we should avoid. @samuel-git any suggestions? We should also consider returning a list of the top 5 pictures from the last week so users have some kind of slide show?

**Comment by moldhouse** [comment]
I think I can filter out pictures with faces in the backend, but still, it would be difficult to select the most beautiful image from a popular flight.

**Comment by samuel-git** [comment]
My favorite option is a slowly playing unobstrusive slideshow with caption for the images (FL, place, user and user added description if available).

We could even go so far and replace the story section on the front page with this new visualization.

Hijacking the image for ads etc. is a problem where I have no good solution.

**Comment by samuel-git** [comment]
![image](https://user-images.githubusercontent.com/22152728/110249800-3f50e000-7f78-11eb-866a-40e44b070cca.png)

This is the new version.
Feedback welcome!

**Comment by frantzheld** [comment]
Looks beautiful!

Maybe add altitude and distance+direction of next Turnpoint/Airport. (e.g. 1200m, 12km SE of Klix)

**Comment by samuel-git** [comment]
Two things which are nice to have:

1. Reverse geocoding to show location of picture relative to closest airport.


2. Remove attention from progress bar (maybe change to a smaller circle progress bar or remove completely)

3. Smooth transitions between pictures

4. Play/Pause button
