### ISSUE TITLE
Registrationprocess does not work

### ISSUE THREAD

**Issue by slowflyer74** [weglide/bugtracker#104]
At first step, registration process looks like working. But I cannot log in. After verification email was sent and email verified, I still see the message "not verified". 
Activating the registration process a second time, did not send the email again.
Trying to change the personal information did succeed, But I am not able to enter a date, only 2 figures.

Device: Laptop Linux LMDE
Browser: Cromium 87

**Comment by samuel-git** [comment]
Are you on the right site or did you try to register for the newsletter (thats not the same).
Did your sign up look like this? https://beta.weglide.org/auth/sign-up That is the right one.

**Comment by flyingjoe** [comment]
Best would be to send us an email to info@weglide.org and we'll have a look.

**Comment by slowflyer74** [comment]
Meanwhile the email for the registration has arrived and also the account was activated correctly - but I was using my windows machine for that. Looks fine now. Thanks
