### ISSUE TITLE
Date formats displayed, UK English

### ISSUE THREAD

**Issue by DecisionNumerics** [weglide/bugtracker#106]
Would be great if with language selection "English" the English date format was applied, DD-MM-YYYY, rather than the American date format (MM/DD/YYYY).

**Comment by samuel-git** [comment]
Good point. Then we need two different language settings or an additional selection in the user settings.

**Comment by moldhouse** [comment]
Backend already supports language setting in the profile section.

**Comment by samuel-git** [comment]
I would rather handle language on a per-device level like it currently is:

1. check if user has already done a selection on this device
2. fallback to browser/OS language
3. fallback to english

I naively assumed that date format can be language dependent. This works only if we distinguish EN and US english.
Date formats are also not unit dependent I guess.

Apropos units, UK uses km for competition flying afaik.
So we need an extra unit setting "UK".

**Comment by samuel-git** [comment]
I think keeping the language <--> date format relation is okay but then we need to introduce English US and English GB:
https://en.wikipedia.org/wiki/Date_format_by_country

**Comment by DecisionNumerics** [comment]
Nice fix! Many thanks.
