### ISSUE TITLE
Task loading of flight

### ISSUE THREAD

**Issue by alegiaio** [weglide/bugtracker#107]
**Describe the bug**
weglide seems not support the declared tasks (i cannot see in the statistics or in other pages)
**To Reproduce**
1. Go to 'one flight'
2. Click on 'the details'
3. Scroll down to 'statistic'

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - OS: [e.g. Windows]

**Comment by samuel-git** [comment]
Yes, the predeclared task is only visible for DMSt contest flights (start in germany) as the declaration has no effect on the points for other contests like free etc.

We will show declared tasks for all contests in the future because it is nice to have.

**Comment by samuel-git** [comment]
Declared and completed tasks can now be found under the "Task" tab of qualifying flights.

**Comment by alegiaio** [comment]
Wow 🤩 thanks!
Il giorno ven 12 mar 2021 alle 12:22 Samuel ***@***.***> ha
scritto:

**Comment by samuel-git** [comment]
No Problem, feedback is always welcome!
Let me know if you encounter errors please.
Currently the task is only shown when declared and completed. Failed declarations are not shown but we plan to.

**Comment by alegiaio** [comment]
Yes it is a nice feauture for see wich declaration Was set from the pilot
in case of failed goal too 👍

Il giorno dom 14 mar 2021 alle 19:01 Samuel ***@***.***> ha
scritto:
