### ISSUE TITLE
Follow pilots and personalized feed

### ISSUE THREAD

**Issue by samuel-git** [weglide/bugtracker#108]
- Add feature to follow pilots
- Show latest flights of your friends 
- Maybe show it on frontpage?

![image](https://user-images.githubusercontent.com/47079209/110485302-c8d4ef00-80eb-11eb-8ea0-eaf6566ed6a6.png)

__Originally posted by @frantzheld in https://github.com/weglide/bugtracker/issues/80#issuecomment-793968227__

**Comment by moldhouse** [comment]
This would be super cool! I just don't see any way to cache this efficiently (yet) and I am a bit afraid of serving individual responses per user on busy days at the moment.

**Comment by deltafox44** [comment]
Great feature. I would expect to see first the list of flights from pilots/airfields/regions whose I watched/liked the more flights in the past.

In addition, It would be great to add public comments to an other pilot's flight, and/or to send him private messages (by e-mail).

**Comment by samuel-git** [comment]
Check out the new friends feed under https://weglide.org/feed when logged in.
