### ISSUE TITLE
Can't set scoring window seconds on iPhones

### ISSUE THREAD

**Issue by flyingjoe** [weglide/bugtracker#11]
**Describe the bug**
The scoring window time selection on iPhones only allows to set minutes, not seconds.

**To Reproduce**
1. Upload or edit a flight
2. Try to change the scoring windows

**Expected behavior**
I expect to be able to change the seconds of the scoring windows.

**Screenshots**
![image](https://user-images.githubusercontent.com/28477393/103106961-408d9480-463a-11eb-9255-1ca5bf0fa994.png)
![image](https://user-images.githubusercontent.com/28477393/103106956-39ff1d00-463a-11eb-94f0-b86ee4cba395.png)

**Device (please complete the following information):**
 - Device: iPhone
 - OS: newest iOS
 - Browser: Safari

**Comment by samuel-git** [comment]
Done for next release. switchet to native text input instead of time.
