### ISSUE TITLE
Bad Windsheim Airfield EDQB wrong radio frequency and callsign, "Report an error" link on map leads to a dead end

### ISSUE THREAD

**Issue by limaoscarzulu** [weglide/bugtracker#110]
Hi there! 
My home airfield, EDQB, is showing the wrong frequency on the web map. It inherited callsign and frequency from ETIK, a US army helicopter field close to us.
Correct frequency is **118.260** and correct callsign **"WINDSHEIM INFO"**

The web map link for the error report is also dead and leads to a 404 on GitHub.
Cheers, 
Lukas

**Comment by samuel-git** [comment]
Thanks for reporting!
Will fix the link. We use OpenAIP for the airfield data. Please report the required changes with them as changing them on our side would not adress the root source. I think your help is appreciated from them.

**Comment by limaoscarzulu** [comment]
Thanks, I changed the frequency on the openAIP website, I hope that it'll be approved and implemented soon
Happy flying!

**Comment by samuel-git** [comment]
Amazing, thanks!

**Comment by samuel-git** [comment]
Link is fixed for next version.
