### ISSUE TITLE
wrong Airfield assigned to user - cannot change

### ISSUE THREAD

**Issue by pcscholz** [weglide/bugtracker#111]
The airfield assigned to my user profile is wrong (it's the one were I used to fly many years, but now this has changed).

There is no way to change this in my user profile. 

It should be user-definable IMHO

**Comment by samuel-git** [comment]
The airfield is set automatically to the one with the most starts from you. I think this is sufficient and does not justify an extra settings option.
Maybe we could change the wording to be more clear about what it represents.
