### ISSUE TITLE
wrong club assigned to Flight

### ISSUE THREAD

**Issue by pcscholz** [weglide/bugtracker#112]
I uploaded my previous flights to weGlide.org. many of them are correct, but the 2020 flights have the wrong club. I moved to another place, and have therefore changed club and home airfield. 

While I can change my club in the profile, I cannot change the club assigned to the flights. I cannot image where you draw the information about the club during upload, it is not contained in the .igc file used for upload. Anyway, it is wrong for all flights that I made in 2020. But I cannot change it in weglide. 

Club info for uploaded flights should be user-definable and -changable.

**Comment by samuel-git** [comment]
Hi pcscholz.

You can delete the flights, change your club and re-upload.
We use the club that is set at the time of upload.

Not optimal but the only other solution would be to add a club field to the upload. Thats too much bloat and rarely needed in my opinion.

Maybe you got a better idea?

**Comment by deltafox44** [comment]
"We use the club that is set at the time of upload"

That's fine, but I fear that nobody when uploading his old flights will think to set his profile to his old club, if not advised to do so (I didn't either when I uploaded my old flights, and deleting hundreds of flights to reload them, plus comments and pictures, would need way too much time)

There should be a message in the profile page (where the club is set) indicating that changing the club for new flights will not affect older flights.  

Also, in the [uploading page](https://www.weglide.org/upload) there should be a reminder of the club name with the possibility to click on it to change it (and the same message as above)

**Comment by samuel-git** [comment]
Good suggestions. We will make it clearer. In the meantime we can change your club on flights in bulk if you email us.

**Comment by deltafox44** [comment]
Many thanks
