### ISSUE TITLE
Comparing flights -> mismatch between barogram and map

### ISSUE THREAD

**Issue by cpizer** [weglide/bugtracker#113]
**Describe the bug**
If two flights are compared, there is a mismatch between the planes visualized on the map and the cursor in the barogram. E.g. a plane is shown already landed at its airfiled while the barogram is somewhere during the flight. In addition, if the cursor of the barogram is moved to a "nonzero" position, the mouse is moved to position outside the barogram and moved onto the barogram again, the map visualization becomes buggy.

**Steps to reproduce**
1. Open https://www.weglide.org/flight/34938,946
2. Compare flight with another flight, which took of earlier than the "main flight" and landed afterwards
3. Navigate through the barogram

**Expected behavior**
The plane of the flight, which was airborne for longer terms than the "main flight", should correspond with the barogram.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/59721050/111701140-aef98180-883a-11eb-98c9-403a2e5f4f82.png)
Stefan Karch's plane is shown at its home airfield while the barogram shows it mid flight

**Device (please complete the following information):**
 - Device: ASUS VivoBook S14 (i5 8th Gen, Intel Graphics)
 - OS: [Windows 10 64bit]
 - Browser [Mozilla Firefox]

**Comment by samuel-git** [comment]
Hi cpizer,
thanks for your report. This is fixed since a week or so. Please clear your cache and reload:
https://support.mozilla.org/en-US/kb/how-clear-firefox-cache
