### ISSUE TITLE
Deleting a image in flight story takes long, without feedback to user

### ISSUE THREAD

**Issue by niggli** [weglide/bugtracker#114]
**Describe the bug**
I uploaded an image to my flight story (in HEIC format if that matters). After it showed up, I decided against it and clicked on delete. Nothing happened, but after 1-2 minutes it was gone. In this time I clicked multiple times, searched for another way to get rid of the image etc. - not a great user experience ;)

**To Reproduce**
1. Upload image to flight story
2. Click on delete
3. Wait

**Expected behavior**
I expect either a instant delete or something in the fashion of "Please wait, image is beeing deleted..."

**Screenshots**

**Device (please complete the following information):**
 - Device: Macbook Pro
 - OS: MacOS Catalina
 - Browser: Safari 14.0.3

**Comment by samuel-git** [comment]
Hi,
will look into this, happend for me instantly but that depends on the connection.
How many images/text did you have in the story? Maybe you can post the link here.
Thanks!

**Comment by niggli** [comment]
Only one - after I deleted it, zero. The flight is here: https://www.weglide.org/flight/37233

And I attached the image file, had to ZIP it because HEIC wasn't accepted first.

[IMG_4107.HEIC.zip](https://github.com/weglide/bugtracker/files/6178323/IMG_4107.HEIC.zip)

**Comment by samuel-git** [comment]
Okay, I cant upload this file. WeGlide responds with "Invalid image format" as it should.
So I am curious how you managed to upload in the first place.

@moldhouse maybe we can add .heic support?

**Comment by moldhouse** [comment]
.heic support does require quite a few adjustments as we depend on Pillow (https://github.com/python-pillow/Pillow/issues/2806). So I am also curious how you managed to upload the image in the first place.

**Comment by niggli** [comment]
I didn't do anything special, so my guess is that the browser (Safari) converted it to jpg in the background: https://stackoverflow.com/questions/64093027/is-it-possible-to-make-ios-safari-upload-original-heic-photos-without-jpeg-conve

The image was shown after uploading, so the process worked somehow. But maybe that conversion by Safari is part of the problem, I can try to recreate the issue in the evening.

**Comment by niggli** [comment]
The behaviour is the same if I upload a jpg version of the same image. My connection is >50Mbps DSL and a ethernet network, so that shouldn't be part of the issue. Did you also try with Safari?

**Comment by niggli** [comment]
I tried this again today, again it was slow. Additionally a popup "Flight Story not found" (or something similar) was shown for a short time after saving the flight. I was too slow to make a screenshot, but I'm sure you'll find it in the code.

**Comment by samuel-git** [comment]
So definitely a Safari/Heic problem. We are not able to replicate the issue atm and will wait for more reports. A short dive in even with your excellent help did not yield any results.

Another short question: Does the version number on the start page footer displays 1.2.2 to you? Just to make sure we are on the same page (sorry for the pun).

**Comment by niggli** [comment]
Yes 1.2.2 is shown.

**Comment by samuel-git** [comment]
Okay, 
can you open the developer console in safari an look for (red) errors while deleting the image?

There should also be a request in the network tab of the dev console on delete.

An screenshot would be superb!

Thanks for your patience.

**Comment by niggli** [comment]
No problem, I hope I did it right. Before I even added a image to the flight story, the console looked like this:

<img width="1273" alt="Before deleting" src="https://user-images.githubusercontent.com/529670/117715425-878ab980-b1d8-11eb-9473-81e16652ef3f.png">

After I deleted the flight, it took about a minute. There was no change to the console, but in the network tab there was a very long API request:
<img width="1273" alt="after deleting image" src="https://user-images.githubusercontent.com/529670/117715420-878ab980-b1d8-11eb-9e12-940a1a49e581.png">

Interestingly, clicking on "Löschen" because I didn't really want to upload the flight, also lead to a very long running request:

<img width="1274" alt="after deleting flight" src="https://user-images.githubusercontent.com/529670/117715410-80fc4200-b1d8-11eb-895a-5401c7abe545.png">

I hope it helps.

**Comment by samuel-git** [comment]
Thanks, this helps a lot. @moldhouse looks like an issue with handling of unexpected API input.

**Comment by samuel-git** [comment]
HEIC format is now supported, right @flyingjoe ?

**Comment by flyingjoe** [comment]
@samuel-git No, pillow still hasn't implemented it.
