### ISSUE TITLE
flight compare - issue with glider symbol on map

### ISSUE THREAD

**Issue by cdolain** [weglide/bugtracker#115]
hi,

i tried to compare 2 fligths in weglide on the map. 
it seems like the time on the barogram is correct but not the representation of glider symbols on the map (??).
[weglide_Flugvergleich_Zeiten.pdf](https://github.com/weglide/bugtracker/files/6189207/weglide_Flugvergleich_Zeiten.pdf)

I started with filtering Europa then 22.03. 
clicked on first flight 
used the right arrow to go to the next flight on 22.3.
until i reached 
https://www.weglide.org/flight/38197

then i added "Gefaehrten  -> Frank Harald Strewinsky" 
click on "vergleichen" 
https://www.weglide.org/flight/38197,38407

then hover with the mouse along the barogram. 

at the end of the barogram they should both be back in Vinon or very close to it.
Frank's glidersymbol is hours away somewhere in the middle of the alps. - see attached pdf file.

this is on Windows 10,  google chrome on a 3840x2160 monitor - no difference whether scaling is 100% or 150%.

regards,
Christoph

**Comment by samuel-git** [comment]
Hi, did you try to clear your cache and open/close the browser?
Seems like you got an old version.
Please let me know if this did not solve the issue.
