### ISSUE TITLE
Protect unauthorized routes in frontend

### ISSUE THREAD

**Issue by niggli** [weglide/bugtracker#12]
**Describe the bug**
The edit-flight page can be opened for any flight if you know the link (which is not very hard to construct) without beeing logged in, and everything is displayed and can be changed. Of course you cannot save the changes.

**To Reproduce**
1. Logout
2. visit https://beta.weglide.org/edit-flight/2562
3. See page

**Expected behavior**
The edit-flight page should not be displayed if the owner of the flight is not logged in.

**Screenshots**

**Device (please complete the following information):**
 - Device: Macbook Pro
 - OS: OSX Catalina
 - Browser: safari

**Comment by samuel-git** [comment]
Good find, we are aware of that and thanks for writing it down. Will be fixed in the coming weeks.

**Comment by moldhouse** [comment]
@samuel-git I think this is fixed now?

**Comment by samuel-git** [comment]
No, still up. But not prio.
