### ISSUE TITLE
Implausible wind calculation

### ISSUE THREAD

**Issue by kaleu2** [weglide/bugtracker#122]
**Describe the bug**
Calculated wind direction in statistics is different from cycling wind offset.
This behavior is only observed at some flights (basically it looks like the issue #66 described before).

**To Reproduce**
1. Go to https://www.weglide.org/flight/41220
2. Click on Statistics
3. The caclulated wind direction is SW while it was NNW all day, clearly visible during circling

**Expected behavior**
Calculated wind direction should be NNW

**Further examples**
https://www.weglide.org/flight/41203
Caldulated: SW, Circling: NNW/N

https://www.weglide.org/flight/41136
Calculated: SE, Circling: N

https://www.weglide.org/flight/41625
Calculated, first legs NE, last legs SW: Circling: NE/N all day

**Comment by samuel-git** [comment]
@moldhouse the arrows are matching the data unlike last time, so it has to do with the calculation.

**Comment by frantzheld** [comment]
Yesterday we had wind from north all day. There is still something wrong with the wind calculation: https://weglide.org/flight/51876
![image](https://user-images.githubusercontent.com/47079209/116067137-2bc51a00-a689-11eb-905a-1fb94a5c0b7d.png)

**Comment by moldhouse** [comment]
Thanks again for the detailed description. I have fixed the bug and reevaluated all the flights you mentioned above. I think they all look sensible now.
