### ISSUE TITLE
Broken Links in user profile

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#123]
**Describe the bug**
When clicking on "Flüge als Liste" or "Flüge als Karte" in the user profile, the flight list filter setting does not work - see screenshot.
The URL seems ok. So when refreshing the page, the correct filter settings are set.

**To Reproduce**
1. Go to user profile, e.g. https://weglide.org/profile/70
2. Click on 'Flüge als Liste'
3. See that the flight list contains flights from other pilots (screenshot)

**Expected behavior**
Only my personal fights should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/47079209/113990227-879e3f00-9851-11eb-9df9-688a185dfce6.png)

**Device:**
 - Device: Laptop
 - OS: Windows 10
 - Browser chrome

**Comment by frantzheld** [comment]
When you go back to the user profile (click "Profil" on the left side), the error affects to your story too:
![image](https://user-images.githubusercontent.com/47079209/113991348-a94bf600-9852-11eb-98f9-fd313d8813b2.png)

**Comment by samuel-git** [comment]
Thanks, we spotted that something slipped to production. I am on it! :+1:

**Comment by samuel-git** [comment]
Fixed for next release
