### ISSUE TITLE
Add sector "Norddeutschland"

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#124]
I very often use the filter "Niedersachsen" to see the latest flights in my region. Unfortunately then I miss "Hamburg" and "Bremen" even though they are located in the same area.

A new sector "Norddeutschland" comparable to the sector "Alpen" would help me a lot!
![image](https://user-images.githubusercontent.com/47079209/114720683-8466ef80-9d38-11eb-94cb-bc16b3f5961a.png)

Maybe even add sectors for south or west germany.

**Comment by moldhouse** [comment]
I see two possibilities: First is to combine multiple regions into a filter, this would be pure frontend + Elasticsearch. 
The second possibility is to add a custom sector, as we have for Taunus, alps, and rhinevalley.

**Comment by frantzheld** [comment]
Both would work for me.

I didn't know that the sectors taunus and rhinevalley exist. A list of all available sectors in the FAQ would help!

**Comment by moldhouse** [comment]
https://github.com/weglide/flugfeld
