### ISSUE TITLE
Wrong scoring start (ENL detection)

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#125]
**Describe the bug**
At some flights yesterday the scoring start has been set to a time where ENL level is still high:

Example 1:
https://weglide.org/flight/47157
![image](https://user-images.githubusercontent.com/47079209/114723090-a95c6200-9d3a-11eb-8a53-369d3b284795.png)

Example 2:
https://weglide.org/flight/47136
![image](https://user-images.githubusercontent.com/47079209/114723151-ba0cd800-9d3a-11eb-93d0-ed645a1af1b5.png)

**Comment by samuel-git** [comment]
The times were set manually, WeGlide detected them correctly. We wrote Example 2 and it has already been changed back.
Thanks for your heads up!
