### ISSUE TITLE
airfield "Itzehoe/Hungriger Wolf" does not belong to region DE/SH

### ISSUE THREAD

**Issue by CarstenSon** [weglide/bugtracker#126]
**Describe the bug**
A flight from the airfield Itzehoe doesn't appear in the scoring when using the regional filter "Schleswig-Holstein"

**To Reproduce**
1. check https://weglide.org/flight/48099 
2. check https://weglide.org/flight?region=Schleswig-Holstein,DE-SH&scoring_date=2021-04-15&order_by=-points
3. open https://weglide.org/airport/152558 - see, that region of the airfield is DE and not DE/SH <- **this is the most probable root cause for the behaviour**

**Expected behavior**
The flight from Itzehoe should appear in the scoring. The airfield should belong to the region DE/SH

**Screenshots**
n/a

**Device (please complete the following information):**
 - Device: all tested platforms
 - OS: Linux, Mac, Windows
 - Browser Chrome, Safari, Firefox

**Comment by CarstenSon** [comment]
same problem with Ahrenlohe, Hartenholm, Hohn, Schleswig, Flensburg-Schaeferhaus, Offenbuettel and Husum/Schwesing

these are some airfields that i found out about in a few minutes - where do these data come from? If these information is getting imported automatically it might be better to solve the problems in the data source..

**Comment by moldhouse** [comment]
https://github.com/weglide/flugfeld
