### ISSUE TITLE
Filtering by Regions 

### ISSUE THREAD

**Issue by deltafox44** [weglide/bugtracker#127]
**Describe the bug**
Administrative regions are not available for filtering and this cause strange filter results.

**To Reproduce**
For instance, in France, entering "Pays de la Loire" will display "Laguna de Gomez" airport in Argentina !

**Expected behavior**
Administrative regions in each country should be available. If not present, it should not filter at all rather than filter by anything else.

By the way, it is not clear if filtering applies to the country/region of the take-off airfield (that's what I guess), to the start point, or to any flight passing through this region.

**Comment by samuel-git** [comment]
It is true, administrative regions are only available for USA (States) and Germany (Bundesländer).
Sadly it requires a lot of manual labour creating regions and boundaries. We are on it!

The search tries to match the closest keyword and has no knowledge what you are looking for in terms of a category. That is why it suggests an airport.

The location filters are applied by takeoff point.

**Comment by frantzheld** [comment]
Is it a good idea to publish the airport database as a repository to allow the community help you with the regions in their countries?
(like GliderList or translations) 
As a positive side effect the community could help to review the regions to fix issues like #126.

**Comment by samuel-git** [comment]
Yes I am strongly in favor. We use OpenAIP data and add some own infos on top, so we will have to check how this makes sense as we do not want to create a competing repo to OpenAIP.
@moldhouse @flyingjoe

**Comment by CarstenSon** [comment]
I would also be strongly in favor of @frantzheld s suggestion of an airport database and would participate to fix problems like in #126 via pull request

**Comment by samuel-git** [comment]
Thank you @CarstenSon, pull requests will be appreciated. We are collecting and sorting the info. Should be ready for open sourcing soon.

**Comment by moldhouse** [comment]
https://github.com/weglide/flugfeld
