### ISSUE TITLE
Airfields "Pinnow" and "Eberswalde-Finow" are mixed up

### ISSUE THREAD

**Issue by eehmke** [weglide/bugtracker#129]
**Describe the bug**
When planning a task on the map, at the location of airfield Pinnow, north west of Berlin, the waypoint shows up as "Eberswalde-Finow". This airfield is in fact north east of Berlin.

**To Reproduce**
1. Go to "New Task"
2. Move to the map location of Pinnow
3. Select the point as turn point
4. It will show up as "Eberswalde Finow"

**Expected behavior**
Each turn point should show the real location

**Comment by moldhouse** [comment]
This was a data issue that was solved [here](https://github.com/weglide/flugfeld) @flyingjoe can you deploy new airport tiles?

**Comment by flyingjoe** [comment]
Fixed
