### ISSUE TITLE
Set descending ordering per default

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#131]
**Describe the bug**
When clicking on the table header in the flight list, you get a ascending ordering per default. So you see the smallest flights for "distance", the lowest speeds for "speed" or the oldest flights for "date" at the top of the table. You have to click a second time to get descending ordering.

**To Reproduce**
1. Go to flight list
2. Click on table header, e.g. "distance"
3. See that smallest flights are on top of the list, see screnshot

**Expected behavior**
When clicking on the table header the ordering should be descending per default (With one click).

**Screenshots**
![image](https://user-images.githubusercontent.com/47079209/116065366-3c749080-a687-11eb-9f7e-9386ba9f0203.png)

**Comment by samuel-git** [comment]
Yes! This annoys me every time!

**Comment by samuel-git** [comment]
Fixed with next release today.
