### ISSUE TITLE
Comments in Story

### ISSUE THREAD

**Issue by maluethi** [weglide/bugtracker#132]
In the same way we can add photographs, allow to add comments to a location on the track. Background: I do not always have time to take a photo, but in hindsight it would be nice to add a comment anyway.

**Comment by frantzheld** [comment]
This is already possible. Just click on "New Comment", set the time and add a comment:
![image](https://user-images.githubusercontent.com/47079209/116227808-d0f8f480-a754-11eb-9308-9f8ebea3682f.png)

The icon is quiet similar: left side photo, right side comment:
![image](https://user-images.githubusercontent.com/47079209/116229504-df481000-a756-11eb-8b3a-3da8d2fe9027.png)

**Comment by maluethi** [comment]
Just tested it, seems I wasn't looking carefully enough and haven't seen this in action. Thanks for the clarification!
A little feedback on the feature: I found that its not obvious that its possible to edit the timestamp. And it would be nice to see the tag in "edit" mode on the map, so one has a direct feedback on the setting of the timestamp. Right now its more of an back and forth of publishing and editing.

**Comment by samuel-git** [comment]
Good feedback!

Some points you make would require tradeoffs between features and simplicity.
The tag is displayed in the barogram, showing the map as well is maybe too much.
But we will improve the timestamp edit and comment icons. :+1:

**Comment by samuel-git** [comment]
Done for next release.
