### ISSUE TITLE
Embed custom story

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#134]
The **embed website widget** is perfect to get the latest story on your website! See https://docs.weglide.org/docs/how_to/embed/
At the moment the widget is available for single flights, clubs, airports or users.

Is there any possibility to embed a **custom story**?
In my case, I'd like to add the widget to our website https://dkader-nds.de/ including the story of all pilots of the "D-Kader Niedersachsen".

The custom story I need looks like this: [https://weglide.org/story?user=Florian%25......](https://weglide.org/story?user=Florian%2520von%2520Fintel,134&user=Felix%2520Vaske,5176&user=Sebastian%2520Steffens,109&user=Paul%2520Seidel,2311&user=Lukas%2520Luksch,532&user=Marlon%2520L%25C3%25B6nnecker,919&user=Renate%2520Litzelmann,4410&user=Eve%2520Lanzend%25C3%25B6rfer%2520,122&user=Bj%25C3%25B6rn%2520Knauff,1535&user=Benjamin%2520Josuttis%2520,1159&user=Frederic%2520Janssen,97&user=Yannis%2520Hartung,76&user=Niklas%2520Hahn,1606&user=Jan%2520Ole%2520G%25C3%25B6deke,110&user=Yannik%2520Freund,741&user=Stefan%2520Braniek,1536&user=Niklas%2520Beening,3732&user=Joshua%2520Arntz,656&order_by=-scoring_date)

Maybe add a possibility to simply add the `embedded `to the URL, e.g.: https://weglide.org/embedded/story?filter.....

I think for this special case it is sufficient to mention the feature in the docs, since it would be hard to include the embed box somewhere on the story page.

**Comment by samuel-git** [comment]
This is currently **not** possible. I will look into this :+1: Maybe it is not too hard to build. But will need some time.

**Comment by samuel-git** [comment]
Okay, it is hard and not widely requested. Will have to postbone this sadly.
