### ISSUE TITLE
Tasks visualization

### ISSUE THREAD

**Issue by deltafox44** [weglide/bugtracker#136]
**Describe the bug**
The task as declared through IGC logger (or Weglide) is not shown when not completed, and sometimes even when completed

**To Reproduce**
1-See for instance this flight : https://www.weglide.org/flight/48049 - there are Free/Triangle/O&R/Sprint tabs, but no "Task". Opening the same flight in SeeYou : https://seeyou.cloud/flight/public/6fh_HyPFOvPIcgbcPvBb3F - the task turnpoints and sectors can be seen. The second turn point FAI sector is missed by about 100 m.
2-In this flight : https://www.weglide.org/flight/49467 - there is no "task" tab, while SeeYou shows the tasks have been completed. 
3-In this flight https://www.weglide.org/flight/56793, I had an engine restart on the final leg. SeeYou shows that I made the turnpoints, but not WeGlide.
4- In this flight: https://www.weglide.org/flight/48858 the task declared through WeGlide was not the same that the task declared in the logger (showed by SeeYou)

**Expected behavior**
1-When declared, completed or not, the task turnpoints and sectors should be shown, at least in "task" tab. This is a valuable information on the pilot's intentions for the day. Also, if a sector was missed (like in the example above), it can be seen without leaving WeGlide
2-WeGlide should detect more accurately when the task has been completed. It is not clear to me why it is not the case about half the flights.
3-In the Task tab, it should be possible to see the declared turnpoints within WeGlide (while obviously there will be zero points since the task has not been completed)
4-It should be noted under Task tab whether the task was declared through IGC logger or through WeGlide, with date/hour of declaration (it will still be possible to see the task as declared through the logger by opening the flight in SeeYou).

**Non DMSt tasks feature request**

I understand that the rules for tasks (scoring points, start and turn points sectors) are those of DMSt. But it would be fine if it was also possible : 
1-for non-DMSt flights (non german clubs/pilots), to fly/score under FAI rules (1 km start and finish lines, 500 m beer can at turn points with 1 km penalty on distance if the FAI sector was not reached) which are compulsory for FAI badges/records.
2-to have a TASK tab in the [list of flights](https://www.weglide.org/flight) (in addition of Free, Triangle, O&R, Sprint and
DMSt, (also, why not an Explore tab, since there is an Explore Contest ?)

**Screenshots**

**Device (please complete the following information):**
 - Device: MacBookAir
 - OS: macOS 10.14.6
 - Browser : Chrome

**Comment by moldhouse** [comment]
Thanks for the detailed description. There is indeed much room for improvement. I think most of the above (except for the different ruleset) can (and should) be implemented with reasonable effort.

**Comment by samuel-git** [comment]
1. Adressed by the new permanent task card which is always displayed when a task was declared.
2. This was an issue where triple click on flight planing added two end sectors which lead to incomplete tasks. Fixed for future tasks.
3. I think this is the same as 1. Please correct me if I misunderstood
4. Will add a notice like DMSt with different colors and tooltips for online/logger declaration. The declaration date is a good suggestion, will see what I can do.

Thanks again for the feedback! Let me know when there is something else :-)

**Comment by deltafox44** [comment]
What do you mean by "new permanent task card" ? I still cannot see the tasks when not achieved (or cannot find where it is)

**Comment by samuel-git** [comment]
![image](https://user-images.githubusercontent.com/22152728/121802348-16597e80-cc3c-11eb-9208-5151c441e143.jpeg)

Like this. Try clearing the cache/reloading if it does not appear.

**Comment by deltafox44** [comment]
Thank you for replying. It took me some time but I finally found out that the declared task appear on the map after clicking on the name of the task near the compass  (in your screenshot it is a flight where the task has been completed, therefore there is a Task tab also). That is fine :-)

However : 

1 - there is a bug when browsing one flight after another in a list - the task card remains selected (blue vertical line on the left), but the task is not shown on the map. One has to click to deselect and click again to select the task card to see the task. Similar bug when the Task tab is selected : one has to select another tab, then Task tab again, to see the task on the map.

2 - sometimes the task cannot be seen without zooming out ([for instance here](https://www.weglide.org/flight/74061)). When selecting the task card the viewport should be extended to include both the whole flight and the whole task

3 - when the task was declared through WeGlide ([example](https://www.weglide.org/flight/48858)), there is a [link to the task](https://www.weglide.org/task/38226) with turn point names, leg distance, etc. ; when it has been declared in the logger, there should be ALSO such a link (as a new task) with the possibilty to save the task in[ My Tasks](https://www.weglide.org/task/mine?order_by=-stars)

4 - When the task was not completed, there should be ALSO a task tab for the flight, with statistics (legs completed, total distance on the task, virtual landing point on the map...). That would be especially useful for contests, but also to understand why the task has not been completed, in the case of a sector miss for instance. or when DMSt tab shows a free distance instead of the task because it yields more points.

5 - in the[ list a flights](https://www.weglide.org/flight?order_by=-scoring_date), there should be 2 more tabs : Task and Explore

6 - When no task was declared, it would better be indicated "no task declared", instead of hiding the task card

That's all for the moment ;-) Thank you again for this wonderful site and keep on the good work

**Comment by samuel-git** [comment]
Hi @deltafox44 thanks for the awesome feedback!

1. Definitely a bug, I am fixing this right now.
2. I do not think that would make it easier. Imagine a scenario where you are zoomed in on a turnpoint to compare the free distance to the declared task turnpoint by switching back and forth. Setting the zoom might be unwanted in this case.
3. This is a bit delicate because the logger declared tasks are not really public / intended for distribution. But I share your view. @moldhouse ?
4. Same problem as 2. with tasks which are "abandoned" in the logger and located somewhere entirely different. The statistics would be empty in a lot of cases and might be more confusing than helpful. Except for cases where the task is genuinely tried. Maybe we can build some kind of intelligent detection @moldhouse 
5. We will check, might be too crowded but we are revamping the tabs atm
6. We will think about it. Most people do not focus on task flying so this might be overkill but needs more feedback/testing.

:+1:

**Comment by deltafox44** [comment]
Thank you for your quick answer and hopefully fixing the small bug soon.

(2) I understand your point, but I think showing both task and flight still could apply to the initial zoom level (when selecting another flight, with "task" selected). Eventually, always showing the Task on the map (and task tab) will encourage pilots to make task declarations more often (especially for people used to OLC where there is only free flight). 

(3) I'm not a lawyer, but I would think that your [Privacy Policy](https://docs.weglide.org/docs/legal/privacy_policy/) covers that : "When you upload your flight logs on WeGlide [...], that information will be public". Sometimes, it is not easy with the map only to know what the declared task was, a list of turn points and legs would help (see for instance [this flight](https://www.weglide.org/flight/50186))

(4) That's right, often, the actual flight is completely different of the task declared (either through the logger or even through Weglide), due to the weather not being as good as expected, or just willing to fly without goal. Still, I suppose that your system evaluates the task every time there is a declaration. Hence, displaying its score will do no harm, even if it is just "no valid start" or "xxx km flown on first leg". In our french cup (Netcoupe) there has always been a bonus given for flights achieved as declared, so most pilots declare a task. Personally most of the times I try to fly the declared task and I think it's more funny than just heading to where the cumulus are...
