### ISSUE TITLE
EDMA SFG frequency

### ISSUE THREAD

**Issue by mar-da** [weglide/bugtracker#138]
**Describe the bug**
Airfieldinformation Augsburg EDMA incorrect:
DE/BY | EDMA | 120.685 MHz
correct frequency, only if glider-sector ist active 123.380, otherwise 124.980
So for foreign pilots the frequency shown should be 124.980, 120.685 is registered, but never used!

In Open AIP the following are displayed

Communication | SGF | 120.685 | Augsburg Segelflug 5
Communication | TOWER | 124.980 | TWR
Communication | SGF | 123.055 | Augsburg Segelflug 2
Communication | SGF | 123.380 | Augsburg Segelflug
Navigation | ILS | 108.500 | ILS 25
Information | ATIS | 119.665 | ATIS

The frequency chosen is the top frequency, which in this case is competely wrong.
120.685 and 123.055 are never used at Augsburg.

**Comment by samuel-git** [comment]
Thanks for the notice @mar-da,

we need to build some kind of ranking and assign e.g. TOWER a higher priority.
