### ISSUE TITLE
Let Copilots add Story Contents via own Account

### ISSUE THREAD

**Issue by isygc** [weglide/bugtracker#139]
If flights with a double seater are made copilots should be able to add story contents (upload pictures etc.) to the flight comfortably via their own account(and consequently mobile phone).  
Maybe add Checkbox for pilot explicitly allowing this.

*

**Comment by samuel-git** [comment]
Already done, maybe try emptying the browser cache until version v1.3.3 is displayed on the WeGlide homepage footer. Happy uploading :+1:
