### ISSUE TITLE
Missing WL versions on index list

### ISSUE THREAD

**Issue by JanJan3765** [weglide/bugtracker#14]
**Describe the bug**
Only standard versions of planes are available. 
Planes with modifications like winglets are not available. E.g. ASW24 available ASW24 WL not available

**To Reproduce**
Upload new igc file. Try to select ASW24 WL with index 108.

**Expected behavior**
DAeC DMST Index list like OLC

**Screenshots**
N.a.

**Device (please complete the following information):**
 N.a.

**Comment by moldhouse** [comment]
Jan, thanks for reporting. Have a look over [here](https://github.com/weglide/GliderList/blob/master/extended.csv), I have already added ASW 24 WL, it should be in production tonight.
