### ISSUE TITLE
Private messages

### ISSUE THREAD

**Issue by deltafox44** [weglide/bugtracker#140]
When looking at a flight it would be great if one could add public comments to the story, and/or contact the pilot by private message (either within weglide or by e-mail). Reserved for WeGlide users to prevent abuse and allow answers. Maybe with an option for each pilot to disallow comments and/or e-mails for all flights or for a particular flight. And/or forums about WeGlide (about Weglide/Flights/Weather/Other...) with the possibility to notify a pilot when one of his flights or his profile is quoted...

**Comment by samuel-git** [comment]
Great suggestion.
We are planing something like this but have to weed out the potential for abuse, repeating questions, reporting function, spam, etc.
Even when all this works there is a need for some kind of manual moderation.

In the meantime pilots eager to chat can write their contact details in the bio.

**Comment by samuel-git** [comment]
@deltafox44 done, we will improve this in the future.

**Comment by deltafox44** [comment]
> @deltafox44 done, we will improve this in the future.

Thanks :-)

It took me some time to find what had changed but I finally found "Write comment" in "Comments" section (I found no way of addressing private messages yet)... Two suggestions :

1. To help find it, put an icon "Comments" at the right of the "Like" icon, with a link to the "Comments" section
2. For clarity, separate pilot"s "Comment" from other people comments ; Pilot's comment would better be set into the beginning of his "Story", and other people comments in the "Comments" section would better be moved below the "Story" section

**Comment by samuel-git** [comment]
There where quite some changes in the last weeks regarding the comment design. I think we streamlined it quite a bit and everyone seems ok with it.

I disagree with putting the comments below the story as others want to to directly answer the pilots comment. The rest was valuable input when designing the new comment section. Sadly no space for a comment icon tough.

The only thing left here are private messages in my opinion. But not a priority at the moment.

**Comment by deltafox44** [comment]
Comments : seems fine :-)

Private messages : not needed within flight page, public comments are better. But , in user's profile page, instead of "Weglide ID" (not useful since it can be found in the URL) there could be a "Contact user" button to send a message. Or to display e-mail address. Eventually with an option for each user to disallow private messages, for privacy.

**Comment by samuel-git** [comment]
This is now available.

**Comment by deltafox44** [comment]
thanks 👍
