### ISSUE TITLE
Long meetings not detected

### ISSUE THREAD

**Issue by samuel-git** [weglide/bugtracker#141]
Tandem flights do often not reflect in meeting points, e.g.:
https://www.weglide.org/flight/77923
https://www.weglide.org/flight/77531

They both came close to each other for longer times but do not show up in the meeting section of the flights.
Other meetings show up.

**Comment by frantzheld** [comment]
Same at my team flight yesterday:
https://www.weglide.org/flight/78587
https://www.weglide.org/flight/78566

**Comment by moldhouse** [comment]
Thanks for reporting, this is fixed now.
