### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by samuel-git** [weglide/bugtracker#142]
Dark Mode.

_Originally posted by @flyingjoe in https://github.com/weglide/bugtracker/issues/80#issuecomment-766170883_

**Comment by samuel-git** [comment]
Had a working prototype but dark mode and maps/barogram is no good  match.
Indefinitely postponed.

(there might be a reason why there is no darkmode for google maps..)

**Comment by dibstan** [comment]
This is still relevant.
