### ISSUE TITLE
Show photo on map icon click 

### ISSUE THREAD

**Issue by samuel-git** [weglide/bugtracker#143]
How about making it possible to at least click on the picture-Icons on the map to show the selected photo?
That does not work on Chrome (PC) or Chrome (Android).
At the moment you can only see that a picture was taken at that point in the flight but you have to manually look for it in the picture list. (or am i missing something?)
Edit: yes, i missed that the plane-symbol on the map moves to the location of the picture when you hover over the picture. Kinda works also on mobile devices. The other way around would be very nice and more intuitive IMHO: click on map to show picture from that location.

Greetings,
Markus

_Originally posted by @Cumulus7 in https://github.com/weglide/bugtracker/issues/80#issuecomment-842243306_

**Comment by JoeHaenf** [comment]
I second that. Intuitively, I always tried to click on the picture markers on the map.

**Comment by deltafox44** [comment]
+1
A further suggestion, it would be great to show picture-Icons on the map of all flights, making possible to see all pictures taken by all pilots on a given day, without having to select the flights on the map one after another...
