### ISSUE TITLE
Some airports exists but cannot be found in the filtering list

### ISSUE THREAD

**Issue by deltafox44** [weglide/bugtracker#145]
**Describe the bug**
When typing the name of some airports, it is not shown in the list

**To Reproduce**
1. Select for instance Nogaro airport (from the map or as a departure airport of a flight) and click on "Flights as a list" you'll get [the list of flights filtered by departure airport Nogaro](https://www.weglide.org/flight?airport=Nogaro,151347&order_by=-distance)
2. Delete "Nogaro" filter
3. Type "Nogaro" : it should appear in the list but it does not
4. Same with [Cholet](https://www.weglide.org/airport/150449), [Requena](https://www.weglide.org/airport/161068), etc.

**Expected behavior**
When typing for instance "La Roche" in a list of flights, "La Roche sur Yon" airport appear in the list. Every airport should appear in the filtering list the same way.

**Screenshots**
![image](https://user-images.githubusercontent.com/82087770/124839013-44ef1e80-df88-11eb-805a-313d109d0b8a.png)
![image](https://user-images.githubusercontent.com/82087770/124839112-79fb7100-df88-11eb-94c1-19eabca4d111.png)

**Device (please complete the following information):**
 - Device: MacBookAir
 - OS: [MacOS 10.14]
 - Browser [Chrome]

**Comment by samuel-git** [comment]
Yes, I also encountered this. Only airports without any starts/landings are not shown in search.

**Comment by moldhouse** [comment]
This is by choice. Only a small percentage of the airports in our database have gliding activity. We do not sync the airports without activity to search on purpose as this should enable you to find the important airports much quicker.

**Comment by deltafox44** [comment]
That makes sense not to sync airports without registered flights. However, that's not the case for the examples above (up to 50 flights). Maybe it takes some time (months?) for the database to be updated ?

**Comment by shadowoneau** [comment]
There is also a number of flights out of Leongatha (VIC AU - YLEG), dating back to March 21. Leongatha also doesn't appear in the search/filter list.

Also I'm not sure what is going on with the club number of pilots/flights, as there clearly is flights there - do you want me to raise another issue?

![Capture](https://user-images.githubusercontent.com/5841265/147802849-c9892df5-72d4-4210-bbfe-242dd9c4dc0c.PNG)

**Comment by flyingjoe** [comment]
Should all be fixed now

**Comment by deltafox44** [comment]
👍
