### ISSUE TITLE
Information about flight simulator flights in the FAQ

### ISSUE THREAD

**Issue by dobrowolsk** [weglide/bugtracker#146]
I couldn't find any information about whether the upload of simulator flights (Condor, ...) is allowed or not. I'd appreciate it if any rule or decision about this would be documented in the FAQ or the rules.

The problem is that these flights are shown on the map like any other flight. But... I don't care what somebody did in their simulator. It just distorts the picture that a user gets of the day. As such, I'd like it very much if simulated flights would be banned or at least not shown on the map or in any lists.
Example: I saw this flight and got excited that somebody made it over the alps, only to find out it was simulated bullshit. https://www.weglide.org/flight/82874 clearly happened in Condor, as seen by this line in the IGC file: LCONFPLCondor version=2160
Example 2: https://www.weglide.org/flight/83263 - this flight is even more bullshit, but it's a more obvious fake.

Thanks for the great platform!

**Comment by moldhouse** [comment]
Thanks for the notice, we have added a section to our user agreement and FAQ and will update it tonight.
