### ISSUE TITLE
Who gave me a 'like'?

### ISSUE THREAD

**Issue by pcscholz** [weglide/bugtracker#148]
When I get a 'like' for my flight, I only see a small symbol for the person that gave me the like. Is there a way to find out who it was? 

- If yes, how do I find out? 
- If no, it would be a nice feature!

**Comment by samuel-git** [comment]
Hi @pcscholz we initialy tought so as well, but some users would like to stay anonymous when giving likes.
Knowing who liked your flight could generate peer pressure like "why did my friend x not like my flight today?".
We do want to avoid social network effects like these.
Hope you understand.

**Comment by samuel-git** [comment]
Reopened due to multiple requests.

**Comment by thbaero** [comment]
Maybe an options to like anonymously or by name would be an option. 

Or

The user settings are extended by an option to toggle anonymity for liking something in general.

**Comment by samuel-git** [comment]
For the sake of simplicity, I will try the option to show all likes and gather feedback. Worst case some pilots stop giving likes and we need to think about a settings toggle like @thbaero suggested.

**Comment by deltafox44** [comment]
In most social media one can see who gave a like. For instance Twitter (and her for "Thumbs up"). If you choose anonymity, it should be for all and no longer display the liker's icon. If not (which I'd prefer), hovering over the icons should display the names of likers, clicking should display the whole list.

**Comment by moldhouse** [comment]
This is now possible
