### ISSUE TITLE
Help wanted: Units

### ISSUE THREAD

**Issue by samuel-git** [weglide/bugtracker#149]
I need your help with this simple question to gather sensible default unit settings for every country.

Please state your
- Country
- Unit for climb rate
- Unit for cruise speed
- Unit for XC speed
- Unit for flight distance
- Unit for flight/airspace altitude

Thanks for your participation! 🔥

**Comment by deltafox44** [comment]
In France (for gliders only) : m/s ; km/h ; km/h ;  km ; m - the same in Spain

**Comment by samuel-git** [comment]
Same in Germany, metric.

**Comment by samuel-git** [comment]
British/AUS: Knots, Knots, kph, miles?, feet

**Comment by samuel-git** [comment]
UK measurements:

Flying speed / V- knots
Altitude - ft
XC Speed - kph
Distance - km
Climb rate - kts/min

**Comment by samuel-git** [comment]
I compiled everything that I know/got send here: https://github.com/weglide/translation/blob/main/units.ts
