### ISSUE TITLE
Highlight Barogram when statistics are selected

### ISSUE THREAD

**Issue by thbaero** [weglide/bugtracker#150]
** General Remark **
Please also have a look at the screenshots including some small red dots with white numbers inside. Those numbers (e.g. (1), (2), ...) are used in the text below to identify the specific features in the screenshot

**Describe the Feature**
When I select a specific Statistics element (see screenshot label (1)) the element itself is highlighted as well as the leg (2) in the map.
Feature-Request 1: It would be great if you could also highlight the appropriate area in the barogram (3).
Feature-Request 2: Also I would be happy if you could mark the counted thermals (4) in the barogram (5).

**Screenshots**

![image](https://user-images.githubusercontent.com/15811184/133105812-3376ba93-6d66-4d58-a509-c3cee8334c0a.png)

**Comment by samuel-git** [comment]
Highlighting the selected leg in the barogram ships with next release, thanks for bringing this back to attention!
Highlighting the thermals is something we are looking into. This requires some more changes to our backend as well.

**Comment by thbaero** [comment]
Thanks for the reply. Appreciate it.

**Comment by samuel-git** [comment]
Baro zoom highlights the corrisponding section on the map now as well. Thermals etc. is deeper flight analysis and already on the roadmap. :-)

**Comment by thbaero** [comment]
Great! Thanks!
