### ISSUE TITLE
API POST ranking query parameter "limit" not working

### ISSUE THREAD

**Issue by MrOlga22** [weglide/bugtracker#152]
**Describe the bug**
The query parameter "limit" on POST request for ranking is ignored.

**To Reproduce**
In bash: 
> curl -X POST https://api.weglide.org/v1/ranking?limit=1 -H "Accept: application/json" -H "Content-Type: application/json" --data-binary @- <<DATA
> {
> }
> DATA

**Expected behavior**
One result should be given back, instead of default 250.

("skip" parameter works fine)

**Comment by samuel-git** [comment]
This is by design to allow better caching on our end. We will deprecate the limit parameter and fix skip to 250 increments. (It is. 100 for other lists). Does this work for you?

**Comment by MrOlga22** [comment]
Should work for me. The skip parameter is already fixed to 250 increments according to my observations. Thanks for the quick reply.
