### ISSUE TITLE
31.Oct. is missing in "daily-best"

### ISSUE THREAD

**Issue by brunnair** [weglide/bugtracker#153]
**Describe the bug**
When navigating through the "daily-best" on the startup page, it's not possible to choose 31.Oct. as date, even if there are flights a this date.
When navigation with the "<" ">" symbols, it changes directly from 30.Oct. to 01.Nov. 

**To Reproduce**
Got to the startup page, click on the "<" ">" symbols and try to see flights from 31.Oct.

**Expected behavior**
Be able to see flights from 31.Oct.

**Comment by samuel-git** [comment]
Interesting bug. This is daylight saving time related. Internally ist uses 00:00 as time but suddenly it's 23:00 and the previous day. Thanks for reporting!

**Comment by samuel-git** [comment]
Fixed long time ago, forgot to close :-)
