### ISSUE TITLE
Displaying factors in Bitner result tab

### ISSUE THREAD

**Issue by p-bartczak** [weglide/bugtracker#156]
Could you write in the Bitner result tab all factor values used to compute the result?

1. Glider factor
2. Task factor 

I think I will help with the tests. It would valuable in the future also.

**Comment by p-bartczak** [comment]
E.g https://www.weglide.org/flight/27773 - instead green **2TP it** could be writen green **2TP - fk=1, fs=0,81**
fk - task factor
fs - glider factor

**Comment by moldhouse** [comment]
@samuel-git

**Comment by samuel-git** [comment]
<img width="396" alt="grafik" src="https://user-images.githubusercontent.com/22152728/151529721-f63c318e-34d9-4e4d-b1eb-710a53a13f1f.png">

Like this? We have space issues on small devices (text get's cut of and the "Free Distance" badges disappear) thats why it is not possible to put directly behind into the badge.

**Comment by p-bartczak** [comment]
Well done :)

pt., 28 sty 2022, 11:21 użytkownik Samuel ***@***.***>
napisał:

**Comment by p-bartczak** [comment]
Sorry but something is wrong. See attached screenshot

pt., 28 sty 2022, 12:43 użytkownik Przemyslaw Bartczak ***@***.***>
napisał:

**Comment by samuel-git** [comment]
Please post the screenshot again directly on github. Cant see it :-)

**Comment by p-bartczak** [comment]
Before there were no factors see [https://photos.app.goo.gl/waQGsfsc4cHnHzax5](url).

Now you I can see factors but fs factor for has wrong value. For

- https://www.weglide.org/flight/27773 flight it should be 0,82
- https://www.weglide.org/flight/117136 flight it should be 0,94

fs = 100/DeAC **NOT ** fs = DeAC/100

**Comment by samuel-git** [comment]
Good find, silly mistake. Is fixed for next version. Thanks!

**Comment by p-bartczak** [comment]
"Good find, silly mistake. Is fixed for next version. Thanks!" - so let mi know when it will be fixed in production and please don't close issues that aren't fixed on weglide.org.
I have no access to test environment.

**Comment by samuel-git** [comment]
Is fixed

**Comment by p-bartczak** [comment]
Why you didn't round fs?  https://www.weglide.org/flight/73488 E.g. fs=0.9259259259259259. Please round it up to 4 digits - in that case fs=0.9259

**Comment by samuel-git** [comment]
Are four decimal places needed? We normally use max. 2.
Also, do you have short explanations for less technical users what these values represent? I have a hard time explaining them in simple terms. And I fear they might confuse more than help.

**Comment by p-bartczak** [comment]
2 is not enough. E.g. ASG29 - 119 and Ventus 2C - 118.

- ASG29 - fs = 100/119 = 0,8403 = **0,84**
- Ventus 2C - fs = 100/118 = 0,8474 - if you drop two last digits = **0,84**

Rounding fs to 4 digits illustrates better difference between gliders.  I'll be responsable for explaining Bitner detail - so forward these users to me ;). Polish glider factors are 4 digit rounded

**Comment by p-bartczak** [comment]
Are you able to add hovers or any other form for explanation in Bitner tab?

fk=0.8 "task factor"  - Polish - "współczynnik zadania"
fs=1.1627 "glider factor" - Polish - "współczynnik szybowca"

**Comment by samuel-git** [comment]
Good feedback and ideas, thank you.
Is deployed with english hover text and 4 digit precision.
