### ISSUE TITLE
Bitner Cup. Display speed used for computing result

### ISSUE THREAD

**Issue by p-bartczak** [weglide/bugtracker#157]
E.g.  https://www.weglide.org/flight/27773 flight. In Bitner Tab is written 690.41 km @ **136** km/h.
IMHO it should be written 690.41 km @ **136.22** km/h

You use to count the result value with two digits. So please display value speed used for computing result.

It helps me to check flights - see https://docs.google.com/spreadsheets/d/1IAFQJLKICny2DAJm3tSOWkHY1G9mrv30cSgyIcF2luU/edit?usp=sharing

**Comment by moldhouse** [comment]
@samuel-git what do you think?

**Comment by samuel-git** [comment]
Done for next version. Might be abbreviated of on small devices but should be ok.
