### ISSUE TITLE
Height bug in map

### ISSUE THREAD

**Issue by ElPaule** [weglide/bugtracker#158]
I just found a _slightly_ big mountain in the main map. Don't know if it's a bug or just a wrong dataset.

<img width="398" alt="image" src="https://user-images.githubusercontent.com/54623099/151220591-ee28839a-4cef-4fb7-a006-28cf7186851c.png">

**Comment by samuel-git** [comment]
Nice find, it's a wrong entry in the dataset.

**Comment by samuel-git** [comment]
https://www.openstreetmap.org/node/4933545073#map=15/-43.5382/170.1108

Seems to be fixed in OSM. Will update with next map generation. May take some months.
