### ISSUE TITLE
Bitner Cup results aren't generated

### ISSUE THREAD

**Issue by p-bartczak** [weglide/bugtracker#159]
I've just added https://www.weglide.org/flight/121889 flight? Why it has no Bitner Cup tab with results?

How can I generate example resuts for common Polish club gliders like :
SZD-41 Jantar Std
SZD -48-3 Jantar Std 3
SZD-48 Jantar Std 2
SZD -42-2 Jantar 2b

**Comment by flyingjoe** [comment]
National Competitions like Bitner Cup are only calculated for flights where the user had set a club. Please don't add testing users as they will clutter the search. You can test it by uploading old flights from 2020 using your own account.
