### ISSUE TITLE
Scoring Window options disappear

### ISSUE THREAD

**Issue by tisoen** [weglide/bugtracker#16]
**Describe the bug**
Deleting all scoring windows and then using "add scoring window", all the buttons for scoring windows disappear. Also, the UI to modify the windows is not very intuitive (I first thought I wouldn't be able to modify existing scoring windows).

**To Reproduce**
1. Upload or modify a flight
2. Scroll to 'Scoring windows'
3. Delete all existing scoring windows via the "X" button
4. Klick "Add scoring window"
5. The buttons disappear and the barogram turns grey

**Expected behavior**
A new blank or auto-generated scoring window appears in the list (or maybe could be created by clicking in the barogram)

**Screenshots**
![image](https://user-images.githubusercontent.com/13700539/103137401-f0114800-46c8-11eb-88e0-5d6a6498b548.png)

**Device (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Browser Chrome 87

**Comment by samuel-git** [comment]
Hey @tisoen, thank you for this report. I am on it.
Any suggestions regarding the Usability of modifying the scoring windows?
Sadly all options to modify directly in the barogram are out because of mobile (too small).

**Comment by samuel-git** [comment]
Should be fixed and UX is improved (clear browser cache). Closing.
