### ISSUE TITLE
Personal Segements Ranking List on a Pilot's Profile Page

### ISSUE THREAD

**Issue by cpizer** [weglide/bugtracker#161]
It would be a nice feature if the rankings of all segements a user accomplished would be displayed on the profile page.
This ranking could be displayed just below the statistics and begin with the best ranking.
I think all seasons shall be included in this list, which can motivate pilots further to "collect" segements from time to time.

E.g.:
Segments:
The Rapture - Black Forest - 11. @ 122.60 points (147km/h)
Frankenstein - 17. @ 125.52 points (129km/h)
....

**Comment by samuel-git** [comment]
Cool idea! At the moment this is possible with filters in the segment tab but not obvious.

**Comment by samuel-git** [comment]
<img width="417" alt="grafik" src="https://user-images.githubusercontent.com/22152728/158435364-9b9145fe-4805-4179-a47e-ed4ffe78283f.png">

This is the solution going online tomorrow. Maybe a good compromise until we find somenthing more interactive.

**Comment by cpizer** [comment]
Looks great! I'll have a closer look at it tomorrow ;)
