### ISSUE TITLE
Zoom map to selected phase in phase analysis

### ISSUE THREAD

**Issue by thbaero** [weglide/bugtracker#165]
**Describe the Feature**
When Phase Analysis is selected one can choose between "Einzelne Phase" and "Barogram Ausschnitt". Now when I choose "Einzelne Phase" and I click in the statistics to one of the phases I would like to see the map is zoomed to selected phase.

It would also be nice to see some statistical data of that phase in a more dense way. Currently, it is rather spread out on the left and you have to scroll to see the data. Maybe another line on top of the barogram which displays the relevant statistical data of that phase would help here.

**Screenshots**
![image](https://user-images.githubusercontent.com/15811184/163775691-b808f32b-8b10-44cc-a0f6-17b64e303a64.jpeg)

**Comment by samuel-git** [comment]
You are confusing legs and phases. The pases are only displayed in the barogram with the phase statistics on top when hovering a phase in the barogram.

We need to find a better way to explain that.
