### ISSUE TITLE
Pan barogram with one finger on timeline

### ISSUE THREAD

**Issue by thbaero** [weglide/bugtracker#167]
Currently, one has to use two fingers to pan the timeline of the barogram when zoomed in. 

I think it would be nice if the x-Axis of the barogram could be configured that it will allow to change the timeframe (but keeping the zoom). This is easier than using two fibers to pan around the barogram on a mobile device. 

![image](https://user-images.githubusercontent.com/15811184/164709509-d23e3536-d29c-40e8-9942-1b9892e8810f.jpeg)

**Comment by samuel-git** [comment]
Sadly this is very difficult and not obvious to users. E.g. where can you swipe and where can you zoom?
I see the need for better barogram interactions though. But this is difficult and I have yet to find a better solution. More brainstorming is appreciated.
