### ISSUE TITLE
DMSt flights not scored correctly

### ISSUE THREAD

**Issue by CarstenSon** [weglide/bugtracker#17]
**Describe the bug**
On a declared triangular flight with direct approach without entering a possible FAI sector, reaching the airfield (according to point 4.5 of the DMSt competition rules) was not counted as rounding the last turn point. Declaration was detected correctly. Start altitude - finish altitude was less than 1000m.

**To Reproduce**
See flight https://beta.weglide.org/flights/3261 

**Expected behavior**
In case of a registered triangular flight with direct approach without entering a possible FAI sector at the finish, reaching the airfield (according to point 4.5 of the DMSt competition rules) should be considered as rounding the last turn point

**Screenshots**
see link above - change to DMSt-tab and click the 

**Device (please complete the following information):**
 - Device: any

**Comment by CarstenSon** [comment]
What I just noticed: At the first attempt I had taken over the suggested times for the scoring - but now the calculation is somehow stuck with adjusted (later) end of the scoring period.
But even with the previous scoring time, the entry into the 1km circle should have been done, but this was not acknowledged.

**Comment by CarstenSon** [comment]
I also just noticed by chance another flight where the scoring doesn't fit.
It is there a non-closed flight path and in the DMSt scoring a free triangle is recognized including the bonuses.
https://beta.weglide.org/flights/2683

Therefore I reset the title

**Comment by moldhouse** [comment]
These are three seperate issues. The triangle one was a scoring bug - thank you very much for reporting. It is fixed and will be in production tonight. The DMSt scoring is probably due to landing detected too early, see #20. Rescoring after scoring time changes also still seems buggy. 

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/24278651/103153602-f91a1c00-4791-11eb-90b6-f0e6a42ada3f.png">

**Comment by CarstenSon** [comment]
Hi Moritz,

thank you for the fast response again. Should i keep the issue open or close it as its solution is most likely that of #20?

I feel that at this point in time of the issues that have come to light, it would almost be better to have as concise a list of open issues as possible. 

If you think so as well you might as well close this issue and/or mark it as a duplicate.

**Comment by moldhouse** [comment]
Yes I think we can close this issue and continue discussion at #20
