### ISSUE TITLE
Flight is scored for wrong club in "DMSt Vereinswertung"

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#170]
**Describe the bug**
While uploading the flight, it was selected to score the flight for the second club of the pilot:
![image](https://user-images.githubusercontent.com/47079209/165056367-eccd08c6-8141-4375-9eb0-5e7cb01a8c12.png)

Nevertheless the flight is scored to the first club in the "DMSt Vereinswertung":
![image](https://user-images.githubusercontent.com/47079209/165056604-2a33e4e5-9ccc-421d-b9bc-f3052535671f.png)

**To Reproduce**
1. Go to https://www.weglide.org/ranking/dmst?season=2022&category=club&region=Niedersachsen,DE-NI
2. See in row 'Akaflieg Braunschweig':  [808,22] Jan Ole Gödeke
3. Click on the flight '[808,22](https://www.weglide.org/flight/140836) Jan Ole Gödeke'
4. See that the flight has been assigned to Hannoverscher Aero-Club, so it should be scored to this club in the DMSt

**Expected behavior**
The flight should be scored for the club which has been selected while uploading. (Hannoverscher Aero-Club)

![image](https://user-images.githubusercontent.com/47079209/165058967-424121ea-05d5-4ce9-bcd7-4f8d16937d73.png)

**Comment by moldhouse** [comment]
Thanks for reporting, race condition in the backend when scoring the flight. Fix will be deployed in the next few days.
