### ISSUE TITLE
Typos in local competitions docs

### ISSUE THREAD

**Issue by TobyF** [weglide/bugtracker#172]
**Describe the bug**
Typo/mis-translation in a few places on 'local competitions' English page

**To Reproduce**

1. Go to https://docs.weglide.org/premium/local_competitions.html

**Expected behavior**
Abonnement -> Subscription and fligth -> flight.

**Device (please complete the following information):**
Chrome browser, Windows Laptop

**Comment by samuel-git** [comment]
Thanks, fixed.
