### ISSUE TITLE
Task valid, non-detected

### ISSUE THREAD

**Issue by deltafox44** [weglide/bugtracker#174]
**Describe the bug**
The task has been completed but "Task" tab is not present
**To Reproduce**
See [flight 148258](https://www.weglide.org/flight/148258)
Task is shown as declared on the logger. Start line, turnpoint sector and finish line seem OK. But the "Task" tab is not present as when the task was not completed. Perhaps due to the fact that the finish line was crossed on the ground (which is valid, at least as of IGC rules)
**Expected behavior**
When a task has been declared, the Task box (below the glider id) indicates the Distance and type (O/R, triangle, 3TN...) but that's all...There should be also either "Completed", or the distance missed on task to the goal, or the next turn point, when not completed) i.e. "finish missed for 30 km" or "100 m to 2nd TP", or any other reason for which the system decided it was not completed (for instance altitude difference greater than 1000 m, if required). It would help understand why Task tab is not present and what was wrong.
**Screenshots**
![image](https://user-images.githubusercontent.com/82087770/167421291-e630d1cd-b73b-4ed6-90be-29424767fed5.png)

**Comment by moldhouse** [comment]
At the moment we only score tasks to the point where the landing is detected. We will look into that but will take some time. Showing more info why the task has not been completed is also in the works.

**Comment by deltafox44** [comment]
Here is another case where task has been completed but not scored (Task tab not present) - [flight 185021](https://www.weglide.org/flight/185021) on 13 July. I cannot see why Task tab does not appear, all waypoints were turned OK

The only particularity I see is that start line was crossed above 1000 m AGL (but less than 1000 m above finish line crossing) and at 260 km/h and that task was declared both via WeGlide - [task 135985](https://www.weglide.org/task/135985) and the logger (with a few meters difference in waypoints coordinates between the two, as often).

**Comment by deltafox44** [comment]
In this flight also https://www.weglide.org/flight/299894 the task has been completed, TP sectors, lines, loss of height are OK, in the Netcoupe [the same flight](https://www.netcoupe.net/Results/FlightDetail.aspx?FlightID=15657&HasPrevious=undefined) is scores "as declared" 

But WeGlide consider the task is invalid (red dot)... Why ???

As commented here https://github.com/weglide/bugtracker/issues/213#issuecomment-1796999385 clicking on the red dot should show why the task cannot be scored...

**Comment by deltafox44** [comment]
> In this flight also https://www.weglide.org/flight/299894 the task has been completed, TP sectors, lines, loss of height are OK, in the Netcoupe [the same flight](https://www.netcoupe.net/Results/FlightDetail.aspx?FlightID=15657&HasPrevious=undefined) is scores "as declared"
> 
> But WeGlide consider the task is invalid (red dot)... Why ???
> 
> As commented here [#213 (comment)](https://github.com/weglide/bugtracker/issues/213#issuecomment-1796999385) clicking on the red dot should show why the task cannot be scored...

#213 has been solved and now clicking on the red dot does show why the task cannot be scored - but apparently only for flights after mid-november 2023, thus the mystery remains for older flights...

**Comment by deltafox44** [comment]
#213 has now been solved and clicking on the red dot does show why the task is not scored (for new flights). To solve the mystery of the flights above, I re-loaded them and here are the results:

https://www.weglide.org/flight/148258
![image](https://github.com/weglide/bugtracker/assets/82087770/cb2e470d-6cc5-4933-85b4-2ecbfe322f8a)

- This is an out&return thus the message should be "finish line missed" 
- as said above by @moldhouse the problem is that crossing the finish line rolling (after landing) is not yet detected

https://www.weglide.org/flight/185021
![image](https://github.com/weglide/bugtracker/assets/82087770/0cabe00a-98d4-4ed7-b9e4-e437ccadc961)
In the original flight there has been a declaration through WeGlide adn the task is invalid. Re-loading the flight, it takes into account the logger declaration instead, and the task is validated !

The start altitude was 1301 m, the finish altitude was 1209 m (at 17:23:20). But at landing, the WeGlide finish line has been crossed again at 217m (at 17:51:26), and the task is apparently deemed invalid because the loss of height is greater than 1000 m ;  the finish point declared in the logger is 100 m more to the south thus there is no second finish line crossing and in this case the task is validated.

The WeGlide task seems to be invalidated for a loss of height exceeding 1000 m.

 https://www.weglide.org/flight/299894 
![image](https://github.com/weglide/bugtracker/assets/82087770/2fb37f2e-e16a-4688-8884-d85d411b5c6b)
Same problem as above, with a confirmation by the error message (altitude difference too large). Start altitude was 1185m, finish 205m at 17:58:57 with a second crossing at 168m at 18:00:51 

Conclusion : 

- there is a bug when there are several finish line crossings, it seems that the last one is taken into account, not the first, and in this case it invalidates a valid task.
- if there are several start or finish line crossings, the last start and the first finish should normally be taken into account (best speed)
- but if the loss of height exceeds 1000 m with these start/finish, a previous start or a later finish which yield a loss of height below 1000 m should be taken instead...

**Comment by moldhouse** [comment]
We have converted this to multiple internal issues which have been solved (not deployed yet), so I'll close this for now. As always, thank you very much for your accurate reporting and for helping us improve WeGlide 👍
