### ISSUE TITLE
Triangle task identification does not find the maximum

### ISSUE THREAD

**Issue by scalvin1** [weglide/bugtracker#176]
**Describe the bug**
Uploading some old flights, I realized that the scoring was unexpectedly low in some of them.
It seems like the triangle task contribution is not optimized correctly in some cases. To me it looks like the optimizer finds a local maximum due to the glider bumbling around for example before the task is open in a competition flight.
When changing the scoring window, sometimes a different task is identified, but I cannot get it to find the triangle I would expect.

**To Reproduce**
Seen in these flights: triangle task is tiny and obviously wrong.
https://www.weglide.org/flight/153627  (Winch launch, gap is not too big)

Other test cases, where the gap (horizontal and vertical) may be too big for closed triangle
https://www.weglide.org/flight/153607
https://www.weglide.org/flight/153605
https://www.weglide.org/flight/153606
https://www.weglide.org/flight/153647

OR/triangle tasks here
https://www.weglide.org/flight/153592 
(but could be because of the >1km distance between tow release and finish line)

**Comment by flyingjoe** [comment]
Thanks for reporting this!
As you already noticed, the gap between start and finish is too large for flights 2-6.

Flight 1 is a fun one - the distance between start and finish is slightly more than 1km by ~5-10m. When the scoring time start is moved to start one fix earlier, the big triangle is detected and everything looks fine.
