### ISSUE TITLE
Task declared via Weglide not accurate

### ISSUE THREAD

**Issue by deltafox44** [weglide/bugtracker#178]
**Describe the bug**
Task editor lets you select a turn point from WeGlide database with relatively low level of zoom, which is very convenient. Unfortunately, in the resulting task the turn point coordinates are not correct. The difference is small (up to 200 m) but may result in missing a start line or sector if the turn point set in the flight computer is from the database, not from WeGlide task export.

**To Reproduce**
Set a new task from two airports on the map at a minimum zoom level, save the task and download it - for instance : 
> name,code,country,lat,lon,elev,style,rwdir,rwlen,freq,desc
> "La Roche sur Yon-Les Ajoncs",,,4642.245N,00123.057W,86m,1,,,,
> "Lons Le Saunier",,,4640.521N,00528.148E,227m,1,,,,
> -----Related Tasks-----
> "524 km · Objectif · UK · La Roche sur Yon-Les Ajoncs_116441","","La Roche sur Yon-Les Ajoncs","Lons Le Saunier",""
The turn points of the task are 50 to 200 m away from airport symbols

Repeat with maximum zoom level : 
> name,code,country,lat,lon,elev,style,rwdir,rwlen,freq,desc
> "La Roche sur Yon-Les Ajoncs",,,4642.153N,00122.902W,87m,1,,,,
> "Lons Le Saunier",,,4640.504N,00528.148E,227m,1,,,,
> -----Related Tasks-----
> "524 km · Objectif · UK · La Roche sur Yon-Les Ajoncs_116440","","La Roche sur Yon-Les Ajoncs","Lons Le Saunier",""
The turn points are exactly on the airport symbols

**Expected behavior**
Name and coordinates should both correspond to the database.

**Screenshots**
![image](https://user-images.githubusercontent.com/82087770/170729539-642d1f1c-fa49-4312-a62d-3f1ba714b716.png)

**Device (please complete the following information):**
 - Device: MacBookAir
 - OS: MacOS
 - Browser: Chrome

**Comment by samuel-git** [comment]
This is a limitation of https://maplibre.org/maplibre-gl-js-docs/api/map/#map#queryrenderedfeatures Unfortunately not much we can do at the moment except for writing the coordinates directly into the feature properties which would a hack.

**Comment by deltafox44** [comment]
Thanks for the explanation.

By the way, is there a mean to download all waypoints used by the Task Planner within WeGlide, or to find the database somewhere ? 

This is to set the task in the flight computer without having to download the task .cup file and upload it to the flight computer each time.

**Comment by moldhouse** [comment]
Not at the moment, but we are working on custom turnpoints in the future.
