### ISSUE TITLE
Task box missing

### ISSUE THREAD

**Issue by deltafox44** [weglide/bugtracker#179]
**Describe the bug**
On [this flight](https://www.weglide.org/flight/159307) - straight goal flight from Lons Le Saunier to La Roche sur Yon on 26/05/2022 - there is task declared on the logger file but no Task **box** (the line with the compass below the glider ID line). There is no task **tab** either but this is normal, since the task was not completed. It happens to be a goal task, I don't know if this can cause the problem. 

Note that [the day before](https://www.weglide.org/flight/157817), it was also a straight goal flight, from La Roche-sur-Yon to Lons-le-Saunier, both task tab and task box are present, since it was completed as declared.

**To Reproduce**
No Task box in the flight page (see screenshot). Download the file, Task declaration is:
> C260522085636260522000100
> C0000000N00000000ENO_NAME
> C4640500N00528150ELONS LE SAU
> C4642216N00122716WLFRI X MDA
> C0000000N00000000ENO_NAME

**Expected behavior**
There should be a Task Box indicating the declared task, as it is usually even when it was not completed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/82087770/170730787-4d26f839-b0ac-4c2f-98ab-7f45cbb22b32.png)

**Comment by deltafox44** [comment]
I was not speaking of the task tab (which is there only when task has been completed) but of the task box (below the glider registration) not sure how you name it) containing the declared task. It was missing on my 26/5 flight. For comparison, yesterday I did not complete the task either thus no task tab  but the task box is there
![image](https://user-images.githubusercontent.com/82087770/170893515-c03df309-e320-4864-9ad3-d00ea9bc669d.png)

**Comment by moldhouse** [comment]
The problem seems to be in the igcfile itself:

C260522085636260522000100

The last two digits refer to the number of turnpoints of the task, in this case, 00. Therefore the task is skipped.

**Comment by deltafox44** [comment]
I disagree. The declaration in the file is correct. Start and Finish points are Waypoints but not Turnpoints. 

In a Straight Goal Task (from a start point to a finish point) there is 2 waypoints but no turnpoints, therefore the number of turnpoints of the task is 0 but the task should not be skipped ! 

See [IGC specification](https://www.fai.org/sites/default/files/igc_fr_specification_2020-11-25_with_al6.pdf) : 

`A3.5.1 Lines in the C Record. The first line contains the UTC-date and time at which the declaration was made, the number of Turn Points in the task (excluding the Start and Finish points), and a text string to describe the task ("500k
triangle", etc).`

`A3.5.2 IGC terminology - Waypoint/Turn Point. In IGC terminology, "Waypoint" refers to a either a start point, turn point or finish point. The term "Turn Point" (TP) refers to a point-of-turn between a start and finish point. The points that must be specified exactly in an official IGC flight declaration are the start-, turn- and finish-points either declared before the flight, or, for IGC "Free Flights", selected after flight. The number of TPs will be nil for a straight goal flight, one for an out-and-return, two for a triangle, three for 3-TP distance, more for competition polygon tasks.`

**Comment by moldhouse** [comment]
Thanks for pointing that out, will be fixed and I will rescore your flight.

**Comment by deltafox44** [comment]
it has been fixed, at least for newly uploaded flights

thanks
