### ISSUE TITLE
Plus Scoring  - 6th leg not long enough?

### ISSUE THREAD

**Issue by cdolain** [weglide/bugtracker#18]
hi,

a flight with 5 points + start/endpoints ends a bit early. 
I'd expect a distance of ~460km  but weglide extracts 400km.
One piece of an out and return at the end of the flight is missing.
I was expecting that the last / 6th leg is a bit longer. 

The flight is uploaded here:
https://beta.weglide.org/flights/3269
https://www.onlinecontest.org/olc-3.0/gliding/flightinfo.html?dsId=7816770

but maybe i just didnt understand the Plus-scoring  ;-) 

best regards,
Christoph

**Comment by cdolain** [comment]
[6th-leg.pdf](https://github.com/weglide/bugtracker/files/5742411/6th-leg.pdf)

**Comment by cdolain** [comment]
or here:
https://skylines.aero/flights/119519

**Comment by moldhouse** [comment]
Thanks for sharing this issue. This seem interesting indeed and is certainly not the expected behavior 🙃 I will look into it.

**Comment by cdolain** [comment]
Looks like the finalnpoint counts into the 5 intermediate points

Am 25. Dezember 2020 23:16:04 MEZ schrieb moldhouse <notifications@github.com>:
>Thanks for sharing this issue. This seem interesting indeed and is
>certainly not the expected behavior 🙃 I will look into it. >
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/weglide/bugtracker/issues/18#issuecomment-751295286

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by moldhouse** [comment]
Hi, I had a look into it. Problem is the scoring intervals, as an engine run is detected where scoring stops. You should be able to manually adjust scoring windows. Scoring your flight without the 'engine run' gives a distance of 463.22 km. So this is a duplicate to #19

**Comment by cdolain** [comment]
So you want your users to play around with enl Times?
Do i need to delete the wrong enl detection?
Longterm you'll Look into Lots of Support i guess. 

Am 26. Dezember 2020 16:48:39 MEZ schrieb moldhouse <notifications@github.com>:
>Hi, I had a look into it. Problem is the scoring intervals, as an
>engine run is detected where scoring stops. You should be able to
>manually adjust scoring windows. Scoring your flight without the
>'engine run' gives a distance of 463.22 km. So this is a duplicate to
>#19 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/weglide/bugtracker/issues/18#issuecomment-751368310

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by moldhouse** [comment]
No, we will try to detect the engine runs as good as we can. You can adjust the periods without engine / without tow after upload. I have some ideas how we can improve for high background noise and will look into it. I was just trying to say that this is not an issue related to the actual scoring algorithms but rather due to our faulty engine run detection (#19).
