### ISSUE TITLE
Set default home page view

### ISSUE THREAD

**Issue by llauner-se** [weglide/bugtracker#180]
**Describe the Feature**
As a user
I'd like to be able to set the default view for a customised home page
So that I can get to my prefered view, with prefered filtered applied by default.

For instance:
I'd like the home , or a new "my Home" menu entry to take me to the Flights / Map view + filtered on France

**Comment by samuel-git** [comment]
Hi, we have that feature, it's called "custom filters". It's on the right side on the home page. You need to be logged in.

<img width="570" alt="grafik" src="https://user-images.githubusercontent.com/22152728/172211962-b6321936-cc2b-488d-9235-3b3723b9d678.png">

**Comment by llauner** [comment]
Yes, I saw that, it doesn't do what I'm describing, or I didn't manage to achieve it:
I'd like to be able, in 1 click to go to the flights / Map view page + filters applied (France for instance).
Maybe another way implementing it is to have "view" filters where I could add a "Map View" custome filter ? + France + ...

**Comment by samuel-git** [comment]
Ah okay, this is too complicated in my opinion. I think the one extra click does hurt less than the added complexity in the UI.
