### ISSUE TITLE
Cannot import Task from .cup file

### ISSUE THREAD

**Issue by llauner-se** [weglide/bugtracker#181]
**Describe the bug**
The tasks stored in my .cup files are working fine in SeeYou or SeeYou Cloud

**To Reproduce**
1. Go to Task / Upload
2. Drag and Drop the attached .cup file
4. See error: "Attention no valid Task in file found"

**Expected behavior**
Tasks should be imported
.

**Device (please complete the following information):**
 - Browser Chrome
[v4_XCSoar.zip](https://github.com/weglide/bugtracker/files/8845053/v4_XCSoar.zip)

**Comment by moldhouse** [comment]
Thanks for reporting, I fixed the problem and will be released with the next deployment.
