### ISSUE TITLE
Move flight list to hovered flight

### ISSUE THREAD

**Issue by llauner** [weglide/bugtracker#183]
**Describe the Feature**
As a user
I want to be able to get the flight preview information when hovering over a track, even if the target line in the list is not currently viewable on the page
So that I can easily look at preview information of any flights

Description: 
In the flights map view: when you hover over a flight, the thickness of the track increases, and the corresponding flight has a grey background in the list on the left hand side.
However, when the hovered flight is not within the current "view port" of the list, we cannot see the grey highlighted flight details.

It would be nice if the target flight could be shown even if it's not currently within the items displayed on screen = the list would have to scroll up or down automatically so that we can see the corresponding details on the right hand side.

**Comment by samuel-git** [comment]
Good point, we did not do this to keep the mobile experience clean. But there might be a way to only do it when the info is displayed besides the map.

**Comment by samuel-git** [comment]
Coming with new release.
