### ISSUE TITLE
Live Tracking

### ISSUE THREAD

**Issue by B-Nicolai** [weglide/bugtracker#186]
**Describe the bug**
Not all gliders are available. Api should be the same...

**To Reproduce**
1. Go to https://live.glidernet.org/
2. Compare with weglide live...

**Device:**
 - Device: [Dell Laptop]
 - OS: [e.g. Windows]
 - Browser [Chrome, Edge, Firefox]

**Comment by julienrf** [comment]
I could not connect my glider, although you can see it in the [OGN database](http://wiki.glidernet.org/ddb-list) (my ID is 200E49). Is there something I missed?
