### ISSUE TITLE
Showing ALL flights in a given area

### ISSUE THREAD

**Issue by deltafox44** [weglide/bugtracker#187]
**Describe the Feature**
To find **ALL** flights that pass through a given region of the world (either via uploaded flights or live tracking). This would be particularly interesting when looking to remote areas, far away from glider airfields, or when pilots and departure airfields are not known, or when making use of the rich WeGlide database to preparing "exploration" flights far from home.

**1 - Uploaded flights**

Currently we can only find flights in a given area by filtering by country/region/airport of take-off.
If we want to display all flights that have passed through the area of the map corresponding to the display window, only a limited number of flight tracks will be displayed (by default the 100 most recent, otherwise the 100 longest distances, etc. depending on the sorting option). We can filter by country or region to increase the probability of finding flights in the area, but with the risk of missing those that took off in another country or region. One can also click on "Load more" to find more flights, but it seems that this is only possible about 10 times (1000 flights), after which all flights disappear.

In the following screenshots, here is an example where I search for flights that went to Vauville or the Cotentin (the peninsula), with the "France" filter. At first sight, there are no flights in the area :
![Capture d’écran 2022-06-23 à 01 08 41](https://user-images.githubusercontent.com/82087770/175348257-c408d11b-5fb5-4cdc-867e-432015c928d4.jpg)

You have to click 8 times on "Load more" to find the first flight in that area (3 weeks ago). After 10 "Load more" about 1000 flights are displayed (in this example, all flights of the last month, but not the flights before that). And, unfortunately, each time you click on "Load more", the system zooms out to show all the flights in the search :
![Capture d’écran 2022-06-23 à 01 10 12](https://user-images.githubusercontent.com/82087770/175348306-c798f62c-e48a-4bc0-8843-29f4e2ac972a.jpg)

You have to zoom in again to see the initial area : 
![Capture d’écran 2022-06-23 à 01 10 37](https://user-images.githubusercontent.com/82087770/175348355-b5bcab96-2a55-41f1-a2f0-ef90b57a25b7.jpg)

After the 11th time you click on "load more", all flights disappear, so that it is not possible to display more than 1000 flights (bug, or technical limitation for my computer, I don't know) :
![Capture d’écran 2022-06-23 à 01 16 10](https://user-images.githubusercontent.com/82087770/175348409-b4535813-70e9-4177-ad2b-aa43bc229c7d.jpg)

Filtering flight originating from nearby regions (North-West of France), and sorting them by distance (long flights first) improve the search results : 
![Capture d’écran 2022-06-23 à 01 27 02](https://user-images.githubusercontent.com/82087770/175348515-2b843ac8-09c0-4418-97f1-d8fe3df9ab32.jpg)

Even this way, only 8 flights are found in that area, impossible to know if there are more flights in the database, or not :
![Capture d’écran 2022-06-23 à 01 28 42](https://user-images.githubusercontent.com/82087770/175348578-57866fa8-4b58-429d-bb82-c567864924f7.jpg)

**Enhancement suggestion** : to display **ALL** flights passing through the area defined by the viewport. At least the last 100/200… 1000 flights. Or, better still, a coloured dots representation to indicate ALL the areas where there are flights, the colour indicating the number of flights, in the same way as on screenshot below (for live tracking). No coloration in a given area would indicate that **NO** flights in the database ever passed through that area.

**2 - Live tracking**

In live tracking, the current operation is somewhat different: by zooming in on any small area, it is possible to see if there are gliders or not. But here too, there will only be a limited number of flights, those with the greatest distance covered at that time. If the area is too large, it is therefore not possible to see all the gliders, you have to zoom in to see gliders appear (or not). 

I understand that due to performance limitations, it is not possible to display individually all gliders worldwide, but at low zoom levels it would be great to indicate the number of gliders in the area by a coloured dots representation, as on some live tracking sites (see screenshot below). This way, at first glance, when opening the flight tracker, it would be possible to see all the regions of the world where there are gliders flying, without need to zoom in to check whether there are gliders or not in a given area.

Looking at Weglide today, most gliders in mid-Germany or Czech Republic, no one in northern Germany, or England 
![Capture d’écran 2022-06-23 à 16 19 31](https://user-images.githubusercontent.com/82087770/175348729-0d5b04cc-3aae-4c30-84f4-87299be1b14d.jpg)

At the same time, on another tracking site, one can see many other areas with gliders : 
![Capture d’écran 2022-06-23 à 16 19 55](https://user-images.githubusercontent.com/82087770/175348762-922abd3d-f769-4d14-817d-8dcee1fa3f27.jpg)

in WeGlide, one has to zoom to see there are gliders in England :
![Capture d’écran 2022-06-23 à 16 20 36](https://user-images.githubusercontent.com/82087770/175348792-a6178a43-e312-41f6-809d-00f185c88e19.jpg)

**3 - Live tracking/uploaded flight**

Currently, on « Live » tracking, the flight disappears soon after a glider has landed. You have to switch to "Flights" and wait until the flight is loaded to view it again.

If possible (technically and legally), it would be great to show all flights together - either from Live tracking or from today’s uploaded files. « Live » menu item would be replaced by « Today » and all flights would be visible as soon as the glider has taken off and remain visible after landing. Once the logger file has been uploaded, the flight will remain visible at the same place, except the tracking data would be replaced by the more precise logger data.

To do that it is necessary to identify which FlarmID correspond to each logger/pilot account. There is probably no relation in the database, currently, between the Flarm ID and the logger ID of the same glider/pilot. And even if there were such a relation, there would probably be oversights and/or errors. But it should be possible to automatically identify which track corresponds to a given file by comparing positions at different times, so that when a logger file is uploaded the live track of the glider will be deleted from the list, to avoid duplicates.

Ideally it would be possible to keep the tracking history indefinitely, to display the track of any past flights even when file has not been uploaded (I’m not sure whether this is authorised with the current Flarm licence, but there could be a way for the pilots to give or not their permission for that)…

**Comment by samuel-git** [comment]
Great proposals, we are currently working on 2. and 3. There is a hard limit how long we are allowed to store flarm data (I believe 24h). Also, pilots can connect der Flarm to their account, this is the cleanest solution for matching live to the uploaded file. We could start by allowing comments or likes for live flights and transfer them to the uploaded flight when available.

More than 1000 flights on the map are a technical limitation of browsers.

I agree that there are areas for improvement in 1. but your proposal involves massive database queries. I am sure we can find a better solution than the current one though. We will think about it :-)

**Comment by samuel-git** [comment]
@deltafox44 we now show all live gliders on the map without zooming needed. Took some heavy performance optimizations but is better than a heatmap in my opinion. Thanks for pointing out the issue! This adresses 2.
For 3. we introduced live replay, not quite the sane but not everybody has linked their account and we can store the data not longer than a day. With this solution we keep it separated from the uploaded flights.
<img width="457" alt="grafik" src="https://user-images.githubusercontent.com/22152728/180192083-b04aeb73-a68d-49ab-a065-962599cb458e.png">

**Comment by deltafox44** [comment]
it's a great improvement ! Not only seeing all gliders live, but also returning to the last map zone ("bbox" in URL), easier displaying of course and baro of a given flight by double click, and switching from one glider to another directly via arrows... also, day replay with gliders and sat pictures ! many thanks ;-)

About displaying every single glider icon rather than a heatmap, yes I find it better too, and glider icons look very nice at first glance, but after a while but it quickly becomes clumsy when there are many gliders (also, perhaps negative effect on computer performance ?) and it does not provide much information. A good thing that now, contest number and altitude are shown besides the glider icon at higher zoom levels. There could be a different icon for glider in straight flight and when thermaling (such as a circle with radius indicating mean vario). The glider icon could be oriented to the direction of cross-country flight rather than the current course in the thermal. The icon could be greater for the glider that have scored more points, smaller for glider not on the list (those with less points scored). And the color of the icon could be related to the height range (for instance red when low...).

A few other details :

I spent some time before finding out that the number left of glider ID in the list (208 in the snapshot below) was the points scored...
![image](https://user-images.githubusercontent.com/82087770/180208026-1d8f1959-c19c-4061-a670-05431a60aa44.jpeg)
Perhaps it should read "208 pts" and/or be on the right after the glider ID.

Also, there is a link to the page of departure airport, 
![image](https://user-images.githubusercontent.com/82087770/180208984-d3580091-22e4-460b-b537-f03107a26de7.jpeg)
on this page there is the list of uploaded flights
![image](https://user-images.githubusercontent.com/82087770/180209327-790a76f1-72b5-40b0-8c74-a89512d09849.jpeg)
there could be also a list of live flights from this airport, or at least a direct link to the "Live" page with the airport filter...
![image](https://user-images.githubusercontent.com/82087770/180209793-0b966831-0a1a-442c-8925-35e4bf65462a.jpeg)

**Comment by deltafox44** [comment]
Back to subject 1. uploaded flights (finding all uploaded flights that pass through a given region) : I understand that it could involve too massive database queries. Perhaps it could be easier if recording, for each each flight, not only the departure airport but all airports within a range of 50 km or so from the glider's track (or all the airports that have been the nearest airport at any time of the flight, if more than 50 km).

This way, one could find not all flights in the area of the map corresponding to the screen, but all flights that passed nearby any given airport, via a link in the airport page, like it already exists for the flights originating from this airport...

**Comment by samuel-git** [comment]
I think this is something which has a use case and feels only "natural".
I added it to our roadmap but without a priority yet. 
Thanks for all the valuable input!
