### ISSUE TITLE
Login to Skysight Integration not possible

### ISSUE THREAD

**Issue by JoeHaenf** [weglide/bugtracker#188]
**Describe the bug**
I cannot use the SkySight Integration because logging into the integration does not work. As soon as I type one letter into the email field, the login box closes.

**To Reproduce**
- Go To Settings / Integration
- If you are already bound to SkySight, click remove to have the SkySight Email and Password fields displayed
- Start typing into the email field
- now the Email and Password fields disappear and the "remove" button appears

**Expected behavior**
I can enter my credentials completely

**Screenshots**
--

**Device (please complete the following information):**
Reproduced with Firefox 101.0 and Edge 103.0 (Windows 10)

**Comment by samuel-git** [comment]
Thank you very much, this bug is fixed for next release. 👍
