### ISSUE TITLE
Multi-Phase-Analysis: Phase analysis shows same data for all flights when comparing them

### ISSUE THREAD

**Issue by cpizer** [weglide/bugtracker#189]
When multiple flights are compared against each other and the phase analysis is selected, a row with a phase analysis for each selected flight is displayed above the barogram. However, all lines show the primary flight's phase-parameters and it's not possible to compare the parameters of multiple flights.

1. Select a flight
2. Select a wingmen and click 'compare'
3. Activate 'phase analysis' and set it to 'single phases'
4. Scroll through the barogram

Expected behaviour
If moving the cursor to a phase, for instance a thermal that was used by both pilots at the same time during a team- or competition-flight, I would expect to see the phase' parameters of both flights.

![Phase_issue](https://user-images.githubusercontent.com/59721050/176171711-f547e8e9-6522-4a8f-9c99-c2a7d9897ef0.png)

**Device (please complete the following information):**
 - Device: Asus VivoBook S14
 - OS: Windows 10
 - Browser Firefox 101.0.1 (64-bit)
 - Cache was cleared and bug still occurred

**Comment by samuel-git** [comment]
It is only possible to show phase analysis for one flight at once due to the visual overload and missing link between phase and pilot for multiflight phase analysis.
I removed the duplicate information. Thanks for the notice.
