### ISSUE TITLE
spurious engine run detected

### ISSUE THREAD

**Issue by cdolain** [weglide/bugtracker#19]
hi,

2 scoring-windows detected in that flight since it's a DG400 self-launcher with ENG recording;
https://beta.weglide.org/flights/3286

the competition scoring webpages  didn't detect the second motor-run. There was definitely only some motor-noise at the beginning.
https://skylines.aero/flights/121554

**Comment by moldhouse** [comment]
Hey, thanks for reporting. The ENL does seem quite high ~200 in large parts of the flight. We compute probabilities for individual times that the engine is running and probabilities for transitiong between the states and then try to find the the maximum likelihood decoding. The span where we have set the highest change in probability (of engine running) is between ENL of 100 and 200. If we set it higher, we don't pick up some engines runs, which makes it very delicate to select the right values. So ultimately we need the user to confirm / change the detected intervals.

The option I see is to compute some kind of background noise across the entire flight and to then subtract a base value to make the algorithm more stable to high background noise.

**Comment by cdolain** [comment]
Maybe with median value (Not mean!) and sigma or 3rd quartile minus 1st quartile of the enl distribution you should  be able to distinguish the Peaks of the Motor noise

Am 26. Dezember 2020 00:54:55 MEZ schrieb moldhouse <notifications@github.com>:
>Hey, thanks for reporting. The ENL does seem quite high ~200 in large
>parts of the flight. We compute probabilities for individual times that
>the engine is running and probabilities for transitiong between the
>states and then try to find the the maximum likelihood decoding. The
>span where we have set the highest change in probability (of engine
>running) is between ENL of 100 and 200. If we set it higher, we don't
>pick up some engines runs, which makes it very delicate to select the
>right values. So ultimately we need the user to confirm / change the
>detected intervals.
>
>The option I see is to compute some kind of background noise across the
>entire flight and to then subtract a base value to make the algorithm
>more stable to high background noise.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/weglide/bugtracker/issues/19#issuecomment-751300961

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by samuel-git** [comment]
#80
