### ISSUE TITLE
Live : Night flight ?!

### ISSUE THREAD

**Issue by deltafox44** [weglide/bugtracker#190]
**Describe the bug**
In LIve view, yesterday's flight and today's flight are merged into one.

**To Reproduce**
Cannot reproduce since it is Live view - see screenshot below and flights [176043](weglide.org/flight/176043) and [176010](weglide.org/flight/176010). Live tracking was lost at 600 m ground before landing at L'Aigle (probably due to poor Flarm coverage) and when it was recovered the next day in the same area it has been considered that the glider remained in flight all night long (though only the last 24 h of flight are shown) 

**Expected behavior**
When position has been recovered after a long time gap it should be considered as a new flight when it is likely to be so - for instance after 1 hour in areas where tracking is good at low altitude, or overnight in areas with poor coverage.

The opposite happened during flight [176043](weglide.org/flight/176043) : My logger had generated two IGC files due to a restart in flight. I uploaded the 2 files and the system showed 2 separates flight for 26 June, one departing from La Roche/Yon, another from L'Aigle (the airport closer to where the logger failure happened). Coming home only two days after, on my computer, I merged the two files in one , loaded if (flight 1760143) and deleted the two old files. But I could not find a way do it on my phone the night of the flight. Given that there is only a 16" gap at 1200 M AGL between the two files (10:28:54 to 10:29:10), the system could have merged the two files in one flight. Not a major issue, but perhaps the fact that by coincidence the failure happened at the same place where I took off the next day (L'Aigle), is somehow related to the night flight bug.

**Screenshots**

![night flight - 1](https://user-images.githubusercontent.com/82087770/176188449-ac2b9144-8a81-41c2-8a00-8e6a96dd906f.jpg)

**Comment by deltafox44** [comment]
quite similar case today, though in this case the glider was on an airfield so perhaps with the FLARM on  all night ?

![image](https://user-images.githubusercontent.com/82087770/178153079-8df096e1-8c0d-4533-a52b-97ad0b9bba39.png)


A few days ago, I saw a glider flight from [Chérence](https://www.weglide.org/airport/151214/pilot) early on the morning, it was in fact on the road to the Alps since the AGL height was about zero with a few peaks (GPS glimpses ?) to about 500 m (contest number LX, not sure of the date - I think it was July 8th at about 9 o'clock - and sorry no snapshots)

**Comment by deltafox44** [comment]
A quite different case : a few days ago, I saw a glider flight from [Chérence](https://www.weglide.org/airport/151214/pilot) early on the morning, it was in fact on the road to the Alps since the AGL height was about zero with a few peaks (GPS glimpses ?) to about 500 m (contest number LX, not sure of the date - I think it was July 8th at about 9 o'clock - and sorry no snapshots)

**Comment by moldhouse** [comment]
Thanks, we will look into this. Those bugs are hard to track as we don't store data longer than 24 hours, so providing as much information as possible (like you did) is very valuable.
