### ISSUE TITLE
Cache issue - old javascript code is loading

### ISSUE THREAD

**Issue by ArnulfKoch** [weglide/bugtracker#191]
(Nearly?) everytime in load weglide the first time, it shows an old version. 
See the screenshot:
Left side, when i type weglide.org in the browser, right side after pressing STRG+F5 to force a reload:
![weglide](https://user-images.githubusercontent.com/42880214/177048310-9501b09b-2c1c-4c34-be8a-f28b330ae893.png)

When i close the browser, start it again and open weglide.org, i see the left picture again.
This is on all pages, e.g. a flight analysis:
![2022-07-03 18_22_08-](https://user-images.githubusercontent.com/42880214/177048454-fc16569d-d457-4ef5-8b41-27c892f947e3.png)

I use Google Chrome on Windows 10 64 Bit:
"Chrome ist auf dem neuesten Stand
Version 103.0.5060.66 (Offizieller Build) (64-Bit)"

I saw the same on my android device (Samsung Galaxy S20 Ultra 5G).

**Comment by samuel-git** [comment]
Thank you for the issue. Please use https://www.weglide.org (with www.) for avoiding this caching issue.

**Comment by samuel-git** [comment]
Automatic redirect is installed since one week. Should not be possible to get an old version anymore. Please report if this somehow happens again. 👍
