### ISSUE TITLE
Filter for Alps doesnt work

### ISSUE THREAD

**Issue by cdolain** [weglide/bugtracker#192]
hi,

i have two flights starting in Dachau into the alps that i cannot see when Filter [Alpen] is active. They are on  April 17 2022 and  July 9 2022.

Both flights went far into the Alps and i would have expected to see them with Filter  [Alpen] so that i can compare with others that were flying in the region.

there's no result at all:
![image](https://user-images.githubusercontent.com/76599408/178122632-87d3182e-2846-4a0c-be75-e7b7272de16d.png)

this is on chrome on Windows 

best regards,
Christoph

**Comment by cdolain** [comment]
if only filter  {Alpen] is applied then todays flight doesnt show up in list as well.

![image](https://user-images.githubusercontent.com/76599408/178122779-1d1844ee-8b92-40a9-bb9a-4e78b7f64f34.png)

**Comment by cdolain** [comment]
those are the 2 flights that show up without [alpen] 

![image](https://user-images.githubusercontent.com/76599408/178122825-6283b5e1-abcb-4944-81c2-18171cb18a68.png)

**Comment by cdolain** [comment]
in this filter i can see flights that  were in [alpen] region - but it's also not really working.
The flight on May 30 2021 was not reaching the alps

![image](https://user-images.githubusercontent.com/76599408/178122926-c95953ab-0bb1-4365-a335-0c1372b3ca60.png)

**Comment by samuel-git** [comment]
Hi, the filter is applied to takeoff airport. See #187 for explanation.
We are happy to get a pull request regarding the boundaries of the alps here: https://github.com/weglide/flugfeld/blob/main/geo/sectors.json

**Comment by deltafox44** [comment]
> Hi, the filter is applied to takeoff airport.

It could be applied also to landing airport, and hopefully for turnpoints - at least when the turnpoints are an airport, since as I understand it, the region filtering use the list of airports, not coordinates...
