### ISSUE TITLE
Upload flight as Copilot

### ISSUE THREAD

**Issue by sbrodehl** [weglide/bugtracker#195]
**Describe the bug**
Unable to upload a (double seater) flight and declare yourself as the copilot.

**To Reproduce**
1. Go to 'Upload flight ' https://www.weglide.org/upload
2. Add igc file for a double seater flight.
3. You are automagically set as the pilot and can only add a copilot.
    (If you add yourself as the copilot, an error appears which states that you can not fill both roles.)

Similarly, if you edit an uploaded double seater flight, there is also no way to edit the pilot's name.

**Expected behavior**
I would like to be able to "switch seats" and be able to upload a flight where I am the copilot.

**Screenshots**
In the screenshot below, notice there is no field to edit the pilot, you are only able to add the copilot
![DeepinScreenshot_select-area_20220725123532](https://user-images.githubusercontent.com/7113492/180757746-c2d545ef-ede1-424e-99eb-631129d78994.png)

**Device (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone, desktop
 - OS: [e.g. Windows]: iOS and linux
 - Browser [e.g. chrome, safari]: chrome and safari

**Comment by scalvin1** [comment]
Good one! I also still have a few such flights to add, where the pilot currently does not care to do it and/or has no WeGlide account.
