### ISSUE TITLE
Broken Link to Taskplanner Documentation

### ISSUE THREAD

**Issue by rthaenert** [weglide/bugtracker#196]
**Describe the bug**
The help site for the task declaration tool in Weglide is broken (404).

**To Reproduce**
1. Go to 'https://www.weglide.org/task/plan/new'
2. Click on 'Help' (German 'Hilfe')
3. See error (link leads to https://docs.weglide.org/how_to/task_planner.html which cannot be found)

**Expected behavior**
Documentation site for the task planner (https://docs.weglide.org/tasks/plan.html)

**Comment by samuel-git** [comment]
Thank you @rthaenert this is now fixed for next release.
