### ISSUE TITLE
Live: The start in competitions is not detected

### ISSUE THREAD

**Issue by ArnulfKoch** [weglide/bugtracker#198]
Example Grand Prix Livno: https://www.weglide.org/live/competition/15
On some days, e.g. today (2022-08-06) the flight through the start line was not detected and the glider is in the state "Warten" (today e.g. for Jon Gatfield YO)
![2022-08-06 13_44_02-SGP Livno](https://user-images.githubusercontent.com/42880214/183247642-183333e5-b31a-4afe-9d92-de2675183868.png)
Perhaps he flew too close to the edge of the start line or the OGN signal fluctuated too much, but in the screenshot you can clearly see that he had a valid start. You should analyse the flight afterwards to find out why the take-off was not recognised. Because the Weglide live tracking interface is by far the best available, especially at competitions.

On the second day (?) in Livno it seems that the start window opened a few minutes earlier then in the task setting and every pilot stayed in the state "Warten". For this case maybe just ignore the given time and count flights up to one hour earlier als valid starts.

**Comment by samuel-git** [comment]
Thank you @ArnulfKoch we are still polishing out some details, live tracking is tricky because it happens exactly once.
But every bug report helps!
