### ISSUE TITLE
Live competition: Option not to display flight track before task start

### ISSUE THREAD

**Issue by ArnulfKoch** [weglide/bugtracker#199]
Feature request: There should be an option not to display the flight track before task start.

Reason: More clarity, e.g. if the flight track is already flown once at a ridge before take-off or if multiple take-offs are made in classic competitions
![2022-08-06 14_02_57-SGP Livno](https://user-images.githubusercontent.com/42880214/183248155-c25705f7-c12e-4a34-8542-beef443bcca8.png)
.

**Comment by samuel-git** [comment]
I like the idea. I would opt for a sensible default like:
Show the whole track until the task starts, then show from the task start until the current glider position and hide the beginning.

@moldhouse what do you think?
