### ISSUE TITLE
Declared DMSt tasks not scored correctly

### ISSUE THREAD

**Issue by flyingjoe** [weglide/bugtracker#2]
**Make sure it's new**
1. [x] I checked if there is already an open issue for my problem
2. [x] I have emptied my cache and reloaded the page and the problem still occurs

**Describe the bug**
Most DMSt declared tasks don't get recognized correctly.

**To Reproduce**
1. Upload a flight with a known valid task and flight
2. Check if the DMSt tab says it was declard

**Expected behavior**
Show declared task and add bonus points correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/28477393/103098727-2341d180-460c-11eb-97ef-f9fc92c0a934.png)
https://beta.weglide.org/flights/2413

**Platform**
 - any

**Comment by moldhouse** [comment]
This was also addressed in the latest updates.
