### ISSUE TITLE
Live competition: Show age of OGN data if older than 30 seconds

### ISSUE THREAD

**Issue by ArnulfKoch** [weglide/bugtracker#200]
Feature request: If the data is not really live at competitions (or live tracking in general), this should be made clear. For example, an exclamation mark could be displayed if the age of the data is more than 30 seconds or 60 seconds (or, if necessary, only after 90 seconds), indicating how many seconds (or minutes) the signal is old.

Reason: More clarity in assessing the competition situation, especially in Grand Prix competitions.

![2022-08-06 14_04_58-120 km · LY-VAR · Livno](https://user-images.githubusercontent.com/42880214/183248308-d97e615c-ad38-4b75-8609-d473d99c9586.png)

**Comment by samuel-git** [comment]
The left data indicates start time and end time (which is now if the glider is still in the air or in this case not over the finish line). I fear there is not enough space for a more complicated info but maybe something like the "stale" symbol.

The right one already shows the stale symbol (crossed out signal) and the last time seen. For me this is clear enough but I am biased so will think about something (maybe different colors).

**Comment by samuel-git** [comment]
Alright, I have to improve here. Thanks for the input :-)

**Comment by samuel-git** [comment]
Next update will bring the latest fix time displayed like this in the live overview:
<img width="414" alt="grafik" src="https://user-images.githubusercontent.com/22152728/236646743-f2a2c12f-055b-452b-8066-4816b140b8bb.png">

On the live detail page, there is a counter how long the latest fix is in the past:
<img width="415" alt="grafik" src="https://user-images.githubusercontent.com/22152728/236646800-2a8a7bb6-19ea-4d60-ab9a-bd7fb99b0322.png">

On the map, it is already quite colorful and I would leave it like it is for now.
