### ISSUE TITLE
Filter for gliders with and without engine

### ISSUE THREAD

**Issue by ArnulfKoch** [weglide/bugtracker#202]
Feature request: In the past, a differentiation was made between gliders and powered gliders. One has quite different possibilities regarding outlanding risks and thus, in the reality of working people, a massive influence on flights. Therefore, a filter for gliders with and without engine would be nice. 
Since this is only distinguishable in Germany on the basis of the registration number (D-[0-9] vs. D-K/D-M), perhaps it could only be shown for German competitions such as the DMSt or the DMSt League. Knowing that it has no influence on the official competition.

![2022-08-06 15_58_18-DMSt Rangliste](https://user-images.githubusercontent.com/42880214/183252543-32d85b35-995b-4b40-a6e7-1b1d434d18f2.png)

**Comment by samuel-git** [comment]
Related to #175. I think a general filter for the search is more universal and does not need so much UI space (but harder to find).
