### ISSUE TITLE
Remove/Hide declared task before upload

### ISSUE THREAD

**Issue by EDELJulian** [weglide/bugtracker#203]
Situation: 
If you fly spontaneously in a club glider, there might be already a declared task in the LX flight computer. This task will show up in weglide as declared task,  if you upload the flight later. 

Feature Request: 
Would it be possible to integrate a checkbox, to hide the unintentionally declared task, in case it was a freeflight?

**Comment by samuel-git** [comment]
I understand the whish for hiding the task. The only feasible option in my opinion would be an automatic way because this is a hard to understand checkbox (added UX complexity) with severe negative consequences (task get's not scored) vs. very little upside (minimal cleaner flight page).

I hope you understand my reasoning, feel free to respond if you do not share this view.

**Comment by deltafox44** [comment]
I agree with samuel (unnecessary complexity)

Moreover, the declared task is what is declared in the logger file (that's IGC law) and I don't see why it should be hidden. On early IGC loggers, on had to declare the task before take-off, on more recent loggers it is automatic and by such may be unintentional. But the pilot can avoid that by deleting the task in the logger before taking off. Or, by declaring a void task through WeGlide. 

The only problem when viewing the flight in WeGlide is that the "Task" Tab is present every time there is a declaration in the file, and one has to click on it only to find out, sometimes, that there was no attempt to fly the task in the actual flight. Or that it is an old task from a remote airport and that it cannot even be seen without zooming out. 

A good enhancement would be to show within the Task box the **status of the task** : Completed, xxx km to first/second/third turn point/finish, or "No start" (which will be the case with an unintentional, remote task). By now, there is only the distance and type of task, and "Completed" if it is the case).

It would be useful for every flight with a declared task and would help to understand why it is not scored as "Completed" (see https://github.com/weglide/bugtracker/issues/174 & https://github.com/weglide/bugtracker/issues/136)
