### ISSUE TITLE
Can't edit task, only visible for me, after "Declare for national competition" and then "Delete Declaration"

### ISSUE THREAD

**Issue by ubx** [weglide/bugtracker#204]
**Describe the bug**
Can't edit a task only visible for me anymore after "Declare for national competition" and then "Delete Declaration".

**To Reproduce**
Steps to reproduce the behavior (WeGlide ID = 747):
1. Create a task, check "Only visible for me"
2. Declare the task (ex. for 1 day)
3. Delete Declaration
4. The task shows: "Can't edit task because it was declared."

**Expected behavior**
It should be possible the edit the task that is only visible for me and is not declared.

**Device (please complete the following information):**
 - Linux AIO5 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 - Linux
 - Firefox 104.0.2 (64-bit)

**Comment by moldhouse** [comment]
We are aware of this problem and will try to adjust it. The reason you can not edit tasks after they have been declared once is that you might have flown them in which case the declaration can get lost. Consider the following:

1. You create and declare a task and fly
2. After finishing the task successfully, you don't upload the flight straight away
3. You delete the declaration and edit the task for the next day
4. You upload the flight, but the declaration is deleted and does not count
