### ISSUE TITLE
When editing your own flight, you can edit the flight of others

### ISSUE THREAD

**Issue by Witloofboer** [weglide/bugtracker#207]
**Describe the bug**
When editing your own flight and clicking away to a different flight, you can edit the flight of someone else. You cannot save the changes.

**To Reproduce**
1. Edit pictures of a flight.
2. Select a different flight from for example the "wingmen"
3. You will see the edit-options on the other flight as well.

**Expected behavior**
Edit options should not be present

**Screenshots**

**Device (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

![image](https://user-images.githubusercontent.com/10199682/197760784-c75487ab-959f-459e-8e69-e1545ac2de65.png)

**Comment by samuel-git** [comment]
Fixed for next release :-)
