### ISSUE TITLE
All but one members missing from our club.

### ISSUE THREAD

**Issue by sirapm** [weglide/bugtracker#208]
Greetings.
When we look at at profiles and click on our Club
"Wellington Wairarapa Gliding Club"
Only one member is showing up, Bruno T.

When looking at "Ranks"
Only Bruno T, shows up from the club.

When filtering for "Wellington Wairarapa Gliding Club" under Flights, we see a lot of WWGC pilots and their flights. 
If one click on "Wellington Wairarapa Gliding Club" (the name displayed as a filter) in the filtered flights list, we are back to only Bruno T showing up.

Bug?
Some settings/prefs missing?

This is all when I'm using Google chrome/Edge etc on Windows and Linux.

Cheers
Martin F

**Comment by samuel-git** [comment]
Hi @sirapm,
only pilots with flights from the current season are showing up.
Will make this clearer in next release and add the "all seasons" option as default later on.
Thanks for reporting

**Comment by sirapm** [comment]
Well, more than Bruno in our club have logged flights so there is still a
problem.

**Comment by samuel-git** [comment]
The other flights are not valid as seen here by the missing green badge on the left hand side: https://www.weglide.org/flight?order_by=-scoring_date&club=Wellington%2520Wairarapa%2520Gliding%2520Club,1034

**Comment by samuel-git** [comment]
By default, now all pilots are shown for a club which uploaded at least one valid flight whenever. Thanks for the valuable community feedback regarding the confusion the previous default season filter to current season caused.
On the left hand side, the season filter can be re-applied by users as needed but defaults to "all": https://www.weglide.org/club/1034/pilot
