### ISSUE TITLE
Invalid flight/story not showing up in flight list

### ISSUE THREAD

**Issue by scalvin1** [weglide/bugtracker#209]
An invalid flight does not show up in any lists, not even in my own flights.
I can access it only directly knowing the link. Example https://www.weglide.org/flight/224209
Of course it is my own fault that I broke things here: I constructed an IGC file conforming to the IGC file rules (but clearly the flight is invalid by G record and should get 0 points) with the intention to add a picture story for an old flight from a time before loggers and cell phones were everywhere.
Maybe as a feature idea (if it is not possible to get a 0-point flight into weglide like this), there should be a way to add something as 'ignore the IGC issues, 0 points, 0 kms, this is story only'.

**Comment by samuel-git** [comment]
Hi @scalvin1,
invalid flights should show up in your profile and greyed out in lists.
Maybe the problem is the zero points thing, do you have the IGC file for me so I can investigate the issue?
Thanks

**Comment by scalvin1** [comment]
I worked around it already. I don't have the file anymore, it was 'very invalid' with only three or four B-records.
Please close the bug.
Thanks!
