### ISSUE TITLE
Link preview showing wrong flight distance and speed

### ISSUE THREAD

**Issue by techolga** [weglide/bugtracker#210]
**Describe the bug**
When sharing a flight for example via telegram the messenger shows e.g. 🏁 1150.5km @ 189.12 km/h as preview for https://www.weglide.org/flight/224809

**Expected behavior**
Correct distance and speed of this flight should be 🏁 1507.5km @ 164.63 km/h

**Screenshots**
![grafik](https://user-images.githubusercontent.com/36713373/201517124-9ad64aa8-fa85-49bc-81a5-24be52e428ed.png)

**Device (please complete the following information):**
 - Device: Android app
 - Firefox (web.telegram.org)

**Comment by flyingjoe** [comment]
This seems to be caused by telegram caching our response (indefinitely?). 
I think the scoring windows incorrectly detected, someone sent the flight via telegram and then the scoring windows were fixed. Not much we can do about that unfortunately..
