### ISSUE TITLE
Add missing "WeGlide-Link" Information in exported cvx/Excel data

### ISSUE THREAD

**Issue by E2nO** [weglide/bugtracker#211]
Observation / Issue:
When I export the filtered flight list as JSON file, the very first Parameter of each JSON entry is "**id**" and this parameter provides a straight forward link the the data set in WeGlide that can be easily accessed by creating the url https://www.weglide.org/flight/id

Unfortunately this information is not included when exporting to cvs or excel file format. Thus these exports are missing a "direct" connection to the WeGlide data set - to get to the specific record one would need to share (and enter) all information to filter for a unique data set.

**I therefore propose to have the id (alternatively the complete url) added as an column "id" (or "url") to the csv and/or excel export.**

Use Case Example:
For a decentralized competition we have to provide a listing of flights that for various reason cannot be generated / filtered in WeGlide. Thus I export the pre-filtered listing (here: a club & a season) and perform the remaining specific filtering and some manual selection in Excel. (E. g. reducing ~150 flights to roughly 1/5th (30 flights)) I then can send the list to the competition judge, however he will have for any flight he wants to check (so up to 30) "copy" quite a bunch of information to get to the correct flight. However "copy" is not the correct word, because the process will require a lot a manual entry effort to reach that goal. If I could provide a direct link to the flight data set in WeGlide, then opening a flight for display in WeGlide would be a matter of a mouse-click.

Evaluation and Last Words
Sure, I alternatively could provide the Link-information  "manually" for the 30 selected flights - but then it will just be a pain in the butt for me instead of the judge. Perhaps I would rather "sed" the JSON export, copy the extracted id data into my Excel and then easily create the required link. But still I believe that adding the requested feature will enhance the overall user experiences when dealing with communication of sets of flights as I guess that perhaps few "end users" can rely on sed or other unix command tools as easily as me.  I also believe the adding of this feature will cost very little effort & time (for someone that knows where to add the column in the export).

**Comment by samuel-git** [comment]
@moldhouse for me this looks like a sensible improvement.

**Comment by moldhouse** [comment]
This has been added, thanks for the idea.

**Comment by E2nO** [comment]
Excellent, works like a charm, Thank you!
