### ISSUE TITLE
Status of the task

### ISSUE THREAD

**Issue by deltafox44** [weglide/bugtracker#213]
**Describe the Feature**

When viewing the flight in WeGlide the "Task" Tab is present every time there is a declaration in the file, and one has to click on it only to find out, sometimes, that :
- the task was set a few days before and is not related to the flight, 
- or the task originates from a remote airport and cannot be seen without zooming out,
- or the task can be seen but obviously the pilot changed his mind and did not attempt to fly the task that day,
- or the task was abandoned during the flight

When the declared task appears to have been flown, but is not scored as "Completed", there is no indication about what was wrong (start line, turn points zones, finish, engine restart...) and it may be difficult to figure it out. 

**Enhancement request** 

To show within the Task box the **status of the task** : Completed, xxx km to first/second/third turn point/finish, or "No start" (which will be the case with an unintentional, remote task). 

Such as 
![image](https://user-images.githubusercontent.com/82087770/213875282-98f23af9-6b61-4e3d-a983-bb45f536cc04.png)
to emphasize that the task was completed (wuthout having to look whether the task tab is present or not)
or
![image](https://user-images.githubusercontent.com/82087770/213875417-cd5d4488-d3f0-426a-9a02-dd9b1c4703c3.png)
to clearly state why the task has been missed

**Screenshots**

For instance in my [26th july flight](https://www.weglide.org/flight/193220), the task was not updated and still was the task of the preceding day:
![image](https://user-images.githubusercontent.com/82087770/213875606-a059221c-5d7d-4413-92da-3241a9580326.png)

In [my 13 july flight](https://www.weglide.org/flight/185021) where the task appears to have been completed correctly but is not scored (no task tab); there should be an indication why the task is not valid, if so :
![image](https://user-images.githubusercontent.com/82087770/213875733-297577be-b933-4c2e-9b44-8dccbd3efa41.png)

See also already reported issues https://github.com/weglide/bugtracker/issues/174 & https://github.com/weglide/bugtracker/issues/136).

**Comment by samuel-git** [comment]
We are aware of this issue but it is a hard problem to solve. Thanks!

**Comment by deltafox44** [comment]
Update : there has been significant improvements :   
- now there are green or red dots for status of the flight and to indicate whether the task has been completed or not - see [my 13 july flight](https://www.weglide.org/flight/185021) and compare with above
![image](https://github.com/weglide/bugtracker/assets/82087770/fb3b2496-8505-4f40-aa19-bb1a8247836a)
- if the flight does not intersect with the declared task, the task is not shown

Still missing : when there is a red dot, indicating why (start, TP or finish missed, altitude difference > 1000 m... in my 13 july 2022 flight all these are OK and I still cannot see why the task is red)

Improvement suggested : when the task is shown (after clicking on the task box) then switching to next flight (with left/right arrows on top), on has to click  again on the task box to show the task ; this should be changed for convenience and to be coherent with other boxes (satellite picture, Likes, Stats) where the selection remain unchanged for all flight in the list

**Comment by deltafox44** [comment]
Still missing : when there is a red dot, indicating why (start, TP or finish missed, altitude difference > 1000 m... in my 13 july 2022 flight all these are OK and I still cannot see why the task is red)

Improvement suggested : when the task is shown (after clicking on the task box) then switching to next flight (with left/right arrows on top), on has to click again on the task box to show the task ; this should be changed for convenience and to be coherent with other boxes (satellite picture, Likes, Stats) where the selection remain unchanged for all flight in the list

**Comment by samuel-git** [comment]
@deltafox44 we implemented a detailed description of what went wrong with the task, thanks for your input!
<img width="411" alt="grafik" src="https://github.com/weglide/bugtracker/assets/22152728/d5ae0593-c45a-46d2-b7ca-a71192257d4a">

**Comment by deltafox44** [comment]
that's perfect, thank you !

it seems that it only applies to new flights... there is still a mystery for some older flights

Also, one still has to click on the task box for every flight in a list (see above "Improvement suggested")
