### ISSUE TITLE
Airports with multiple runways

### ISSUE THREAD

**Issue by deltafox44** [weglide/bugtracker#214]
**Describe the bug**
The runway displayed on the map may not be the main runway (though the main runway is correct in the airport data list)

**To Reproduce**

see Soria : https://www.weglide.org/airport/189927 : main runway 09 in the list, shorter 02 runway on the map airport symbol

**Expected behavior**
The runway displayed on map should be the main runway (or the longest, if no 'main runway' defined)

**Screenshots**
![image](https://user-images.githubusercontent.com/82087770/213877932-da589d8d-b8f9-4a1c-a670-827fabe7a784.png)
vs AIP 
![image](https://user-images.githubusercontent.com/82087770/213876586-fbfc1ef7-6ed0-4aa6-9e6d-3b1ef5fa2204.png)
![image](https://user-images.githubusercontent.com/82087770/213876727-9a0566df-22d2-4ad6-8930-033720fafe70.png)

PS: since https://github.com/weglide/bugtracker/issues/133 frequency problem seems to have been solved, I opened a new issue for runway (not a big problem though, since what is most important is main runway length/width and it is indicated in the list)

**Comment by samuel-git** [comment]
@moldhouse this is a data conversion issue from openAIP to our map layer.

**Comment by deltafox44** [comment]
Seems good now, at least for Soria
![image](https://github.com/weglide/bugtracker/assets/82087770/0d882f87-8b1f-463c-bd09-099c61357753)
