### ISSUE TITLE
local competition broken after deleting task

### ISSUE THREAD

**Issue by CarstenSon** [weglide/bugtracker#215]
**Describe the bug**
When cleaning up my tasks in the planner I apparently also deleted a task used in a local competition. When I open the flight it shows that local competition. If I click on it says "no flights yet"

**To Reproduce**
1. create local competition
2. have some gliders fly it
3. delete the task during winter depression
4. Don't be able to open the competition but still see the competition

**Expected behavior**
Either the task should not be deleteable or the competition shouldn't appear in the flight information or the competition task should be available despite the deletion of the task (as some kind of different entity) 

**Screenshots**
Happened for that flight: https://www.weglide.org/flight/207055

**Device (please complete the following information):**
 - Device: most likely all, don't have enough local competitions
 - OS: most likely all
 - Browser FF all the way (but most likely also others)

**Comment by moldhouse** [comment]
Thanks for reporting. The general issue is fixed and I will delete the scores for this task manually later on.
