### ISSUE TITLE
enable pilots to link a flight with declared task to a local competition

### ISSUE THREAD

**Issue by CarstenSon** [weglide/bugtracker#216]
**Describe the Feature**
If you declared a task that is used in a local competition but didn't use the online declaration feature you should be able to "link" the flight to the local competition afterwards

**Screenshots**
For example this flight: https://www.weglide.org/flight/207030 flew the same task as this one: https://www.weglide.org/flight/207055 but didn't participate in the local competition for some reason. 

The computing ressources should be manageable for this as there will lost likely not be too many local competitions from one airfield during the time of departure and landing and the airfield for departure and landing was already calculated.

**Comment by moldhouse** [comment]
Thanks for taking the time to describe this issue and sorry that it took us so long to get back to you. The reason that the flight was not scored on the task (which has now apparently been deleted) was a bug from our side, which we have now fixed. As any flight is now scored on the task, the link to the local competition should work automatically again. In case I have missed anything, please reach out via email again.
