### ISSUE TITLE
US/GB/AUS altitude scale is in multiples of 3281 feet

### ISSUE THREAD

**Issue by demccormack** [weglide/bugtracker#217]
**Describe the bug**
When units are set to GB/AUS or US, the altitude graph at the bottom of the flight screen has labels of 3281, 6562 etc. It would be more user-friendly to place the gridlines at multiples of 2000 feet.

**To Reproduce**
1. Go to 'Profile'
2. Click on 'Settings'
3. Change units to 'GB/AUS' or 'US'
4. Click 'Save'
5. View a flight

**Expected behavior**
The altitude scale should be in round numbers of feet such as 2000, 4000, 6000 etc.

**Screenshots**
<img width="641" alt="Screenshot 2023-02-03 at 11 22 39 PM" src="https://user-images.githubusercontent.com/52194107/216580250-6bfcfcae-375d-45b5-9cde-5a493b64ef19.png">

Thank you for building WeGlide. It is a truly fantastic web app!

**Comment by moldhouse** [comment]
@samuel-git I agree that it would be sensible to have round numbers.

**Comment by samuel-git** [comment]
Thank you, this is fixed for next release.
<img width="263" alt="grafik" src="https://user-images.githubusercontent.com/22152728/219206083-4d811f8a-2ab5-490d-b370-a928ff14ae96.png">
