### ISSUE TITLE
No Date Recorded in H File Uploading from XCSOAR.

### ISSUE THREAD

**Issue by Brosaybrobro** [weglide/bugtracker#218]
Uploading the IGC file to other viewers works fine. (Soaring lab etc.) However ton WeGlide has the error "No date recorded in H File." 
In the IGC files, the H file does record a date in the following format.  "HFDTE060223" 

Using XC Soar on a late model Android.

**Comment by moldhouse** [comment]
Can you send the corresponding file to info@weglide.org or upload it here?
