### ISSUE TITLE
Live: new aircraft appear on map only after they receive a new position

### ISSUE THREAD

**Issue by MariusMangold** [weglide/bugtracker#219]
https://user-images.githubusercontent.com/51188180/217586765-2f691dbd-e26e-4135-8c6d-2399f04f4cb1.mp4

Wie im Video zu sehen verschwinden in der Tagesrückschau beim Heranzoomen Flugzeuge, es sollte wahrscheinlich andersrum sein.

**Comment by samuel-git** [comment]
Danke Marius!
Ist notiert und wird mit dem nächsten größeren Live Update behoben.

**Comment by flyingjoe** [comment]
Sollte mittlerweile gefixt sein, gerne wieder öffnen, falls es noch einmmal auftritt
