### ISSUE TITLE
Improvement: User should be able to upload Waypoint file to plan task

### ISSUE THREAD

**Issue by henrik-the** [weglide/bugtracker#22]
**Improvement:** 
It would be a great feature, if a user could upload own waypoints in the task planner.

**Possible solutions:**
Most intuitive, but probably most work:
User can upload Waypoint file (.cup) and select the waypoints on the map by clicking on them.

Less work, but not so intuitive:
User can upload Waypoint file (.cup) and select waypoints in a drop-down list to create task.

**Comment by moldhouse** [comment]
We serve waypoints in the .mbtiles format. However, this seems difficult for user defined waypoints as we would need to host possible thousands of individual layers. 

First approach:

Convert waypoints to geojson, frontend adds custom geojson layer on top of mbtiles. 

Second approach:

Store waypoints in DB and convert to MBtiles on the fly (gustav).

**Comment by samuel-git** [comment]
First approach should be feasible up to 1k waypoints.

The better solution might be to encourage contributing to one single waypoint collection.
Maybe tagged for easy filtering.

@henrik-the what is your opinion/wish on this matter? (will dedicate quiet some time in the upcoming weeks to taskplaner UX)

**Comment by henrik-the** [comment]
I think one big public Database would be a good idea!
But then the filter feature would be a must. For example it should have the option to only display your own waypoints. 

For me it would be okay to add the waypoints manually as a first approach (e.g. a form), because i only have a few (<20) waypoints that i use regularly.

On the long run the public Waypoint Database with tags combined with powerful filtering options (for viewing and exporting the waypoints) would be a great help for planning Tasks.

**Comment by moldhouse** [comment]
Yes, I like the idea of one database with filtering options very much. By enabling tags and descriptions, users could also share wavepoints, outlanding spots or hotspots (we have some more ideas towards hotspots). I think the difficult problem is getting high quality data and to prevent users flooding the DB by placing the same waypoint with three different names and slightly different coordinates. 

Having one database would also enable popularity features (count how often a waypoint is referred to from a task) and to then make waypoint appear on the map ordered by popularity when zooming in / out.

**Comment by samuel-git** [comment]
#80
