### ISSUE TITLE
Filter does not work on a local competition ranking

### ISSUE THREAD

**Issue by didier-kuttel-private** [weglide/bugtracker#221]
I have created a local competition with an AAT task, I get a ranking with 3 pilots, one of these started from another airport and I want to filter him out as he is not part of the competition.

How to reproduce:
1. Look at my competition - its is called "LSTR - Test - 1"
2. Try to filter on AD Montricher

Yves Müller, started from Zwiesimmen he should be filtered out

![WeGlideProb](https://user-images.githubusercontent.com/17776989/221705212-73404aa2-ef64-4576-bc19-9b5eac33a21a.png)

**Comment by moldhouse** [comment]
Hi, thanks for reporting. We'll fix this with the next release.

**Comment by samuel-git** [comment]
We removed the option to filter local competitions for now because competitions are bound to an airport or specific date anyway and the flights therefore limited.
