### ISSUE TITLE
My Club is also Missing

### ISSUE THREAD

**Issue by smgrieve** [weglide/bugtracker#222]
**Expected behavior**
Hamilton Texas Soaring Club should appear in the list its missing and we are very sad about this. 

**Screenshots**

**Device (please complete the following information):**
 - Device: [mac]
 - OS: [macos]
 - Browser [ safari]

Feature request would be to allow people to add clubs.

**Comment by moldhouse** [comment]
Your club is added now, sorry for the delay. Enjoy the upcoming season!
