### ISSUE TITLE
Segements Download always downloads Json

### ISSUE THREAD

**Issue by lordfolken** [weglide/bugtracker#223]
Hi, 

Thx for the great work! 

When selecting download on the weglide page https://www.weglide.org/segment?season=2023 the download drop down lists several formats:
* json
* cup
* txt
* tsk

No matter what i select there, the contents of the file seem to be json, eventhough the filename changes. 

I would love to add these to the XCSoar's data repository (via link) https://github.com/XCSoar/xcsoar-data-content

Regards,
 - Folken

**Comment by samuel-git** [comment]
Thank you @lordfolken, this is fixed for next release.
