### ISSUE TITLE
Altitude / max Altitude filter

### ISSUE THREAD

**Issue by groundhogxc** [weglide/bugtracker#224]
A filter for flight altitude would be great. Specifically, most useful would probably be "max altitude".

Use case: Trying to look at all flights that were *not* wave flights on a given day (use a filter max_altitude < 3000 for example), or, conversely, to look at all flights of a region that were wave flights (max_alt > 3000 or whatever is useful for that region).

Of course if you have a better idea to filter for wave, that'd be fine as well... (Circling fraction < some percentage could also be useful for example, could also be applied to ridge flying).

**Comment by samuel-git** [comment]
<img width="957" alt="grafik" src="https://user-images.githubusercontent.com/22152728/235297599-cd9a1237-61f9-41b9-86fd-bcd7f3c055c4.png">

here a quick idea how this could look like @moldhouse

**Comment by groundhogxc** [comment]
> <img alt="grafik" width="957" src="https://user-images.githubusercontent.com/22152728/235297599-cd9a1237-61f9-41b9-86fd-bcd7f3c055c4.png">
> 
> here a quick idea how this could look like @moldhouse

Looks nice!
But I would not call it "wave", but rather just "altitude" if it is purely a max-altitude-based filter with no other wave-specific properties.
