### ISSUE TITLE
Uploaded flight missing, can't upload again

### ISSUE THREAD

**Issue by benhirashima** [weglide/bugtracker#225]
I uploaded a flight on April 22, 2023. The flight was made the same day. The flight does not appear on my profile or when I search for my name (Ben Hirashima). I tried to upload the IGC file again, but got a message that it has already been uploaded.

The logger was an LXNav 9050 on firmware 9.02. IGCShell says the file is valid. A task was declared and completed.

**Comment by benhirashima** [comment]
Here is a link to download the IGC file in question: https://drive.google.com/file/d/1vJYxtESgDx9EAkrN7Ax4e9f6gzNim-e0/view?usp=sharing

**Comment by flyingjoe** [comment]
Please send Emails in such urgent cases, as we cannot monitor the bugtracker daily
