### ISSUE TITLE
Add SSA regions in the USA

### ISSUE THREAD

**Issue by benhirashima** [weglide/bugtracker#230]
**Describe the Feature**
Currently, flights and ranks can be filtered by region, club, airport, and state/province. However, SSA regions are not included. In the USA, the country is divided into 12 regions by the SSA. They are known simply as regions 1 through 12. Here is a list of regions and the areas they cover: https://www.ssa.org/groups/type/region/. I would like to be able to filter by SSA region, like I can do on OLC. I'd suggest naming the regions something like "SSA Region 1", and so on.

**Comment by samuel-git** [comment]
@benhirashima can you point us to a working link of the region areas? Somehow my google game is not good enough.

**Comment by benhirashima** [comment]
@samuel-git I got the following from the SSA. Most US states belong to only one region, so the state to region mapping is 1:1, as listed in state_region.csv. However, there are three states that are divided between two regions. They are PA, MO, and CA. In these cases, the states are divided by zip codes (postal codes). In split_states.csv, there are ranges of zip codes assigned to regions. The hard part will be to determine where the dividing line should be, based on the zip codes. It doesn't need to be exact. As long as the correct airports are on the correct side of the dividing line, it should work as intended.

> The state defines the region except when the region is 0 and the key is 1, then the code uses a range of zip codes in a lookup table to assign the appropriate region where states are split; PA, MO, and CA

[split_states.csv](https://github.com/weglide/bugtracker/files/12083894/split_states.csv)
[state_region.csv](https://github.com/weglide/bugtracker/files/12083896/state_region.csv)

**Comment by moldhouse** [comment]
The regions are now available both in the list and the ranking.

**Comment by benhirashima** [comment]
@moldhouse I'm excited to hear that the SSA regions have been added, but I'm unable to find them on the site. How are they named? I tried searching in both Flights and Ranks for the expected keywords such as "SSA" and "Region", but saw nothing.

**Comment by moldhouse** [comment]
Sorry, it's available now

**Comment by benhirashima** [comment]
@moldhouse I see the SSA regions in Flights and Ranks now. However, I am not seeing them when I try to customize the filters on the homepage. Could that be added? Thanks.

**Comment by samuel-git** [comment]
@benhirashima it is added now, thank you.
