### ISSUE TITLE
Rocket(wo)man badge not received

### ISSUE THREAD

**Issue by Okrummel** [weglide/bugtracker#231]
I had a thermal over 630m with 6.1 m/s average but did not receive the badge.

![Screenshot_2023-05-24-16-24-58-50_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/weglide/bugtracker/assets/134522207/49d9d09e-fb54-4215-8fc2-9a8ca9cb04c8)

https://www.weglide.org/flight/256962

**Comment by moldhouse** [comment]
Thanks for the notice. It is hard to correctly identify thermals when the logger interval is high (4s), but we'll try to adjust our algorithms.
