### ISSUE TITLE
Free Ranking for California is broken

### ISSUE THREAD

**Issue by benhirashima** [weglide/bugtracker#234]
**Describe the bug**
The free ranking for California is broken. Many pilots in the top 20 have flights scored that were not in California. Only flights that originated in California should be counted in the ranking for California. The rankings for Sprint, O&R, and Travel by Glider appear to not be affected. Only the Free ranking is incorrect.

**To Reproduce**

1. Click Ranks
2. Type in California
3. Leave all other settings as default
4. Observe how many pilots in the top 20 have flights scored that were not in California. For instance, the current number 3 ranked John Johnson has five flights scored that were entirely within Arizona.

**Expected behavior**
Only flights that originated in California should be included in the best-of-five flights for California.

**Screenshots**
![CaliforniaFreeRanking](https://github.com/weglide/bugtracker/assets/1156502/b81bd4d2-1e9f-4e96-928a-057aba0b32b0)

**Device (please complete the following information):**
 - Device: Intel based desktop
 - OS: Windows 10
 - Browser: Firefox

**Comment by moldhouse** [comment]
Thanks for reporting. This should be fixed now. Feel free to reopen, if you encounter this again.
