### ISSUE TITLE
Aufgabenerstellung, Lachen Speyerdorf nicht anwählbar

### ISSUE THREAD

**Issue by RM9412** [weglide/bugtracker#235]
Wenn ich eine Aufgabe planen möchte, kann ich Lachen Speyerdorf zwar auswählen aber es wird immer Ludwigshafen Dannstadt eingetragen als Wendepunkt.
von Apple sowie Android  und Windows probiert.

Gruß

**Comment by samuel-git** [comment]
Hi, thanks we are working on it. In the meantime just zoom in a bit more on the map and then type in / select the turnpoin
t.

**Comment by samuel-git** [comment]
Schould work properly now.
