### ISSUE TITLE
Cannot assign second club in profile

### ISSUE THREAD

**Issue by phorward** [weglide/bugtracker#237]
**Describe the bug**

Hello! I cannot save a second club. There is no error message. Nothing happens.
After investigating the network traffic, I've found that weglide responds an HTTP error 400 with the message

```
{
	"error": "second_club_forbidden",
	"error_description": "Only allowed to set second club until 31st of May"
}
```

**To Reproduce**
1. Go to https://www.weglide.org/settings/profile
2. Enter a second club
3. Click the "save" button
4. No response, nothing is reported to the user.

**Expected behavior**

Why am I not allowed to assign a second club?
The message is not displayed to the user. Anyway, the field should be removed, because it cannot be set. (Why?)

**Screenshots**
![shot-2023-06-15_23-58-45](https://github.com/weglide/bugtracker/assets/16870072/25dfb581-c0a6-46cd-a282-853f0b27b55f)

**Device (please complete the following information):**
 - Device: Thinkpad T460p
 - OS: Arch Linux
 - Browser: Firefox 114.0

**Comment by flyingjoe** [comment]
Hi, 
I cannot reproduce the missing error message. 
Adding a second club is not allowed during the league season to prevent cheating in the leagues. 
We'll have a second look at this rule.
