### ISSUE TITLE
Themal statistics: effiency of thermaling by showing altitude gain & loss in thermal

### ISSUE THREAD

**Issue by bschellekens** [weglide/bugtracker#238]
**Describe the Feature**
Part of the learning curve of becoming a solid gliderpilot is how effective you can thermal. Both in centering, as well as keeping within the center during the thermal. SeeYou has the statistics to show how much altitude you gained and lossed during thermalling, broken down in each thermal phase. You can calculate this as the % of altitude loss you have during thermal in respect to the altitude you gained. The lower the percentage the more efficient you have thermalled.

Places where to add this feature:
1. The statistics page, see [example LS8](https://www.weglide.org/flight/statistics?aircraft=LS%25208%2520neo,459&distance_gt=%253E%2520400%2520km,400). In the column Thermal you would like to add the %alt loss
2. The statistics table Thermalling on the flight page, where you can see the % alt loss over the flight and per leg
3. Phase analysis, where you can see per thermal the % altitude loss you had in this thermal.

**Screenshots**
An example as to how this might look like for the phase analysis:
<img width="669" alt="Screenshot 2023-06-18 at 08 45 23" src="https://github.com/weglide/bugtracker/assets/7326010/ea98cfb4-d864-40d8-9ca0-27afc05366cc">

**Comment by samuel-git** [comment]
Interesting idea. We are sadly heavily space constrained in the statistics list and phase analysis. Maybe we find a spot :-)

**Comment by moldhouse** [comment]
Hi, thanks for bringing up this very interesting idea. We evaluated it and sadly did not find a way to implement this in a good way, as we are space constrained and also have the problem that sometimes you lose some altitude if you speed up or recentre, which is not necessarily bad.
