### ISSUE TITLE
Date Selector is hard to find

### ISSUE THREAD

**Issue by flyingjoe** [weglide/bugtracker#24]
**Describe the bug**
Users have a hard time finding the date selector to be able to view all flights of a single day.

**To Reproduce**
1. Go to flights
2. Try to find date selector

**Expected behavior**
Users shouldn't have to search around for a date selector. 
Opening it by searching for a date is also not intuitive.

**Screenshots**
![image](https://user-images.githubusercontent.com/28477393/103173509-c76d8780-485b-11eb-834c-fd9a3c091f44.png)

**Device (please complete the following information):**
Any

**Comment by flyingjoe** [comment]
A possible solution would be to have it prominent next to the search at all times.

**Comment by KonstantinDib** [comment]
I think this would also be a nice feature for some more common filters like country, region or class.
