### ISSUE TITLE
Subscribe to club

### ISSUE THREAD

**Issue by lordfolken** [weglide/bugtracker#240]
**Describe the Feature**
Currently one can subscribe to individual users and see their flights. 
It would be fantastic if i could subscribe to the entire club with one click. 
Or maybe a list on the club page with tick boxes for each pilot.

**Comment by moldhouse** [comment]
Hi, you can currently set a custom filter on the start page to always see the newest flights from one day. We think that the complexity introduced by following clubs is too great.
