### ISSUE TITLE
Sortierung in Flugsammlungen

### ISSUE THREAD

**Issue by KiwiRacing** [weglide/bugtracker#241]
**Describe the bug**
In Flugsammlungen ist die Sortierung von Flügen nach den Filtern in der oberen Leiste nicht möglich.

**To Reproduce**
1. Klicke auf eine Flugsammlung
2. Klicke auf die sortieren Schaltfläche
3. Die Liste nach einem Parameter sortieren lassen
4. See error (Liste sortiert nicht)

**Expected behavior**
Liste sortiert korrekt

**Device (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS
 - Browser WeGlide Widget (Safari)

https://github.com/weglide/bugtracker/assets/137898711/702ba1a5-c733-4b1b-8cb4-c9f42bb133ea

**Comment by moldhouse** [comment]
Thanks for reporting, will be fixed with the next release.
