### ISSUE TITLE
Extend voting/ popularity contest to photos and flight description

### ISSUE THREAD

**Issue by scalvin1** [weglide/bugtracker#243]
It would be interesting to have a 'photo of the month' or 'flight description of the month' feature.

This could maybe be realized by allowing users to give 'hearts' or similar votes directly to the pilot's flight description, and also to individual photos.

Then there could be a photo or flight documentation ranking to add a new angle to the contest.
Also, it would encourage people to take more/ even better photos and to add more detailed descriptions to their flight stories.

**Comment by samuel-git** [comment]
Hi @scalvin1 thanks for the suggestion. Allowing likes for all individual images and descriptions makes thinks too complex for pilots who just want to express their appreciation (like) for a flight. We decided against it.
