### ISSUE TITLE
Sattelite-Picture shifted

### ISSUE THREAD

**Issue by LaeriutWS** [weglide/bugtracker#244]
**Describe the bug**
The sattelite-pictures are shifted.

**To Reproduce**
1. Go to https://www.weglide.org/flight/305698
2. Click on 'Satelittenbilder'
3. From 12:45 UTC - 13:00 UTC, the sattelite-pictures are shifted (observe the lakes)

**Expected behavior**
The lakes should not be on another place from 12:45 - 13:00.

**Screenshots**
-

**Device (please complete the following information):**
 - Device: Desktop-Computer
 - OS: Windows
 - Browse: chrome

**Comment by moldhouse** [comment]
Hi, this should be solved for future images, thanks for the hint.
