### ISSUE TITLE
Electrical power comsumption is wrong for JS3 RES

### ISSUE THREAD

**Issue by amguettler** [weglide/bugtracker#246]
**Describe the bug**
For the electrical self launch JS3 there is bar which shows power consumption of the motor in kWh. However this seems to be wrong by about a factor of 3.

**To Reproduce**
1. Go to https://www.weglide.org/flight/314203
2. Click on the lightning symbol with "0.72 kWh" below the aircraft name
3. Scroll down to barograph, and use mouse wheel to zoom in to beginning.
4. Hover mouse over beginning of graph and notice that it says power usage is 103.95 kW, which is way beyond what the motor is capable of delivering. Hover a bit more to the right and it around 12 kW, and then a bit later during the climb and it shows about 7 kW before going to 0.
5. The battery remaining also seems to be off. It starts at 92% and drops to 71% for the take off and climb. Actual for the flight was 100% to 81%.
6. The bar on the left says battery usage went from 84% to 66%, where do the 84% value come from?
7. The bar on the left says usage was 0.72 kWh, while actual usage was about 30% which should be about 2.7 kWh.

My other flights, and other JS3 RES flights I have seen all have the same errors.

**Expected behavior**
These values are wrong, the actual used power was 40 kW for the initial take off, and then 25 kW. I don't know where the 103.95 kW value comes from, but 12 kW and 7 kW sort of makes sense if multiplied by a bit more than 3.

I noticed my LX9070 was also initially showing similar errors, but the configuration was wrong in that its configuration had its batteries at 120V, while they actually are 380V. When I changed it to 380V the LX shows correct values. Is there is similar voltage assumption in weglide which could cause the error? This flight was made after I made the adjustment to the LX-configuration.

**Screenshots**
![usage](https://github.com/weglide/bugtracker/assets/139278627/a092811a-1872-434d-8b5c-72d05bb728b6)
![baro](https://github.com/weglide/bugtracker/assets/139278627/f04da97f-1cae-4ec5-a84c-37ce8732355e)

**Device (please complete the following information):**
 N/A

**Comment by moldhouse** [comment]
Hi, thanks for bringing this up, and sorry for the very late response. Reaching out via email is our preferred way no and we try to reply to all support requests within 48 hours. It was really helpful that you described everything in such detail.  There are two issues, the first one with the voltage and the second one with the capacity.

1. The problem indeed seems to be with the voltage. It is not provided as an extension in your igc file, so we assume a fixed voltage, which is wrong for the RES.
2. As your igc file also does not provide left battery ("leb"), we need to assume a fixed capacity, which is wrong for the RES.

Do you have any idea, why this data is not written? It would be great to check with LX directly. If you contact them, please cc me (moritz at weglide dot org), so we can find a solution for this.
