### ISSUE TITLE
Airspace map updates

### ISSUE THREAD

**Issue by deltafox44** [weglide/bugtracker#248]
**Describe the bug**
When airspace is updated on OpenAIP, it is not on WeGlide maps before a certain time (weeks, months ?)

**To Reproduce**
See for instance Madrid TMA, class A :
1. Go to [OpenAIP map](https://www.openaip.net/map#8.81/41.1413/-3.6946)
2. Click on TMA1 (on the north-west part of the TMA) : it is above 9500 ft 
3. Look at the same area on [Weglide](https://www.weglide.org/airport/161168)
4. there is indicated a VFR sector with base at 10500 ft around Villacastin which no longer exists this year (refreshing or clearing cache does not change anything)

**Expected behavior**
Airspaces should be up to date. The Madrid TMA has been updated on OpenAIP 2 weeks ago, on 27th July. If there is no automatic update for WeGlide maps there should be a mean (here or elsewhere) to warn you when an important update has been made somewhere.

**Screenshots**
OpenAIP
![image](https://github.com/weglide/bugtracker/assets/82087770/e3db3e76-a35a-4549-9f9c-6cb9ce2e75ac)
WeGlide
![image](https://github.com/weglide/bugtracker/assets/82087770/0da175c4-6d7e-434a-b0da-bfac175c3dec)

**Device (please complete the following information):**
 All

**Comment by moldhouse** [comment]
Thanks for the hint, we will update on a more regular schedule in the future.
