### ISSUE TITLE
The map and replay has stopped

### ISSUE THREAD

**Issue by sscotchm** [weglide/bugtracker#249]
As of yesterday the ability to see a flight, hit the "play" button and replay the flight has disappeared from my Samsung galaxy fold running Android. 
My profile and my friends profiles still show the flights and maps. But when I click on that flight the stats and details are at the bottom but the map at the top is blank. 

Anyone having the same experience ? Any cures ?

Cheers
Steve

**Comment by samuel-git** [comment]
Can you send a screenshot? This should not happen.

**Comment by moldhouse** [comment]
Hey Steve, I will close this until you provide more information. You can also contact us via info@weglide.org

Feel free to reopen with more infos.
