### ISSUE TITLE
Livetracking glider filter

### ISSUE THREAD

**Issue by knuffo** [weglide/bugtracker#250]
**Describe the Feature**
A clear and concise description of what you wish for and what pain point it solves.

Most of the cases you want to track multiple but specific glider.
It would be great if we can filter the WeGlide Live view to self defined list of "favorites" glider.
Like on glideandseek.com

**Screenshots**
If applicable, add screenshots from similar features to help explain

see attached screenshot:

<img width="563" alt="4" src="https://github.com/weglide/bugtracker/assets/30173568/b2e71aac-4b5c-42b2-b836-e11a0bf45ece">

**Comment by samuel-git** [comment]
Hi Knuffo,

I would recommend to ask your favorite glieder pilots to connect their glider permanently and then befriend them.
This way others can easily follow them as well.
As a bonus you get all their uploaded flights in your feed.

Happy watching
Samuel
