### ISSUE TITLE
Adding a YouTube URL to a flight sometimes fails

### ISSUE THREAD

**Issue by benhirashima** [weglide/bugtracker#251]
**Describe the bug**
First, thank you for adding the ability to put YouTube links on our flights! I was able to successfully add one to my [last flight](https://www.weglide.org/flight/324219): . However, when I tried to add YouTube links to my other flights, it didn't work. 

**To Reproduce**
1. Go to [this flight](https://www.weglide.org/flight/310945)
2. Click on Add Video button, at the bottom
3. Enter the YouTube URL in the YouTube text box
4. Click Save button, at the bottom
5. YouTube text box disappears, Success: Saved Flight appears in the top right corner, and no video appears under Story.
6. Shift-reloading page shows no video
7. Tried on Firefox and Safari on MacOS

**Expected behavior**
YouTube thumbnail and UI should appear under Story

**Screenshots**
<img width="414" alt="image" src="https://github.com/weglide/bugtracker/assets/1156502/3f8d5151-58f4-4cb2-95be-2fd925c1a188">

<img width="1444" alt="image" src="https://github.com/weglide/bugtracker/assets/1156502/2cf09fbf-da15-49f9-ba43-eee009986acd">

**Device (please complete the following information):**
 - Device: MacBook 
 - OS: MacOS Ventura
 - Browser Firefox and Safari

**Comment by flyingjoe** [comment]
We'll look into it 👍
