### ISSUE TITLE
Embed website widget not loading in chrome

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#252]
**Describe the bug**
The Embed website widget is not loading in google chrome.
I then tested with safari, firefox, edge - these are working fine.

**To Reproduce**
1. Open Google Chrome
2. Go to https://haec.de (or any of these websites https://docs.weglide.org/how_to/embed.html#examples)
3. Scroll down to "Segelflug"
4. See, that Embed weglide widget is missing

**Screenshots**
Left: Chrome, right: Firefox
![image](https://github.com/weglide/bugtracker/assets/47079209/afa9ead8-2415-4fa3-9501-fcb99c808717)
****

**Device:**
 - Device: PC
 - OS: Windows 10
 - Browser: chrome 116.0.5845.187

**Comment by samuel-git** [comment]
Most likely an adblocker issue. Can you try a private tab with adblocker disabled?
Some adblockers heavily block javascript in iFrames.

**Comment by frantzheld** [comment]
I encountered the same issue while using a private Chrome tab with extensions disabled.
To further investigate the issue, I conducted additional tests using different browsers on various operating systems:
### macos:
- chrome ❌ (privat tab without extentions)  
- safari ✔️ 

### android:
- chrome ❌
- firefox ✔️ 

### windows:
- chrome ❌ (privat tab without extentions) 
- firefox ✔️ 
- edge ✔️ 
- opera portable ✔️ 

## Problem solved!

After conducting a test with Chrome Portable, where I wasn't logged in with my Google account, I was pleasantly surprised to find that it worked flawlessly ✔️
This led me to the conclusion that the issue must have resided within my Chrome settings. I successfully resolved the problem by disabling the "**Block third-party cookies**" option:
![image](https://github.com/weglide/bugtracker/assets/47079209/80d151c3-7b6d-467b-9652-0b5e75b758c3)

**Comment by samuel-git** [comment]
Ah perfect, thanks for the effort!
Weird how chrome treats some local storage entries (language & log in info) in an iframe as "third party cookies".
