### ISSUE TITLE
Arfield "Măgura, Cisnădie" displayed as "Baia Mare Tautii"

### ISSUE THREAD

**Issue by vacaretutudor** [weglide/bugtracker#254]
**Describe the bug**
Airfield "Măgura, Cisnădie" is displayed as "Baia Mare Tautii". That is not correct. 

"Baia Mare Tautii" is an airfield North West of the Country and next to Maramureș International Airport ([IATA](https://en.wikipedia.org/wiki/IATA_airport_code): BAY, [ICAO](https://en.wikipedia.org/wiki/ICAO_airport_code): LRBM)
See location for "Baia Mare Tautii":  - https://maps.app.goo.gl/e452J5zEvmpQWKwc7 - https://aeroclubulromaniei.ro/page/aerodrom-baia-mare
Coordinates for "Baia Mare Tautii": Latitude: 47.658909, Longitude: 23.478039 
ICAO: LRMM

"Măgura, Cisnădie" is an airfield South East of Sibiu. At this moment the airfield is displayed on WeGlide as "Baia Mare Tautii" which is wrong. See attached screenshot. 
Coordinates for "Măgura, Cisnădie": Latitude: 45°44'21"N (45.739167) Longitude: 24°09'50"E (24.163889) 
ICAO: LRCD.

**To Reproduce**
1. Go to 'https://www.weglide.org/airport/1360125'
2. See error
![Screenshot 2023-09-15 at 13 40 50](https://github.com/weglide/bugtracker/assets/6464247/e6d13324-f827-4d5b-822a-d71b7348e000)

**Comment by samuel-git** [comment]
Please correct the airfield at https://www.openaip.net/.

**Comment by vacaretutudor** [comment]
I had a quick look on OpenAIP and the airfields are correctly displayed there. Or am i missing something? See below:
<img width="1439" alt="Screenshot 2023-10-08 at 22 58 34" src="https://github.com/weglide/bugtracker/assets/6464247/326b5ae2-e4aa-44eb-97f0-6072fe783053">
<img width="1073" alt="Screenshot 2023-10-08 at 22 59 28" src="https://github.com/weglide/bugtracker/assets/6464247/6edf1c30-b165-4124-b957-9fb211ee4cf2">
