### ISSUE TITLE
Junior Promotion / WeCoach docs page only in German

### ISSUE THREAD

**Issue by piotr-lasota** [weglide/bugtracker#256]
**Describe the bug**
WeCoach section of the docs (https://docs.weglide.org/programs/wecoach.html) is available only in German.

**To Reproduce**
1. Go to `https://docs.weglide.org`
2. Select display language: `English`
3. Select article on [`Junior Promotion, WeCoach`](https://docs.weglide.org/programs/wecoach.html)

**Expected behavior**
Article is displayed in it's English translation version

**Actual behavior**
Article is in German. Cycling through languages in the Language dropdown yields the following result:
- For German language it's displayed in German
- For English language it's displayed in German
- For French language it's not found (redirect to 404 page)

**Screenshots**
n/a

**Device (please complete the following information):**
 - Device: Laptop
 - OS: Ubuntu
 - Browser: Firefox

**Comment by samuel-git** [comment]
Hi @piotr-lasota,
this is because only juniors from the german free ranking can apply.
