### ISSUE TITLE
Missing arrows in Range Filter

### ISSUE THREAD

**Issue by jB1d3n** [weglide/bugtracker#258]
In the 'Range' filter the month before the previous month cannot directly be selected. Instead, it is only possible to jump to the same month of the previous year by selecting 'earlier'.

1. Go to 'flights'
2. Click on 'Range'
3. Click on 'earlier' (only option to scroll to the previous month)

**Expected behavior**
It shall be possible to directly scroll to the previous month (by arrows) without going one year back

**Screenshots**
![image](https://github.com/weglide/bugtracker/assets/148797017/2d60a9e6-6fbd-46ce-908e-ca33d53c8e85)

**Device (please complete the following information):**
 - Device: Surface 3 Pro
 - OS: Windows
 - Browser: Chrome

**Comment by samuel-git** [comment]
Hi [jB1d3n](https://github.com/jB1d3n),
this is expected as there is always a whole season shown and the season starts on October.
I agree it looks a bit strange.

**Comment by jB1d3n** [comment]
Thanks for the reply.

In that case I'd like to mention that it's quite uncomfortable to select ranges across the season start/end. E.g. selecting 25.09. - 05.10. requires ~10 clicks
