### ISSUE TITLE
Aerodrome info panel does not open a second time

### ISSUE THREAD

**Issue by vihai** [weglide/bugtracker#259]
Hello,

I open the map showing one of my flights, then I click on an aerodrome. The information panel is opened on the left. I close the aerodrome information panel, the flight information panel is shown. All the aerodrome placeholders are not clickable anymore.

Firefox 119.0 on Ubuntu Linux

Thanks

**Comment by samuel-git** [comment]
Thank you, this is fixed with the next update.
