### ISSUE TITLE
Separate input for empty weight, pilot weight and water ballast

### ISSUE THREAD

**Issue by neckmann** [weglide/bugtracker#260]
**Describe the Feature**
Within the "Coach" function, specifically the weight analysis, no lower limit is used for the analysis.

For example: 
Weight 260 kg
Pilot weight 95 kg
_Total 355 kg_

The recommendation from the analysis of the flight https://www.weglide.org/flight/49131 is 300 kg and would therefore require the pilot to lose 45kg of body weight

**Comment by samuel-git** [comment]
Hi @neckmann 
You are right but we want to limit the fields the user has to enter and the pilot weight might be somewhat private information. We set the default minimal body weight we assume from 50kg to 70kg in the hope this works better as a default.
