### ISSUE TITLE
Announcement of changes or new features

### ISSUE THREAD

**Issue by deltafox44** [weglide/bugtracker#261]
Thanks to WeGlide team there are regularly new features or improvements implemented. Sometimes there are difficult to notice. For instance, tasks that have been declared can now be copied for editing, there is a "copy button" since last June but I never saw it before reading this solved issue - see https://github.com/weglide/bugtracker/issues/233. 

Also there has been a change in the flight page (green/red dots for the status of flight/task), this one cannot be missed but it takes some time to notice what exactly is the extent of the changes and their implication.

Of course major new features are announced in WeGlide Magazine, but for more technical items it would be good that every significant change be announced in a few words here, especially when it solves existing issues (perhaps it is already the case but I missed it). There could be a special issue here to follow the changes (or a mailing list).

**Comment by deltafox44** [comment]
opened twice

**Comment by samuel-git** [comment]
Hi @deltafox44,
while I agree that this would be wonderful to have for the community, someone needs to take the time to write a concise changelog in non-technical terms. We decided that at the current speed of development, the time is better used fixing bugs and supporting the users via email. This can - and hopfully will - change in the future.

**Comment by deltafox44** [comment]
you're right ;-)
