### ISSUE TITLE
Comments stay the same for all flights in a list

### ISSUE THREAD

**Issue by deltafox44** [weglide/bugtracker#263]
**Describe the bug**
Comments stay the same for all flights in a list when switching one from another with the arrows

**To Reproduce**
1. Go to https://www.weglide.org/flight
2. Click on 'show' for any flight of the list with a comment
3. Switch to the next or the preceding flight using the arrows on the top, one or several times
4. See error : the comment remain the same
5. reloading shows the real comment of the flight but the ability to navigate in the list through the arrows is lost 

If the flight in the step 2 has no comment, other flights will never show their comments either

**Expected behavior**
The comment should correspond to the flight

**Screenshots**
![image](https://github.com/weglide/bugtracker/assets/82087770/c67e538f-102e-4f68-a8a1-063c0b55104c)
![image](https://github.com/weglide/bugtracker/assets/82087770/7bf791ce-b11e-4d92-a9e3-9c16f16d4a66)
![image](https://github.com/weglide/bugtracker/assets/82087770/617f8301-9587-4f31-8f09-16b80eb56bd0)

**Device (please complete the following information):**
 - Device: MacBookAir or iPhone8
 - OS: macOS10.14.6, iOS16.7.2
 - Browser : Chrome, Safari

**Comment by samuel-git** [comment]
Thanks, this one slipped trough. It is fixed now.
