### ISSUE TITLE
Broken Link in "Approved Loggers" documentation page

### ISSUE THREAD

**Issue by E2nO** [weglide/bugtracker#264]
On Page & Section https://docs.weglide.org/contests/loggers.html#how-can-i-check-files-myself

the link to http://www.ukiws.uk/GFAC/downloads.htm ("This page" in Step No 2) does not exist - you will end up on a web page, offering the domain for purchase, and not on a webpage, where you could possibly find that "correct DLL" file.

I guess, you will have to rewrite this section in case that the DLL files that should have been linked cannot be found elsewhere on the Net.

Cheers, Enno.

**Comment by moldhouse** [comment]
Thanks for reporting, the link is now removed.
