### ISSUE TITLE
Task rejected with no reason

### ISSUE THREAD

**Issue by VH-TND** [weglide/bugtracker#266]
**Describe the bug**
This flight https://www.weglide.org/flight/348802 appears to successfully complete the task, but is marked red. No reason is given for the rejection in the info box.

**Device (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Browser: Chrome

**Comment by samuel-git** [comment]
@VH-TND thanks for reporting, we are looking into it.

**Comment by moldhouse** [comment]
It seems like the start was manually adjusted to be just when the start line was crossed. I set it to one minute before, and now the task is scored properly.

![Image](https://github.com/weglide/bugtracker/assets/24278651/d557a999-0d4a-447b-8041-ad4c15d66733)

**Comment by VH-TND** [comment]
Thanks, Moritz, I appreciate your efforts.

Regards
Niall
________________________________
