### ISSUE TITLE
Terrain on barogram is wrongly rendered

### ISSUE THREAD

**Issue by vacaretutudor** [weglide/bugtracker#268]
**Describe the bug**
Terrain on barogram not displayed properly in Chrome Canary.

**To Reproduce**
1. Go to www.weglide.org.
2. Click on any flight.
3. Scroll down to barogram of flight.
4. See error: Terrain on barogram is wrongly rendered.

**Expected behavior**
Terrain on barogram is displayed/rendered properly.

**Screenshots**
![Screenshot 2024-01-17 at 16 06 07](https://github.com/weglide/bugtracker/assets/6464247/867c26ba-7e82-472b-b600-57a0a6d4413c)
![Screenshot 2024-01-17 at 16 07 00](https://github.com/weglide/bugtracker/assets/6464247/b6f36676-3fc5-4c25-a91d-e2aa5f868a66)

**Device (please complete the following information):**
 - Device: MacBook Pro
 - OS: macOS Ventura 13.6.3
 - Browser :
Google Chrome
Chrome is up to date
Version 122.0.6253.0 (Official Build) canary (x86_64)

**Comment by vacaretutudor** [comment]
Not sure if this is reproducible in Google Chrome Stable and might be a glitch/bug in Canary, please discard if irrelevant.

**Comment by samuel-git** [comment]
Thanks @vacaretutudor 
Tried to reproduce on stable chrome with your hardware and everything seems fine. Must be an error in the canary build with svg canvas drawings.
<img width="957" alt="grafik" src="https://github.com/weglide/bugtracker/assets/22152728/0bb37986-66d2-4050-9f84-63bed260d332">
