### ISSUE TITLE
wight in coach

### ISSUE THREAD

**Issue by hag3fe** [weglide/bugtracker#269]
You have to enter the wight of the glider. 

If I'm too heavy, the recommendation is to reduce wight

If I did not load any water, it is impossible to reduce the wight (unless I do not stop eating)

Browser: firefox

Suggestion: separate empty wight of the glider and payload of pilot and water.

**Comment by samuel-git** [comment]
Hi @hag3fe,
thank you for the feedback. We considered it but came to the conclusion that this will be too much overhead when uploading the flight. In the end some gliders will always have a different empty weight than others.
Best is to ignore the weight recommendation in this case.
