### ISSUE TITLE
Front page listing invalid top flights

### ISSUE THREAD

**Issue by flyingjoe** [weglide/bugtracker#27]
**Describe the bug**
The front page is listing invalid igc files as the top flights of the day. These should be ignored.

**To Reproduce**
1. Do a big flight in condor
2. Upload to weglide
3. Enjoy your first place

**Expected behavior**
Invalid flights should be ignored

**Device (please complete the following information):**
 - Any

**Comment by samuel-git** [comment]
Going to be fixed in next release.
