### ISSUE TITLE
Statistics on tasks

### ISSUE THREAD

**Issue by fmg12** [weglide/bugtracker#271]
Statistics are currently available only for 'Free', 'Sprint', 'Triangle' and 'O&R'. But when analysing competition flights, in particular, it would be very helpful to get statistics for a given task as well. It would be very natural and helpful to offer this. 

In fact, I was convinced it must be there. I looked everywhere, but I just can't find it. It seems so obvious that you ought to be able to get statistics on a task (whether pre-declared or added afterwards). If it's already possible, and I'm missing it, please make it more obvious. If not, please consider adding this feature.

**Comment by samuel-git** [comment]
Hi @fmg12,

statistics are only calculated for declared and successfully completed tasks.
They can be found unter "Statistics" --> "Task" tab on these flights (e.g. https://www.weglide.org/flight/361386).
If the flight is scored for a national competition, the statistics are calculated for the national competition instead (taking the task declaration into account). The tab is then called "IRC", "DMSt" etc.

Do I understand you correctly that you are looking for statistics of flights for arbitrary tasks which are not declared?

**Comment by fmg12** [comment]
Dear Samuel,

thanks for taking this up. Yes, because sometimes tasks are only assigned after the flight. This happens in particular in competitions, when someone goes to the trouble of putting in a task for us using the ‘local competitions’ option, even if the participants didn’t declare anything. Now, after the flights are in, it would be nice to see your performance analysed within the parameters of that task. Usually, such flights involve a long wait at the start line, so the ‘free flight’ analysis is very misleading. See e.g. this flight of mine last year:
https://www.weglide.org/flight/302436

Weglide already sees the task and works out when I started on it, but it does not calculate the statistics based on this task.

With kind regards - Malte
￼

**Comment by deltafox44** [comment]
> statistics are only calculated for declared and successfully completed tasks. 

An useful enhancement would be to have statistics calculated also for declared but **non-completed tasks**. Even if non-completed tasks give no points in WeGlide, the statistics would be interesting to understand one's errors while sitting in the field expecting for retrieve ;-)

Not directly related to this issue, when "Points" awarded for a complete task are higher than points for free distance flown, these points should be taken into account in the list of flight (for ranking), not the "free" points. And, when clicking on such a flight, it should open directly on the "Task" tab
