### ISSUE TITLE
wrong glidertype and ID in Weglide Flight after uploading IGC-File

### ISSUE THREAD

**Issue by Ventusfahrer** [weglide/bugtracker#276]
**Describe the bug**
flight https://www.weglide.org/flight/377272
The IGC-File I uploaded lists the Glider-ID with D-7174, type Ventus 2b, the flight downloaded lists the same information.
Weglide listed the glidertype as Janus C, registration: PH-1506. I have never seen/used this glider and therefore astonished how it find the way to my Weglide Flight Declaration.

**To Reproduce**
In order to reproduce the problem I would have to delete the flight in Weglide in order to get it uploaded again...
So I won't try to reproduce it.

**Expected behavior**
no change or manual change during flight declaration.

**Screenshots**
not necessary, see flight and IGC-File linked in the flight

**Device (please complete the following information):**
 - Device: Notebook
 - OS: Linux Manjaro
 - chrome (original, not chomium-browser)

**Comment by samuel-git** [comment]
Hi  @Ventusfahrer 
We are preselecting the aircraft associated last with this logger for you.
You can change the aircraft on upload https://docs.weglide.org/how_to/edit_flight.html#glider-name if the preselection is wrong.
Our system remembers the aircraft set and will show the correct aircraft the second time you upload a flight.

Please reach out to info@weglide.org if you want any changes made to existing flights out of the edit period.
Sam
