### ISSUE TITLE
Club search doesn't show any results

### ISSUE THREAD

**Issue by ctriebstein** [weglide/bugtracker#277]
I just registered to WeGlide and wanted to update my profile to save the club I'm flying with. I can save my profile after entering the club but it doesn't persist the club itself. Every other change seems to be saved. When checking the network traffic I saw that the endpoint https://api.weglide.org/v1/search never returns any result. I've tried several different clubs (that definitely exist) and the result was always the same. 

Tested on Chrome, Firefox, Edge in Desktop and Mobile versions.

As a side note: I noticed that with every keystroke in the "club" field a search is executed. This might have a performance impact and should be avoided. Could be fixed by searching after a set timeout for keystrokes.

<img width="1470" alt="profile" src="https://github.com/weglide/bugtracker/assets/5031323/3d309e56-f718-444a-bae1-aa5420263df2">

**Comment by samuel-git** [comment]
Hi @ctriebstein thanks for the report.
The search should work, this was only a temporary outage. 
We are working on the robustness of the API at the moment.
Sam
