### ISSUE TITLE
Coach shows very low (wrong) average gliding speed

### ISSUE THREAD

**Issue by JohnCJ2** [weglide/bugtracker#282]
The coach function shows consistently very low average IAS for my glide segments.  The graph, however, shows an unlabeled speed value for each segment that seems to match my calculations.  

**To Reproduce**
1. Use my flight on May 11, 2024 (John Johnson, Tucson Soaring Club)
2. Look at the gliding segment 21:30:51 - 21:42:43 (~12min duration, 20nm distance)
3. See that the graph shows 102kn (unlabeled) and simple calculations yield ~100kn (distance/time)
4. See that the coach function says the average speed was only 69kn: _You were flying the glide phase from 21:30 to 21:42 with an average indicated airspeed of 69 kn. Based on an average MacCready of 559 fpm and the net air mass movement of 7 fpm, the optimal glide speed is 95 kn according to MacCready theory. Try to fly faster between thermals._
5. See similar discrepancies in other glide segments.

**Expected behavior**
A reply with an explanation of my confusion or a response to correct this if it is a bug.

**Screenshots**
Attached
![JJohnson glide speed error 5-11-2024](https://github.com/weglide/bugtracker/assets/169620414/3b375c6f-c4a7-47f2-aec3-bb196855b747)

**Device (please complete the following information):**
 - Device: PC
 - OS: Windows 11
 - Chrome

**Comment by morhall** [comment]
Not someone from WeGlide, but saw this and read through your report.  Keep in mind that the speed shown on the graph is Groundspeed.  At 10-13k you're also going to see true airspeeds that are ~20% higher (2%/1000ft) than your indicated.  So TAS + a tailwind could put you at 100kts over the ground with 70ish kts indicated.  Not knowing what your winds were, their number seems a bit low, but not completely out of the realm of possibility.  

I have felt like the numbers were generally a bit low as well, but the data probably tells a better story than my memory.

**Comment by JohnCJ2** [comment]
Great feedback, Morgan.  Thank you!
I think you're right about weglide (and reality) in terms of using a pure
MC calculation.  I definitely need to unlearn my hang gliding 'turn in
every thermal and top them out' past.
thx, JJ

**Comment by morhall** [comment]
Classic HG moves. I too came from HG and had to unlearn take em all, top em
all.

**Comment by samuel-git** [comment]
The discrepancy can be explained by the windvane in the bottom right corner indicating a 16kn tailwind and the difference between ground and airspeed pointed out by @morhall.
The wind is an approximaten derived from your circling offsets.
In real live scenarios we often see people flying "too slow" because they can not take the full risks in all scenarios and are cautious. But we found that the best pilots consistently hit the green areas of the coach.
