### ISSUE TITLE
Copilot - Rain radar / Live tracking buttons on/off contrast

### ISSUE THREAD

**Issue by DanD222** [weglide/bugtracker#288]
**Describe the bug**
At present, the icons of the "Rain rada"r on/off and the "Live tracking" on/off button indicate whether the feature is enabled or disabled by changing the colour of the graphic from black to blue. 

It is hard to differentiate between the two states at present, so I think a more contrasting method would be better suited to indicate whether the features are turned on or off (e.g. fill the buttons with a colour, like the "Center" button, or add an outline to the button, like the "updated time" infobox).

Rain radar off:
![radar_off](https://github.com/weglide/bugtracker/assets/48011765/278a7907-313a-48cf-9a15-8688eb25e92a)

Rain radar on:
![radar_on](https://github.com/weglide/bugtracker/assets/48011765/f01db4ea-a599-4c6e-99b0-d05e3815cc73)

**Comment by deltafox44** [comment]
+1
The same applies to the Live tracking On/Off button.
Better fill the button entirely (like Center) since the outline is barely visible, especially the outline color as said in https://github.com/weglide/bugtracker/issues/286
