### ISSUE TITLE
filter out manipulated gliders/trackers from livetracking

### ISSUE THREAD

**Issue by CarstenSon** [weglide/bugtracker#289]
**Describe the bug**
Sometimes some gliders show up that either have unrealistic altitudes/speeds and/or unrealistic average speeds for the setup glider and for the fun of checking the live tracking it would be cool to filter out those - especially the first ones mentioned since i'm aware you can't do that much against people providing wrong glider types in OGN DDB..

**To Reproduce**
wait for a good day
check live tracking
wonder about a std. cirrus in 32.000 m MSL or one with an average speed of 215kph in central europa at 11:40 CEST

**Expected behavior**
those most likely manipulated flights/data should be filtered out

**Screenshots**
![image](https://github.com/weglide/bugtracker/assets/21118388/c35006ea-cc41-4e40-84ae-906e65617ca5)

**Device (please complete the following information):**
 - Device: any
 - OS: any
 - Browser any

**Comment by samuel-git** [comment]
Hi @CarstenSon,
we do some filtering of unrealistic aircraft behaviour. We need to improve that instead of making the UI more complex.

Thanks for pointing this out!
