### ISSUE TITLE
Cambride 302 IGC file is not validated correctly

### ISSUE THREAD

**Issue by Ventusfahrer** [weglide/bugtracker#29]
**Describe the bug**
In Weglide flight  https://beta.weglide.org/flights/4044 validates as "Datei vorläufig ungültig"

**Expected behavior**
possitive validation of the flight, as https://www.onlinecontest.org/olc-3.0/gliding/flightinfo.html?dsId=8238703 - same file - does.

Maybe your are using http://vali.fai-civl.org/webservice.html webservice validation? 
This side is not able to handle cambridge devices:

**Analisis**
```
/usr/bin/curl -F igcfile=@2020-08-16-CAM-3LG-01.igc vali.fai-civl.org/api/vali/json
{"result":"ERROR","status":"ERR_UNSUPPORTED","msg":"IGC program not supported - CAM","igc":"2020-08-16-CAM-3LG-01.igc","ref":"","server":"Open Validation Server 3.03"}

```
even though the device is supported and approved by IGC:
https://www.fai.org/sites/default/files/igc-approval_-_cambridge_302_-_2020-5-20.pdf

When downloading the IGC-validation rules for the 302, the file validates false for vali-cam.exe (should not be used) and true for VALICAM2.EXE (which should be used according above document). Location of the [validation programs](http://www.ukiws.uk/GFAC/downloads.htm) 

kind regards

Peter Simon

**Comment by flyingjoe** [comment]
Hi Peter :)
Thanks for opening an issue about this. 
As stated in #6 our file validation is still work in progress and therefore doesn't validate some files.
We will support all IGC-approved flight recorders.
There will hopefully be an update on this in the coming days.

**Comment by Ventusfahrer** [comment]
maybe it would be a good idea to Create a Link on the status label if it's value is "file interim invalid" or "file interim valid" and put all other information to this point.

**Comment by flyingjoe** [comment]
@samuel-git We should add a link to https://docs.weglide.org/docs/contests/loggers/

**Comment by samuel-git** [comment]
Ships in next release
