### ISSUE TITLE
Altitude difference too large when closing the task

### ISSUE THREAD

**Issue by mookymook** [weglide/bugtracker#290]
**Describe the bug**
A get an error on my task "Altitude difference too large when closing the task" but the fly seems to be ok...
Can you explain me if it is not bug ?

**To Reproduce**
1. Go to https://www.weglide.org/flight/423366
2. Click on Task

**Expected behavior**
Getting a valid task

**Screenshots**
![image](https://github.com/weglide/bugtracker/assets/2605637/b5d587f2-3226-407c-91d6-a3e3cc797bae)
![image](https://github.com/weglide/bugtracker/assets/2605637/962b5ac3-30c8-4e43-b114-19d29cac9703)

**Device (please complete the following information):**
 - Device: Google Pixel 8 Pro
 - OS: Windows 11
 - Browser : Chrome

**Comment by samuel-git** [comment]
Hi @mookymook,

the max altitude is 1000m for all national competitions. This is why the message is (incorrectly because you did not fly a national competition) shown to you.
Otherwise the task is o.k. Congrats for your flight.
