### ISSUE TITLE
dead or empty link on "status of flight"

### ISSUE THREAD

**Issue by Ventusfahrer** [weglide/bugtracker#30]
see attached video.

when moving the cursor over the label **Flug gültig** it looks like there is a link defined on the label.

But when clicking on the link/label nothing happened.

https://user-images.githubusercontent.com/5901190/103281769-09b9d480-49d4-11eb-8ed5-604395db40e5.mp4

**Comment by samuel-git** [comment]
Thanks, fixed in next release.
