### ISSUE TITLE
UI reacts strange after upload of Task

### ISSUE THREAD

**Issue by dspreitz** [weglide/bugtracker#31]
I tried to upload a task and the UI behavior was unexpected.
Steps to reproduce.
1. go to http://https://beta.weglide.org
2. Klick auf Aufgabe
3. Klick auf 'Neue Aufgabe'
4. Doppelklick in File Upload Feld
5. Datei auswählen & Öffnen
6. CUP Datei wird zwar von weglide verarbeitet, aber der Dialog um Aufgabennamen und Beschreibung zu bearbeiten verschwindet.

Work around:
Schritte 1-5 durchführen, dann
1. Klicke auf Aufgabe
2. Klicke auf Meine Aufgaben
3. Klicke auf Hochgeladene Aufgaben
4. Editieren.

**Comment by samuel-git** [comment]
Hi dspreitz,

this is a upload **or** create by changing forms scenario (thats why the forms disappear when uploading).
But I guess this needs to be separated.

Keep up the good bugreports!

**Comment by samuel-git** [comment]
User flow is clear in next version.
