### ISSUE TITLE
Filter tasks by ICAO codes of Airfields

### ISSUE THREAD

**Issue by dspreitz** [weglide/bugtracker#32]
**Describe the bug**
Wenn man im Aufgabendialog ICAO-Kenner von Flugplätzen eingibt erhält man keine Suchergebnisse.

**To Reproduce**
1. Kicke auf Aufgabe
2. Klicke ins Such Feld
3. Geb einen ICAO Flugplatzcode ein (z.B. EDNC)
4. Suche liefert keine Ergebnisse
5. Geb 'Beilngries' ins Suchfeld ein und Du erhälst Ergebnisse

**Expected behavior**
Es wäre sehr gut, wenn die Suche nach ICAO Flugplatzkenner zu den gleichen Ergebnissen wie die Suche nach dem kompletten Flugplatznamen führen würde.

**Comment by samuel-git** [comment]
#80
