### ISSUE TITLE
Aufgabensuche berücksichtigt nicht Aufgabentitel

### ISSUE THREAD

**Issue by dspreitz** [weglide/bugtracker#33]
**Describe the bug**
Der Aufgabensuchdialog scheint nur Wendepunktnamen zu kennen und reagiert nicht auf Wörter, welche im Aufgabentitel angegeben werden.

**Expected behavior**
Es wäre gut, wenn die Aufgabensuche auch die Wörter des Titels der Aufgabe als Ergebnisse zurück liefern könnte.

**Comment by samuel-git** [comment]
![image](https://user-images.githubusercontent.com/22152728/103305344-31785f00-4a0b-11eb-858a-8718ca9f60ba.png)

Scheint bei mir zu funktionieren. Wahrscheinlich hat die Aufgabe die du suchst keinen Titel (das ist bei der erstellung noch etwas verwirrend.) oder die Aufgabe ist auf privat gestellt. Sie sollte aber unter deinen Aufgaben zu finden sein wenn sie von dir ist.

Der Aufgabenplaner bekommt in der nächsten Zeit noch viel Zuwendung.

**Comment by dspreitz** [comment]
Merkwürdig, bei mir funktioniert genau das leider nicht. Wenn ich nach EDNC suche, bekomme ich keine Suchergebnisse angezeigt, obwohl ich eigentlich entsprechende Aufgaben hinterlegt habe. Siehe Bilder.
![Screen Shot 2020-12-29 at 21 15 54 (2)](https://user-images.githubusercontent.com/1283730/103314264-d8b4c080-4a22-11eb-948f-607230650647.png)
![Screen Shot 2020-12-29 at 15 31 49](https://user-images.githubusercontent.com/1283730/103314271-dc484780-4a22-11eb-8b64-1005c37164a0.png)

**Comment by samuel-git** [comment]
@dspreitz Tatsache, wir sind dran. Danke!
