### ISSUE TITLE
Two clicks on back button needed to return to profile page after clicking on "Flights as list"

### ISSUE THREAD

**Issue by AeroLuk** [weglide/bugtracker#34]
**Describe the bug**
When selecting "Flights as list" from profile page two clicks on browser back button are needed to return to the profil page. The first click has no visible effect apart from changing the url.

**To Reproduce**
1. Go to 'Profile'
2. Click on 'Flights as list'
3. Click on back button in browser
4. Click a second time on back button in browser

I noticed that this isn't always reproducable. Sometimes one click is enough. But I could reproduce it always when opening the profile page by url in a new browser window with privacy mode enabled. But it appears on a normal workflow too.

**Actual behavior**
3. Page doesn't change. But url changes from
`https://beta.weglide.org/flights?filter=[{%22index%22:%22user%22,%22name%22:%22XXX%22,%22id%22:XXX},{%22index%22:%22order_by%22,%22name%22:%22-scoring_date%22}]`
to
`https://beta.weglide.org/flights?filter=[{%22index%22:%22order_by%22,%22name%22:%22-scoring_date%22},{%22index%22:%22user%22,%22name%22:%22XXX%22,%22id%22:XXX}]`
**NOK**
4. Profile page is shown again **OK**

**Expected behavior**
3. Profile page is shown on first click. No second click needed.

**Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Browser: Firefox 84.0.1

**Comment by samuel-git** [comment]
Thanks for the detailed bug report. This was something bugging me for quiet some time. Just fixed it by replacing router history instead of adding when switching filters. Comes with next release.
