### ISSUE TITLE
Filters do not reset when visiting ranking

### ISSUE THREAD

**Issue by moldhouse** [weglide/bugtracker#35]
**Describe the bug**
Previously set filters are not removed on the ranking page.

**To Reproduce**
1. Go to the flight list
2. Apply a filter, e.g. a user
3. Go to ranking
4. Filter is still visible

**Expected behavior**
I expect the list filter to be removed when visiting the ranking

**Screenshots**
<img width="397" alt="image" src="https://user-images.githubusercontent.com/24278651/103291377-db47f380-49eb-11eb-8903-4b2c493bdb74.png">

**Device (please complete the following information):**
 - OS: Mac OS
 - Browser: Firefox

**Comment by samuel-git** [comment]
fixed in next release.
