### ISSUE TITLE
Set/Change home airport manually in Profile settings

### ISSUE THREAD

**Issue by AeroLuk** [weglide/bugtracker#36]
**Describe the bug**
As far as i could tell the home airport is automatically selected based on the flights uploaded by the user.
This selection could be wrong (f.e. in my case) or could change when moving to a different airport.
It should be possible to change the home airport manually in the profile settings linke the club.

**To Reproduce**
1. Go to 'Profile'
2. Go to 'Profile settings'

**Actual behaviour**
1. In 'Statistics' a home airport is shown which could be wrong
2. No option to change/set home airport manually.

**Expected behaviour**
2. Option to set home airport manually (like setting the club).

**Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Browser: Firefox 84

**Comment by samuel-git** [comment]
#80
