### ISSUE TITLE
Previous selected flight is still shown on 'airport map'

### ISSUE THREAD

**Issue by AeroLuk** [weglide/bugtracker#37]
**Describe the bug**
A previous selected flight is still shown on map after selecting an airport.

**To Reproduce**
1. Go to 'Flights'
2. Click on 'show' in order to show a flight
3. Click on back button in browser or click on 'Flights' (left tabbar)
4. Click on an airport in flight list in order to show the airport on the map

**Actual behavior**
4. Flight selected in 3. is still shown on map although it has nothing to do with this user action.

**Expected behavior**
4. No flight is shown.

**Screenshots**
![Screenshot 2020-12-29 162241](https://user-images.githubusercontent.com/35994571/103294454-2b29b900-49f2-11eb-93db-8aafa77af0b1.png)

**Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Browser: Firefox 84.0.1

**Comment by samuel-git** [comment]
Thanks @AeroLuk I am working on it.

**Comment by samuel-git** [comment]
fixed in next release.
