### ISSUE TITLE
Header in ranking does not reset

### ISSUE THREAD

**Issue by moldhouse** [weglide/bugtracker#38]
**Describe the bug**
When switching between categories in ranking, sometimes the table header does not match the number of columns in the ranking

**To Reproduce**
1. Go to Ranking
2. Select on category
3. Select a different category

**Expected behavior**
I expect the table header to adjust

**Screenshots**
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/24278651/103300163-89f52f80-49fe-11eb-9608-baa54407fd6c.png">

**Device (please complete the following information):**
 - Device: MacBook
 - OS: Mac OS
 - Browser: Firefox

**Comment by moldhouse** [comment]
This seems to be a backend problem

**Comment by samuel-git** [comment]
@moldhouse the number of flights for the header is read from the config.json. If there is a mismatch between number of flights from api vs. config this happens afaik.

**Comment by samuel-git** [comment]
Fixed.
