### ISSUE TITLE
My club is missing

### ISSUE THREAD

**Issue by samuel-git** [weglide/bugtracker#4]
**Describe the bug**
I can not find my club in the selections.

**To Reproduce**
1. Go to 'Sign up'
2. Click on 'Select club'
3. Enter 'Non-existing Club'
4. No proposals / selectables

**Expected behavior**
The club should be proposed and selectable.

**Comment by samuel-git** [comment]
Open a pull request in [OpenClubList](https://github.com/weglide/OpenClubList) or contact info@weglide.org so we can create a pull request.

**Comment by niggli** [comment]
My club has two entries but the "OpenClubList" repo does not seem to exist (your above link leads to a 404).

**Comment by samuel-git** [comment]
Sorry @niggli, the repo is not (yet) open source. We will change it manually. Which club is affected? Thanks for your notice and have a wonderful evening.

**Comment by niggli** [comment]
The club is "SG Oberaargau" - thanks!

**Comment by samuel-git** [comment]
Interesting, your Club name is not unique as it matches the one in CH and another one in DE. We will display the country code alongside the name in the search results to let the user know which one to chose.

**Comment by niggli** [comment]
Displaying the country code is a good idea.

However my club is a strange issue. I googled the heck out of it but couldn't find a real German club with that name. Strangely, in OLC our club is shown in the [club statistics 2019 for Switzerland](https://www.onlinecontest.org/olc-3.0/gliding/clubRanking.html?st=olc&rt=olc&d-1987472-p=&paging=100000&sp=2019&c=CH&sc=) with all the flights but also in the [club statistic 2019 for Germany](https://www.onlinecontest.org/olc-3.0/gliding/clubRanking.html?st=olc&rt=olc&d-1987472-p=&paging=100000&sp=2019&c=DE&sc=) with only one single flight. The link to the club on both pages lead to the same "Club performance" page, so it's the same club.

Conclusion: The club really exists only once and this is some kind of artefact from the OLC club list.

**Comment by moldhouse** [comment]
I removed the German edition of 'SG Oberaargau' from OpenClubList as it did not seem to be a valid club.

**Comment by niggli** [comment]
The club "SG Oberaargau" has two entrys again.

![image](https://user-images.githubusercontent.com/529670/108704883-e65f6180-750c-11eb-96ff-17d969c9b2b5.png)

**Comment by Cedoo1** [comment]
The club "LV Reutlingen" has also two entries.
![image](https://user-images.githubusercontent.com/56065648/109717938-fcbd8b00-7ba6-11eb-89a0-7b38d1da854c.png)

**Comment by Cedoo1** [comment]
The club "LV Reutlingen" has also two entries.
![image](https://user-images.githubusercontent.com/56065648/109718076-2aa2cf80-7ba7-11eb-9e0c-09e7a1a35d23.png)

**Comment by samuel-git** [comment]
Thanks, Oberaargau is fixed and LV Reutlingen clubs are merged.

**Comment by borisbroere** [comment]
Hello,

The club "Eerste Zeeuws-vlaamse Aero Club" also has two entries:
![image](https://user-images.githubusercontent.com/82435256/114528027-e6482c00-9c48-11eb-972b-ddfbbd88ee0c.png)

**Comment by samuel-git** [comment]
@flyingjoe please take a look at this :-)

**Comment by flyingjoe** [comment]
@borisbroere Thanks, I removed the duplicate :)

**Comment by karenwilk** [comment]
Is it possible to merge the two version of LSC Bayer Leverkusen as well? Thanks!
![image](https://user-images.githubusercontent.com/83554482/116825225-9648ef00-ab8e-11eb-8715-da3999dd670b.png)

**Comment by frantzheld** [comment]
The icon of LSV Lüneburg is missing.
![image](https://user-images.githubusercontent.com/47079209/117808559-53a5a780-b25d-11eb-986b-62fa2141577d.png)

You can download it here:
https://edhg.de/wp-content/uploads/2020/11/LVL-VEKTOR.png

**Comment by samuel-git** [comment]
Everything added and fixed. Thanks

**Comment by deltafox44** [comment]
[AC Nogaro](https://www.weglide.org/club/595) and [Aéroclub du Bas Armagnac](https://www.weglide.org/club/595) are the same and its logo is
![image](https://user-images.githubusercontent.com/82087770/125189795-33cd3880-e23a-11eb-8dcf-c17c39677e50.jpeg)

More generally, what is the preferred form for the name of clubs ? In this case, the official name was "Aéroclub du Bas-Armagnac", in short "ACBA", but it has been changed 3 years ago to "[Aéroclub du Bas-Armagnac André Malibos](http://www.aeronogaro.com/)" and most people outside the town know it better as "AC Nogaro"

I think the more appropriate name would be "AC du Bas-Armagnac" or, if including the name of the airport, "ACBA Nogaro" (cf. [VVY La Roche sur Yon](https://www.weglide.org/club/1376) which officially is "Vol à voile Yonnais" but is in [La Roche-sur-Yon ](https://www.weglide.org/airport/150993)airport)

Also, there would be a need for some sort of redirection when searching (for instance searching "AC Nogaro" would find "AC du Bas-Armagnac"). It seems that after the entries have been merged the alternative can no longer be found (for instance [above](https://github.com/weglide/bugtracker/issues/4#issuecomment-818581625) "Eerste Zeeuws-vlaamse Aero Club" can no longer be found by its short form "EZAC"), and that could induce creating duplicate names again.

**Comment by ElenaSte** [comment]
The icon of FSV Unterjesingen is missing too.
Would it be possible to add it? 
You can download it here: https://www.fsv-unterjesingen.de/wp-content/uploads/2015/06/FSU-Logo-HQ.jpg
Thanks!

**Comment by samuel-git** [comment]
@deltafox44 We will merge the clubs under the name AC du Bas-Armagnac. Thanks for the logo! Redirects are sadly bot possible.

**Comment by samuel-git** [comment]
@ElenaSte thanks! We will add your club.

**Comment by Cedoo1** [comment]
Hello,
can you please change the logo of [LV Reutlingen](https://www.weglide.org/club/205) to the new one in the attachements?

![new_logo_blue_001](https://user-images.githubusercontent.com/56065648/129492920-8ecde354-eb57-4607-bac4-589a55bf15f6.png)

**Comment by moldhouse** [comment]
I have updated the logo, will take some time untill it is invalidated though.

**Comment by deltafox44** [comment]
> @deltafox44 We will merge the clubs under the name AC du Bas-Armagnac. Thanks for the logo! Redirects are sadly bot possible.

As I feared, AC Nogaro has been re-created since : https://www.weglide.org/club/726

It would definitely need some sort of link to avoid this kind of duplicate, so that the name of the aeroclub(s) based in a particular airport appears when searching by the name of the airport

Also, it would help if finding flights by filtering by name of take-off airport was allowed for any airport where there is at least one flight, not only a few of them - see https://github.com/weglide/bugtracker/issues/145

**Comment by brunotag** [comment]
Hi, change of name, and possibly icon

Wellington Gliding Club
https://www.weglide.org/club/1034

New Name:
Wellington Wairarapa Gliding Club

New Homepage:
https://www.wwgc.co.nz/

New Logo:
![131394272_3813618521981559_8007744088870076420_n](https://user-images.githubusercontent.com/1215492/150308372-cc672c34-06d8-4df6-a8e9-84145d93d6ba.jpg)

:-)

**Comment by moldhouse** [comment]
It is updated, might take some time to show on some of the sites because of caching.

**Comment by Cedoo1** [comment]
FG Pliezhausen is Part of the FSV Übersberg.

**Comment by moldhouse** [comment]
Please get in touch via mail and tell us which one of the two you want to have in the system.

**Comment by k-grosser** [comment]
Hi! AC Koblenz has also no logo, yet. Could you please add it?
SVG: [https://www.aeroclub-koblenz.de/img/logo.svg](https://www.aeroclub-koblenz.de/img/logo.svg)
PNG: 
![LogoACK](https://user-images.githubusercontent.com/43414739/177209555-3e4154f2-b950-4c61-8752-ab3fabe5bc3a.png)

Thanks!

**Comment by cerio1992** [comment]
hi, could you please add logo for Aeroclub Volovelistico Milanese? Many thanks.
and, how to add the pilots to the proper club? cause I set my club, but if I go to the club page it says 0 pilots... many thanks.

![AVM](https://user-images.githubusercontent.com/111052126/200934431-1f0bf2ef-aab7-442b-ba57-d7cc23d62273.png)

**Comment by samuel-git** [comment]
@k-grosser , @cerio1992 I will add the logos.
@cerio1992 I answered your question here: https://github.com/weglide/bugtracker/issues/208#issuecomment-1320842468

**Comment by Spaegi** [comment]
Hi
Could you add the following logo to SG Birrfeld?
![Logo SG Birrfeld](https://github.com/weglide/bugtracker/assets/135174130/97bf2605-080d-419d-91f4-5a16a977ec62)

Thanks and best regards

**Comment by lepehne** [comment]
Hi WeGlide Team,

could you add the logo to our club **LSV Bad Neuenahr-Ahrweiler** ?

Thank you

![LSV_Bad_Neuenahr_Logo](https://github.com/weglide/bugtracker/assets/30369205/56e0f7e3-8868-4551-aca5-746ec69cdeef)

**Comment by StefanSFG64** [comment]
Hello again, Logo still missing. Send 3 E-Mails....

![Bild1](https://github.com/weglide/bugtracker/assets/145422291/6d4b970d-b7cb-492d-8bba-5040d602887e)

**Comment by samuel-git** [comment]
Hey all,
Please send us missing logos per email to info@weglide.org and we will add them for you.
Closing this issue as one way to update logos is cleaner.
