### ISSUE TITLE
"Ghost" flight prevents re-uploading of a flight

### ISSUE THREAD

**Issue by CarstenSon** [weglide/bugtracker#41]
**Describe the bug**
I had uploaded a flight in the early stages that seemed to get stuck in the processing. The flight can't be found in my flight log and I can't just re-upload it because apparently there is another flight with the same hash value (or whatever you use for identifying flights) in the system and it is preventing the upload.

**To Reproduce**
1. Upload Flight
2. wait for analysis to get stuck (might take hours/years ;-))
3. flight not in flight log and re-upload of flight not possible

**Expected behavior**
If the analysis of a flight has not been done within a certain period of time, the user should be notified, if necessary, and the flight should be deleted or the possibility of processing it again should be provided.

**Screenshots**
not helpful for this problem

**Device (please complete the following information):**
 - Device: any

If needed I can send you the IGC file, just give me the desired email for it and let me know.

Whether this problem also occurs "in the wild" on later flight days I can hardly assess, but an interception of this problem should sufficiently take into account any imponderables.

**Comment by moldhouse** [comment]
Hey, thanks for reporting! I suspect the problem to be an internal server error on flight upload, where the file object has already been saved and the flight has not been. It might be that we have already fixed the internal problem, so if you sent me the file I can check if it parses and then delete the broken db record.

**Comment by CarstenSon** [comment]
just sent you an email 👍
