### ISSUE TITLE
Cookie flight upload/edit

### ISSUE THREAD

**Issue by August2111** [weglide/bugtracker#44]
**Describe the bug**
I tried to upload my first flight to WeGlide - and because all glider information was wrong I changed it completely - from ASG28 18m to LS4. But after the upload the old information was displayed, I couldn't find any changes... 

**To Reproduce**
1. Don't log in
2. Use user name and birth date to upload
3. change glider and click save
4. Get a "login again error"
5. look at flight and notice the glider didn't change

**Expected behavior**
I expect the right glider information in the flight info - and if they are wrong, I want to correct them, but I cannot find  some button to do this... A big problem for me is the wrong LogIn: WeGlide don't allowed me with my login data which I registered!  

**Screenshots**
--

**Device (please complete the following information):**
 - Device: Laptop HP OpenBook
 - OS: Windows
 - Browser: Firefox

**Comment by August2111** [comment]
** Reproduce: **
15 min later I did the same with a 5 minute flight (only a airfield circuit) - and the same wrong glider type is taken from IGC file, my changes have no effect!
The flight numbers are 5706 and 5716 in your database!

**Comment by flyingjoe** [comment]
These seem to be two independent issues. Could you send us an email to support@weglide.org for the account one? Thanks.
We'll have a look into the glider definition issue, thanks for reporting!

**Comment by moldhouse** [comment]
This is most probably related to the cookie method we use to edit flights after upload with date of birth. @samuel-git we need to revisit this.

**Comment by August2111** [comment]
From my point of view there are 3 independent issues:
- the 1st is the wrong glider definition, used the igc file one instead the user defined one during the upload in the edit fields.
- The second is the unpossibility to change this later on (or it is possible if I logged in))!
- And the 3rd is the problems with the log in - for this I will write an additional eMail to support!

**Comment by moldhouse** [comment]
Aircraft selection works if uploading while logged in. Therefore I think this is only one issue - missing authorization from cookie. You can change the aircraft later on if logged in.

**Comment by samuel-git** [comment]
Will be fixed in next release.
