### ISSUE TITLE
Mobile flight view didn't show the airport

### ISSUE THREAD

**Issue by glidingFisi** [weglide/bugtracker#45]
The mobile flight view didn't show the airport information.
This information is important to have a quick idea, where the flight happens.
Currently the club is presented, in my opinion the club field should be replaced with the airport field.
May be it is possible, to write the Club to the Name information: Name/Club

![image](https://user-images.githubusercontent.com/11047687/103380751-20eae600-4aea-11eb-9045-b2169068bd06.png)

**Comment by samuel-git** [comment]
Thanks @glidingFisi ,
will remove club information and instead show airport on mobile!
Coming with next release.
