### ISSUE TITLE
additional engine run during flight not detected

### ISSUE THREAD

**Issue by we730** [weglide/bugtracker#46]
Second engine run have not been detected in both files. 
Btw. OLC recognized both events.

https://beta.weglide.org/embedded/5678?baro=true&bbox=[15.72017,49.40377,11.86978,48.8392]
https://beta.weglide.org/embedded/5928?baro=true&bbox=[12.63978,49.13973,10.05142,48.74657]

OLC:
https://www.onlinecontest.org/olc-3.0/gliding/flightinfo.html?dsId=7746754
https://www.onlinecontest.org/olc-3.0/gliding/flightinfo.html?dsId=7917119

**Comment by moldhouse** [comment]
Thanks for reporting. Please select an aircraft with engine - then engine runs should be detected. Feel free to reopen the issue if that is not the case. @samuel-git this has happened quite a few times, maybe we need to make the user more aware?
