### ISSUE TITLE
LAK17 B FES not considered in Electric Scoreboard

### ISSUE THREAD

**Issue by abx-git** [weglide/bugtracker#48]
**Describe the bug**
In the scorecard for Electric flights, flights of other aircraft (Discus FES and Hp304) are listed but not the flights of the LAK 17-B FES.

**To Reproduce**
https://beta.weglide.org/flights?filter=[{%22index%22:%22order_by%22,%22name%22:%22-points%22}]

**Expected behavior**
Flights like https://beta.weglide.org/flights/5640 should appear in the list.

**Screenshots**
N/A

**Device (please complete the following information):**
not relevant

**Hints**
The entry in the aircraft list (extended.csv) looks correct, both the indicator 'engine' and the indicator 'FES' are set.

**Comment by flyingjoe** [comment]
Thanks for opening an issue! 
To get information about FES power consumption, it needs to be written into the igcfile. The MOP sensor seems to be missing in your case. 
We will clarify this in our documentation about the electric contest.
