### ISSUE TITLE
Tracks displayed on the map interfere with task definition

### ISSUE THREAD

**Issue by abx-git** [weglide/bugtracker#49]
**Describe the bug**
Previously displayed flights are not hidden when defining a new task and hinder the graphical definition of the turn points

**To Reproduce**
1. open a flight in order to display the track on the map
2. change to 'Define a task'
3. create a new task
4. start adding waypoints and legs in the same geograpical area as the displayed track

**Expected behavior**
The previously displayed tracks of the flights should not be displayed or should not interfere with the editing of the task waypoints

**Screenshots**
![image](https://user-images.githubusercontent.com/73913842/103438841-e98a4f80-4c37-11eb-9f07-f221028f96e6.png)

**Device:**
 - Windows / Chrome

**Comment by samuel-git** [comment]
Thanks, state management between maps needs cleanup.

**Comment by samuel-git** [comment]
Should be fixed in next release.
