### ISSUE TITLE
Search sometimes not responding

### ISSUE THREAD

**Issue by flyingjoe** [weglide/bugtracker#5]
**Describe the bug**
The search is sometimes not responding. This was only observed on mobile for now, but could be a problem on the desktop as well.

**To Reproduce**
1. Go to "flights" 
2. Enter anything
3. Search results should start to show up but sometimes don't

**Expected behavior**
Search results should show up 

**Device (please complete the following information):**
 - Device: Oneplus 7, iPhone X 
 - OS: Android 10, Newest iOS
 - Browser: Mobile Chrome, Mobile Safari

**Additional Information**
This needs further investigation, could be frontend or backend.

**Comment by samuel-git** [comment]
Please re-open if it appears again.
