### ISSUE TITLE
Flight phase statistics

### ISSUE THREAD

**Issue by tisoen** [weglide/bugtracker#51]
**Describe the suggested enhancement**
I like the statistics when viewing a flight, but what I'm missing the most compared to Skylines is a detailed thermaling and glide analysis that shows climb rate, speed, time, etc. of each individual thermal/glide. I think this feature is pretty helpful for precisely analysing some decisions and mistakes of a flight.

**To Reproduce**
1. View a flight
2. Scroll down to "statistics"

**Desired behavior**
A collapsible chronological list of all individual thermals and glides, marking the position/section of selected items on the map and barograph with stats like time spent, height difference, distance, average rate of climb/descent, average velocity and glide ratio

**Screenshots**
![image](https://user-images.githubusercontent.com/13700539/103462151-a60d0f80-4d23-11eb-8b03-055c091c5763.png)
(from skylines.aero)

**Comment by samuel-git** [comment]
@tisoen coming soon.

**Comment by samuel-git** [comment]
We just added a "circling" section to the leg statistics: 
![image](https://user-images.githubusercontent.com/22152728/105609021-c8d09800-5da6-11eb-8385-46e91d92a0bd.png)

I would rather not add a flight phase statistic page as this adds a lot of visual noise / makes the interface harder to use and can be rather long for 1000 km flights.

But we need some more feedback here. I understand that this is desirable for power users.

**Comment by samuel-git** [comment]
#80
