### ISSUE TITLE
Show airspace altitudes on map

### ISSUE THREAD

**Issue by tisoen** [weglide/bugtracker#52]
**Describe the suggested enhancement**
I really like the airspace display in the barogram (although it's maybe a bit low contrast). But when viewing a flight or planning a task it would be helpful to also see the altitude limits of airspaces on the map, at least when zoomed in.

**To Reproduce**
Open the map view of a flight or task planner and zoom in towards an airspace

**Expected behavior**
Show upper and lower altitude border of airspaces (when zoomed in), i.e. next to the airspace name.

**Screenshots**
![image](https://user-images.githubusercontent.com/13700539/103462457-9393d580-4d25-11eb-9706-957b66c5e4cf.png)

**Comment by samuel-git** [comment]
@tisoen coming soon + airspace detail view like the airport one

**Comment by samuel-git** [comment]
altitude in map on airspaces ships in next release
