### ISSUE TITLE
after IGC file download navigation is only possible via main menu

### ISSUE THREAD

**Issue by CarstenSon** [weglide/bugtracker#53]
**Describe the bug**
After downloading an IGC file, it is not possible to "go back" to the previous page. Also the browser buttons for navigation are not usable. 
Only by selecting the items in the main menu it is possible to get back to a "meaningful" page that does not exclusively offer a download link.

**To Reproduce**
1. Pick any flight
2. Download IGC file
3. only main menu remaining for navigation

**Expected behavior**
Either the browser navigation buttons would have to continue to work or another way to get to the previous page would have to be created. Alternatively, it would also be possible to open the download link including the consent in a separate tab/window.

**Screenshots**
n/a

**Device (please complete the following information):**
 - Device: Windows 10 20H2 Computer

**Comment by samuel-git** [comment]
Confirmed. This page is removed in next version (direct download).
