### ISSUE TITLE
Sorting order of flights in club ranking is not consistent

### ISSUE THREAD

**Issue by CarstenSon** [weglide/bugtracker#54]
**Describe the bug**
In the club rankings (Sprint and Plus) the sorting order of the flights is not consistent or not given. According to my tests, the problem does not occur in the individual and club overall rankings.

**To Reproduce**
1. Choose DMSt or Plus scoring
2. Set Category = club
3. see different or missing sorting orders of clubs rankings

**Expected behavior**
The flights shown should be listed in descending order - analogous to the individual scores from left to right. This is also the way it is used by other well-known portals.

**Screenshots**
n/a

**Device (please complete the following information):**
occured on all tested devices

**Comment by samuel-git** [comment]
Confirmed!
Affects order of flights in one ranking.

**Comment by moldhouse** [comment]
Thanks for reporting. Sorting was based on user_id which is probably not the expected behaviour :)
Will be fixed in next release.

**Comment by CarstenSon** [comment]
The Problem persists in the current release in the DMSt-"club"-ranking of 2020. Is it already patched or will it go live with the next release or this afternoon?

**Comment by moldhouse** [comment]
Frontend and backend are deployed separately - we will try to deploy tonight.

**Comment by CarstenSon** [comment]
Alright! Thanks a lot for the fast response and have wonderful day!

**Comment by CarstenSon** [comment]
Hey @moldhouse,

I just checked and everything looks good now in the DMSt ranking.

But what I noticed is that the club ranking for the plus ranking still has the same problem. Maybe you can reuse the problems solution of the DMSt ranking for the Plus ranking?

![grafik](https://user-images.githubusercontent.com/21118388/104502619-ba34f480-55e0-11eb-98d2-d5b9541922e8.png)

**Comment by moldhouse** [comment]
I think it works now :)

**Comment by CarstenSon** [comment]
I think so too!

Great to see and thanks! 👍
