### ISSUE TITLE
Club ranking takes into account more than the 5 flights

### ISSUE THREAD

**Issue by CarstenSon** [weglide/bugtracker#55]
**Describe the bug**
The club ranking in DMSt and Plus ranking takes into account more than the apparently intended 5 flights

**To Reproduce**

1.  Choose DMSt or Plus scoring
2.  Set Category = club and year = 2020
3.  see more then 5 flights accounted for some clubs

**Expected behavior**
Either the number of table headings would have to be increased if there are more flights (if this is the desired case) or only the first 5 flights should be included in the calculation.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/21118388/103488397-6110d800-4e0c-11eb-83aa-45d34953dc1a.png)

**Device (please complete the following information):**
 - any

**Comment by moldhouse** [comment]
Thanks for reporting. This appears to be the same issue as #38 and should be fixed with next release.

**Comment by CarstenSon** [comment]
I already thought it might be the same root cause as both errors occured in the club scoring but I wanted to open another issue if that wasn't the case and to keep those two issues apart 👍
