### ISSUE TITLE
Filtering/Searching for Flight-Indexes should be possible

### ISSUE THREAD

**Issue by Dimowelle** [weglide/bugtracker#58]
This is important for comparison with other flights. Searching e.g. 19.12.2020 index 68-90. 
For comparison it often makes sense, not to compare worldwide with all indexes/glidertypes.

**Comment by flyingjoe** [comment]
Good idea 👍

**Comment by moldhouse** [comment]
Maybe we should start with scoring class?

**Comment by Dimowelle** [comment]
Scoring class doesn't help comparing glidertypes with similar indexes - e.g. for indexes between 68-90 there are glidertypes in club-class and doubel-seater.

**Comment by moldhouse** [comment]
Yes I understand the use case and it is possible to implement for the API. However, I'm a bit concerned about the UI so we should make sure that we have some ideas how to make filtering easy and straightforward.

**Comment by Dimowelle** [comment]
Some ideas for filtering:
 - very nice (I would appreciate): new column and order ascending/descending
 - flexible but probably no good user experience: adjustment in the user profile
 - not so flexible: index sharpness +/- 10
 - makes problems at the border of ranges, I don't appreciate: ranges for indexes

For the "very nice" idea with a new column I have another nice idea to reduce one column:
The column "Mehr" with the content "zeigen" seems to be unnessesary because double?!
You can also view the flight by clicking the flight in the column "Punkte".

A more time expensive enhancement could be customizable columns and user-preferences in user-profile ...

**Comment by Dimowelle** [comment]
@moldhouse What do you think of filtering ascending/descending in the column "Mehr"?

You might think, Index is not so important for an extra column ...
then I have another idea, that goes in the detail of the field "Mehr" - as I mentioned "Mehr" is double, seams unnecessary:
Instead of the static field "Mehr" you can change the field to multiple entries e.g. Index, Window-Start-Time.
The column entries should then filled with content of e.g. index and should be ordered ascending/descending.

This method brings a wide range of further use, bringing more but customizable content on the page.

I think, this method of multiple entries is also used by amazon, ebay. google etc. 

Nethertheless: I think index is very important for comparison and competing especially with the nearly forgotten low-index glider-types and still with potential.

**Comment by samuel-git** [comment]
Good ideas but we have to focus on features that appeal to everyone and are straght forward. This one is kind of specialized and introduces a lot of added complexity in the UI (implications for mobile etc.).
You would not belive how many emails we get with questions how to use/find existing features (In this case "how to open the flight from the list").
I hope you can understand. We are maybe in 6-10 months ready to consider improvements like this one but not now.

**Comment by Dimowelle** [comment]
... I understand and will look next year in weglide.
Index-filtering is very important for gliding on low-index-gliders.

**Comment by Dimowelle** [comment]
Why implementing a comfortable filtering by columns in the UI?
More easier is "searching" in the Search-field with SQL-statements like "FROM", "TO". The content "Index" is already in the data-room for any glider for any flights, but not searchable - but this should be no problem with a new hidden column in the data-table...

Searching could look like this:
"Index" FROM 68 TO 85

As I mentioned - index search/filtering is a very important feature ...

Nice, if there would be an earlier solution ;-)
