### ISSUE TITLE
Flugdetails/Show-Layer/Aviation-Flüge does not show other flights

### ISSUE THREAD

**Issue by Dimowelle** [weglide/bugtracker#59]
I don't know what Aviation-Flüge should show, but it would be a very nice feature, to show other flights during the flight-time of the detailed flight ... maybe with a list of meeting-times.

**Comment by flyingjoe** [comment]
Do you mean meeting-pionts/wingmen?
That's something we already have:
![image](https://user-images.githubusercontent.com/28477393/103514676-68b49900-4e6d-11eb-9e1b-bfc5f3cec512.png)

**Comment by Dimowelle** [comment]
That's it! I will look for it on next flights, when there are wingmen :-) Thank you, this issue can be closed.
