### ISSUE TITLE
File validation is WIP

### ISSUE THREAD

**Issue by flyingjoe** [weglide/bugtracker#6]
**Describe the bug**
Valid files should show up as valid, invalid ones as invalid 

**Explanation**
The igc file validation is still work in progress and will be updated in the coming days. 
Until this is done, flights will have the label "file interim invalid" or "file interim valid"

**Comment by samuel-git** [comment]
https://docs.weglide.org/docs/contests/loggers/

**Comment by flyingjoe** [comment]
This should be done now. 
Documentation is updated.
