### ISSUE TITLE
Barogram of two flights shifted in time

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#60]
**Describe the bug**
Two files of a team flight have been uploaded. When comparing the flights, the barogram is fitting at the beginning and at the end of the flight. In between each barogram point of the red flight (8343) is displayed to late in time, while each point in the map fits perfectly.

**To Reproduce**
1. Go to https://beta.weglide.org/flights/13355,8343
2. Compare red and blue barogram
3. See error

**Expected behavior**
Both barograms should fit nearly perfectly, see OLC screenshot.

**Screenshots**
<img width="614" alt="weglide" src="https://user-images.githubusercontent.com/47079209/104043559-465bac00-51dc-11eb-8f06-0623dbaed89e.png">
<img width="638" alt="olc" src="https://user-images.githubusercontent.com/47079209/104043229-cd5c5480-51db-11eb-9c91-3fde567ab93a.png">

**Device (please complete the following information):**
 - Device: Laptop / Huawai P20 pro / Desktop PC
 - OS: Windows 10 / Android / Windows 10
 - Browser chrome / chrome / Firefox

**Comment by samuel-git** [comment]
Good find, not an easy fix unfortunately.

**Comment by samuel-git** [comment]
Okay, found the bug.
Minimum logger interval function used an average but your logger interval (for the shifted part) even lower so the interpolation lagged behind.
Fixed for next release.
