### ISSUE TITLE
Add meaningful meta data when sharing links

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#61]
**Describe the bug**
When sharing weglide links, always standard meta data is previewed, see screenshots.
Especially when multiple links (e.g. multiple flights of a day from different pilots) are send by e.g. whatsapp all descriptions are identical. It is not possible to identify the links, when searching for one of these links.

**To Reproduce**
1. Copy weglide link, e.g. https://beta.weglide.org/flights/844
2. Paste it to Whatsapp / Facebook etc.
3. See boring description (screenshots added)

**Expected behavior**
Meaningful meta data could be added, so that the main content is previewed, e.g.:
Picture: WeGlide logo or better (if feasible) flight map thumbnail
Headline: "WeGlide - Pilot Name"
Description: "Date - Points - km - km/h"

**Screenshots**
Facebook post:
<img width="243" alt="facebook" src="https://user-images.githubusercontent.com/47079209/104044393-8e2f0300-51dd-11eb-941c-1081660a8bbd.png">

Whatsapp message:
<img width="231" alt="whatsapp" src="https://user-images.githubusercontent.com/47079209/104045829-6c368000-51df-11eb-8f13-61c3207a5268.png">

**Comment by samuel-git** [comment]
This is somewhat tricky. The metadata is added but too slowly for the Whatsapp/FB bots to wait for (flight needs to load). So they rush and go with the default data.

**Comment by samuel-git** [comment]
Okay, this seems not possible with our setup for now.
