### ISSUE TITLE
Allow to share ranks with applied filters

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#62]
**Describe the bug**
Sometimes an URL to filtered ranks is necessary by clubs for sharing.
As an example an article "Club XY wins DMSt 2020 in Lower Saxony" is written and published on a clubs website. A link (or even an embedded iframe) to the results would be very nice.

**To Reproduce**
1. Go to https://beta.weglide.org/ranking/dmst
2. Apply some filters (e.g. Season "2020", Category "Club", Region "Lower Saxony")
3. Copy URL
4. Paste URL to new Browser Tab
5. See, that all filter settings are gone

**Expected behavior**
There should be a way to share the filtered DMSt results.
Two ideas:
1. Apply filter settings immediately to URL, so that the current URL always represents the current filter settings
2. Add share Box somewhere on the ranking page (below filter settings?), e.g.
<img width="281" alt="share" src="https://user-images.githubusercontent.com/47079209/104089436-4f498d80-526f-11eb-94a4-43345d7e1b74.png">

**Comment by samuel-git** [comment]
Good suggestion! I would go with option 1 as the space for a box is limited.

**Comment by samuel-git** [comment]
Coming in next release.
