### ISSUE TITLE
Club page missing

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#63]
**Describe the bug**
There are broken links in the ranking list.

**To Reproduce**
1. Go to https://beta.weglide.org/ranking/free
2. Apply filter: Category: "Club"
3. Click on any club (Link is e.g. https://beta.weglide.org/club/133)
4. See error (site not found)

**Expected behavior**
Link should lead to the clubs flight list, e.g. https://beta.weglide.org/flights?filter=[{%22name%22:%22LSV+L%C3%BCneburg%22,%22id%22:133,%22index%22:%22club%22},{%22index%22:%22order_by%22,%22name%22:%22-points%22}]

**Comment by samuel-git** [comment]
Hi, good find!

The club detail page is not jet implemented. Coming soon with some nice overviews!

**Comment by samuel-git** [comment]
Ready for next release.
