### ISSUE TITLE
Bug in Wingmen Calculation

### ISSUE THREAD

**Issue by henrik-the** [weglide/bugtracker#64]
**Describe the bug**
I think there is a bug in the Wingmen calculation. In one of my flights it shows that i have flown a very long time with another Plane, but i never did. In the part of the flight that is highlighted as "wingmen time" (the leg on the swabian alb) we even flew in different directions. 

**To Reproduce**
1. Go to my flight 'https://beta.weglide.org/flights/1087'
2. Click on 'Wingmen'
3. Click on 'Michael Wisbacher'

Additionally you can compare the flight under:
https://beta.weglide.org/flights/3581,1087

**Expected behavior**
WeGlide should only count time, where we are in proximity.

**Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows
 - Browser: chrome

**Comment by samuel-git** [comment]
Please also fix the ordering (by meeting time) while you are on it.

**Comment by moldhouse** [comment]
I can't reproduce this locally. Would you mind deleting your flight and uploading it again? We might have already fixed this bug.

<img width="739" alt="image" src="https://user-images.githubusercontent.com/24278651/105372288-b834ec00-5c05-11eb-8f01-68372783cc99.png">

**Comment by henrik-the** [comment]
I have reuploaded the flight. And i think now it shows the correct meeting times 👍
