### ISSUE TITLE
Hiding the Flight Detail Panel (Enhancement)

### ISSUE THREAD

**Issue by henrik-the** [weglide/bugtracker#65]
Possible Enhancement:
When comparing flights (for example of a competition day) it would be nice to have a big map window.
So it would be nice, if there would be a button to hide the flight detail panel (maybe also the Height diagram).

See attached Screenshot:
![image](https://user-images.githubusercontent.com/64869196/104097111-69e62b80-529c-11eb-94fe-ecd2a712b101.png)

**Comment by Dimowelle** [comment]
Comparison of flights also works with:
Search Flight
Select-Field: date, name, ... what you want

![2021-01-09-213932_1366x768_scrot](https://user-images.githubusercontent.com/76923146/104108233-379bf480-52c3-11eb-8e97-0971bd9d627d.png)

**Comment by samuel-git** [comment]
This is not easy to hide but as a completely different page it's already available: 
* Click on the share button in flight detail panel
* Open the "Embed" url

Should be better accessible.

**Comment by henrik-the** [comment]
Thanks! That is what i was looking for 👍
