### ISSUE TITLE
Implausible wind calculation (only within some flights)

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#66]
**Describe the bug**
Calculated wind direction in statistics is different from cycling wind offset.
This behavior is only observed at some flights.

**To Reproduce**
1. Go to https://beta.weglide.org/flights/6802
2. Open statistics
3. See calculated wind direction (NW) and compare it to wind offset while cycling (SSW), see screenshot.

**Expected behavior**
Calculated wind direction should be SSW.

**Screenshots**
<img width="905" alt="wind" src="https://user-images.githubusercontent.com/47079209/104105798-0e726880-52b1-11eb-98a0-52abe86721f5.png">

**More Examples:**
https://beta.weglide.org/flights/4417
calc: NNE / cycling: SE

https://beta.weglide.org/flights/7153
calc: NW / cycling: SW

https://beta.weglide.org/flights/4401
calc: WNW / cycling: WSW

https://beta.weglide.org/flights/7137
calc: ENE / cycling: ESE

**Comment by moldhouse** [comment]
Thanks for reporting, I spotted this in some other flights too. Seems to be some ~90 degrees offset for some flights.

**Comment by moldhouse** [comment]
Seems like the north component is upside down while the east component is right.

**Comment by frantzheld** [comment]
You could be right in all examples above. 
Unfortunately this observation is not consistent at every flight. In the following example, the wind calculation seems ok:
https://beta.weglide.org/flights/4524
![image](https://user-images.githubusercontent.com/47079209/104159072-f3a60e00-53ee-11eb-9121-0535d01e2c4c.png)

**Comment by moldhouse** [comment]
North component might not be flipped every time. But I think I have not seen a flight where the west-east component is wrong.

**Comment by moldhouse** [comment]
Fixed in next release. We will recalculate for old flights, if you still experience this issue a week from now feel free to reopen. 
Thanks again for the detailed feedback.

**Comment by frantzheld** [comment]
Today the wind was still wrong for flight 6802.
I deleted and re-uploaded the flight, now everything seems fine: https://beta.weglide.org/flights/16548

Are you still planning recalculation for all old flights?

**Comment by moldhouse** [comment]
Yes, we will do that, but there are small changes in other places (Out and Return scorer) which will also be affected, which is why we did not rescore yet.
