### ISSUE TITLE
Highlight legs in Baro and Map

### ISSUE THREAD

**Issue by Dimowelle** [weglide/bugtracker#67]
It would be nice to see the gliding-window and tracks-segments in the map and the barogramm-view.
E.g.: Non-Gliding track =black line in map
Track in Gliding-Window =blue line in map 
Marked segements from the Statistic-Area = red-shadow in barogram-view (red line in map works already)

... and maybe also the other way around:
clicking in the map/barogram-view marking the segments in the statistic-area and barogram/map
![2021-01-09-221431_1366x768_scrot](https://user-images.githubusercontent.com/76923146/104108909-ebec4980-52c8-11eb-87ae-3d6cef52a7bf.png)

**Comment by samuel-git** [comment]
Hey Dimo, good suggestions. 
From a visualization point of view, there is definitely room for improvement.
The other way round is sadly not practical (interfers with zoom/drag&drop gestures).
For now we added a second thermal section for next release.

**Comment by samuel-git** [comment]
#80
