### ISSUE TITLE
Wrong distance calculated for uploaded pictures 

### ISSUE THREAD

**Issue by YannisHartung** [weglide/bugtracker#69]
**Describe the bug**
The distance label next to the pictures of the story is sometimes wrong. 

**To Reproduce**
1. Go to https://beta.weglide.org/flights/844
2. Scroll down to the pictures
3. See that Philipp has already flown 6000 km before taking the pictures.

Also at the last picture of this flight: 
https://beta.weglide.org/flights/849
We only flew 220 km, but the picture was taken after 260 km. 
And the picture here: 
https://beta.weglide.org/flights/2021

**Expected behavior**
See the right distance. 

**Screenshots**
![image](https://user-images.githubusercontent.com/64095851/104477695-b5ad1380-55c1-11eb-89fa-27e7d13e3213.png)

**Device (please complete the following information):**
 - Device: Google Pixel 4, Desktop PC 
 - OS: Android, Windows
 - Browser: Chrome, Chrome

**Comment by CarstenSon** [comment]
This is probably identical to Issue #7: 
https://github.com/weglide/bugtracker/issues/7

Solution there was deleting the images and adjusting the scoring period to recalculate them

**Comment by YannisHartung** [comment]
Reuploading flight and image worked.

**Comment by samuel-git** [comment]
Was due to an older analysis bug. Is fixed now.
