### ISSUE TITLE
km figure displayed at some images does not match actual flown km

### ISSUE THREAD

**Issue by CarstenSon** [weglide/bugtracker#7]
**Describe the bug**
km figure displayed at some images does not match actual flown km. 

**To Reproduce**
I have also seen numerous images where this problem does not occur, but for my images/flights, the problem has occurred for all flights and images uploaded so far.
In my case the steps to reproduce the issue were:
1. upload pictures
2. see wrong km figures

**Expected behavior**
km figure for images from cameras without GPS sensor should be generated via the timestamp of the photo. km figure for images from cameras with GPS sensor should be assigned via GPS coordinates and time.

**Screenshots**
"story" area of an examplary flight (only ~ 540 km total flight distance)
![grafik](https://user-images.githubusercontent.com/21118388/103105206-978c6d00-462c-11eb-9ec8-13b2b273b30c.png)
https://beta.weglide.org/flights/902 <- This is a link to the exemplary flight

**Device (please complete the following information):**
 - Device: Computer
 - OS: Windows 10 Version 20H2
 - Browser Firefox 84.0.1 (64-Bit)

**Comment by samuel-git** [comment]
Thanks for documenting this bug! We are on it @moldhouse .

**Comment by CarstenSon** [comment]
If you need the original files including EXIF information, feel free to let me know.

So far I have noticed a tendency: I haven't seen this problem with images that don't have the time (I assume it's fetched from the EXIF information).

**Comment by moldhouse** [comment]
Thanks for reporting! Yes, providing the image containing exif would be very helpful.

**Comment by CarstenSon** [comment]
just sent you an email containing the picture including its exif information

**Comment by moldhouse** [comment]
Hi Carsten, I could reproduce the bug. We had a logic problem in the way we project the flight path onto optimized score to calculate the distance in between turnpoints. We will deploy this afternoon, you need to rescore your flight (change scoring intervals by 1s) and upload the story again afterwards. Thanks again for reporting in detail.

<img width="1578" alt="image" src="https://user-images.githubusercontent.com/24278651/103134940-dd8d1380-46b4-11eb-85d1-8a023ecfce27.png">

**Comment by CarstenSon** [comment]
Hi Moritz,
thanks for the fast bugfix and investigation! I've just tested it and now it works like a charm.
