### ISSUE TITLE
Allow filtered daily best bookmark

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#70]
**Describe the feature**
It would be a helpful feature to allow bookmarks to filtered daily scores.

**To reproduce**
1. Click the "Show daily" button on the home page, see screenshot
2. This link leads to the flight list for a **static** date, e.g.:
[https://beta.weglide.org/flights?filter=[{"index":"date","name":"**2021-01-13**"},{"index":"order_by","name":"-points"}]](https://beta.weglide.org/flights?filter=[{"index":"date","name":"2021-01-13"},{"index":"order_by","name":"-points"}])
3. When bookmarking this link, it always leads to a fixed day

**Expected behavior**
1. For storing the daily scoring in a bookmark or for adding it to the home screen on smartphones, a flexible link should be accessible, e.g.:
[https://beta.weglide.org/flights?filter=[{"index":"date","name":"**daily**"},{"index":"order_by","name":"-points"}]](https://beta.weglide.org/flights?filter=[{"index":"date","name":"2021-01-13"},{"index":"order_by","name":"-points"}])
2. More filters like region should be applicable, so that users can store a link to e.g. "Daily Score Lower Saxony". (I think this would be already possible?)
3. The link should always lead to the latest day, on which flights are available within the selected filter settings. In this example: Latest day, where flights have been uploaded in Lower Saxony. (Otherwise it leads to "No flights with these filters.")

**Screenshots**
![image](https://user-images.githubusercontent.com/47079209/104810857-d1016400-57f7-11eb-9180-04d5e36c0f75.png)

**Comment by moldhouse** [comment]
I would love this feature!

**Comment by samuel-git** [comment]
I would propose a new boolean daily parameter as the current solution via activity endpoint needs two api calls.
@flyingjoe is it possible to put this in search with translations?

**Comment by samuel-git** [comment]
#80

**Comment by frantzheld** [comment]
https://beta.weglide.org/flights?country=Deutschland,DE&order_by=-scoring_date

`order_by=-scoring_date` solved this issue for me... 👍
