### ISSUE TITLE
Cannot "un"declare task

### ISSUE THREAD

**Issue by CarstenSon** [weglide/bugtracker#72]
**Describe the bug**
I  have created a task and in the process of creating it, I seem to have declared it directly. Therefore, I cannot delete the task now, even if that would be my wish.

I can't find a way for me to "un "declare a flight.

**To Reproduce**
1. Create Task
2. Declare Task
3. can't "un"declare task/delete task 

**Expected behavior**
there should be a possibility to "un"declare a task or force to delete it maybe as the creator of the task

**Screenshots**
n/a

**Device (please complete the following information):**
 - Device: any

**Comment by samuel-git** [comment]
Hi CarstenSon,
once a task is declared (no matter from whom) it becomes public domain and can therefore not be deleted by you.
I agree that this is somewhat difficult do communicate but there is no other option as declared tasks might appear in flights.

A delete button will be added soon.

@moldhouse maybe we could allow deletion for private tasks even if they were declared?

**Comment by samuel-git** [comment]
Improved in next release
