### ISSUE TITLE
Flight declaration while uploading flights keeps jumping to newest tasks

### ISSUE THREAD

**Issue by dspreitz** [weglide/bugtracker#73]
**Describe the bug**
I uploaded multiple IGC files. Once the first IGC file is processed, a window opens below the flight process queue, which lets me add the declaration features of the flight.
However, when another flight of the queue finishes processing the declaration window immediately jumps to the new flight. This is quite annoying, because you effecively cannot declare flights, while the upload of all files is not finished, because the declaration window keeps jumping between flights

I really like that you have the capability to upload multiple files and that you want to offer a certain degree of parallelism in it.

**To Reproduce**
See above.

**Expected behavior**
Expected behaviour would be, that the flight declaration window remains on the first processed flight and only upon user interaction another flight declaration is shown.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1283730/104855987-32b4f180-5910-11eb-985b-12162def5c64.png)

**Device (please complete the following information):**
 - Device: Macbook
 - OS: OS X
 - Browser Firefox 78

**Comment by samuel-git** [comment]
Thanks for reporting. Your suggestion will be implemented to mitigate this issue.

**Comment by samuel-git** [comment]
Fixed for next release (inclusive aircraft preselection).
