### ISSUE TITLE
Wrong detection of "DMST Viereck"

### ISSUE THREAD

**Issue by henrik-the** [weglide/bugtracker#74]
**Describe the bug**
WeGlide ist detecting this task as a "Viereck":
https://beta.weglide.org/task/6609
![image](https://user-images.githubusercontent.com/64869196/104931912-59723700-59a7-11eb-904b-a7aec1e0ebfb.png)
So it receives the x1.7 Bonus.

Aber in der DMST Wettbewerbsordnung steht unter Punkt 4.3.2 c):
"c. die Dreiecke dürfen nicht übereinander liegen"

**To Reproduce**
1. Go to 'https://beta.weglide.org/task/6609'
2. See error

**Expected behavior**
"DMST Vierecke" should not receive Bonus, if the triangles are overlapping.

**Comment by samuel-git** [comment]
Thanks for reporting! We will look into it.

**Comment by moldhouse** [comment]
Thanks for reporting. 

4.3.2 Vierecksflug
Bei einem geschlossenen angemeldeten DMSt-Vierecksflug wird ein Bonus von 70% addiert, wenn die Fläche zwischen den Wendepunkten bzw. den Wendepunkten und dem Abflug-/Endpunkt durch zwei Dreiecke beschrieben werden kann, für die gilt:
a. beide Dreiecke müssen dieselbe Forderung nach 4.3.1a bzw. 4.3.1b erfüllen,
b. die Dreiecke müssen mit einem identischen Schenkel aneinander liegen,
c. die Dreiecke dürfen nicht übereinander liegen.

Your task fullfilles a) and b) but not c)

We are not evaluating c) yet, I will add it tommorrow.

**Comment by moldhouse** [comment]
So if your WP are ABCDA (B and D are identical in your case) I think it would be sufficient to check that 

- B and D are on different sides of the line going through A and C
- A and C are on different sides of the line going through B and D
