### ISSUE TITLE
Rectangle is displayed as triangle in task overview

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#75]
**Describe the bug**
The 670km DMSt rectangle (https://beta.weglide.org/task/3695) is displayed incomplete in task overview.

**To Reproduce**
1. Create DMSt rectangle task
2. Go to task overview
3. See that one turnpoint is missing on the map, see screenshot 1
4. See that the distance on the list card is to small (distance of the small triangle)

**Expected behavior**
Screenshot 2 shows the task when opened. It's a 670 km rectangle. It should be displayed as such in the overview.
The list card should show the correct distance.

**Screenshots**
![image](https://user-images.githubusercontent.com/47079209/105504056-9bf98380-5cc7-11eb-923a-993a23fca223.png)
![image](https://user-images.githubusercontent.com/47079209/105503944-79676a80-5cc7-11eb-9c03-bd0fed8690b9.png)

**Device:**
 - Device: Acer Laptop
 - OS: Windows
 - Browser: chrome

**Comment by frantzheld** [comment]
Fun fact: I've build **exactly** the same task again: https://beta.weglide.org/task/7734

Now everything works fine:
![image](https://user-images.githubusercontent.com/47079209/105505632-7b322d80-5cc9-11eb-933f-d6b78478db57.png)

Only the distance has grown by 0.03km

**Comment by moldhouse** [comment]
We already fixed this a while ago (thanks to the detailed feedback) but it took us some time to get it to the server and apply the fix backwards.
