### ISSUE TITLE
Download multiple tasks

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#76]
**Describe the bug**
I planned a series of tasks. To download them all, I have to open every singe task and download it as a single file.

**Expected behavior**
It would be a nice feature to allow multiple task download once.

**Screenshots**
![image](https://user-images.githubusercontent.com/47079209/105511381-1dedaa80-5cd0-11eb-9922-547bdb782418.png)

**Comment by samuel-git** [comment]
The only difficulty I see with this is: How to select the tasks?
A button for downloading all your tasks at once would be easy to implement and maybe sufficient?

**Comment by frantzheld** [comment]
All my tasks at once world be sufficient. :)
Or maybe implement the download button for both, my tasks and my favorites?

**Comment by samuel-git** [comment]
#80

**Comment by frantzheld** [comment]
One more comment regarding task downloads:
When downloading a task, the filename is always _task_container.cup_
If feasible, the task name could be set as filename.

**Comment by FliegerBP** [comment]
I would really like to have the ability to pack several tasks into a cup file and download them at the same time. With SeeYou, that's no problem. It saves a lot of work.
