### ISSUE TITLE
Flight list: filter by year

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#77]
**Describe the bug**
Many filters can be applied to the flight list, e.g. pilot, club, region, airport, single date, glider class....
So far it is not possible to filter by year.

**To Reproduce**
1. Go to https://beta.weglide.org/flights/map?filter=[{%22index%22:%22order_by%22,%22name%22:%22-points%22}]
2. Type "2020" into Search input
3. Press Enter
4. Nothing happens

**Expected behavior**
Flight list should be filterable by year.

Together with other filters this would give a lot of possibilities, e.g.:
- Display all your own flights of one year
- Display all flights of your club for one year and make screenshot of the map for an annual club review
- How far did I fly into the alps in my 2018 France holiday? How did this change 2019?
- ...

Alternatively a custom period of time would solve the problem, e.g. "01.01.2020-31.12.2020".
This would allow users to display any time period they want.
Advantage: more flexibility
Disadvantage: more complicated to use (It's easier just to type "2020" into the search field).

I would prefer the simple year filter. What do you think?

**Screenshots**
![image](https://user-images.githubusercontent.com/47079209/105526456-bdb43400-5ce2-11eb-9c06-10321882c2be.png)

**Comment by samuel-git** [comment]
This is currently in the works.
We need some more days to add season filtering. Nice to see this one is wanted!

**Comment by samuel-git** [comment]
#80
