### ISSUE TITLE
Adjust airspace age with flight date

### ISSUE THREAD

**Issue by samuel-git** [weglide/bugtracker#78]
**Describe the bug**
Airspace violations on upload are calculated according to the newest airspace.

**Expected behavior**
Use the airspaces from the season of the flight.

**Comment by samuel-git** [comment]
Additional: Make older airspace available e.g. as map layers.

**Comment by deltafox44** [comment]
Airspace penetration is subject to radio clearances or temporary area activation, it's impossible to assume violations and it is the responsibility of the pilot.
For me airspace layer is useful only for flight planning, which involves only current airspace.

**Comment by flyingjoe** [comment]
@deltafox44 I agree that it's not useful to see if an airspace was violated and that's not the intention. Seeing airspaces from the time of the flight can help understand decisions the pilot made at the time which may seem weird with todays airspace.
It's quite low priority though.
