### ISSUE TITLE
Improvement: Allow addition of club logo

### ISSUE THREAD

**Issue by Scumi** [weglide/bugtracker#79]
**Describe the bug**
A club can be selected, but no logo is displayed currently (no bug).

**To Reproduce**
n/a

**Expected behavior**
Allow the upload of the club logo.
Display the club logo when showing a club.

**Screenshots**
n/a

**Device (please complete the following information):**
n/a (all)

**Comment by samuel-git** [comment]
Hi Scumi, 
this is rather difficult as we need to moderate uploads for 3k+ clubs.
My idea is to make a database here on github where everyone can submit their homepage URLs, wikipedia link, logo etc. and we build something like a peer review.
My fear is that most of the clubs do not even have a logo.

**Comment by Scumi** [comment]
>  My fear is that most of the clubs do not even have a logo.

You think? I would think its the other way around. You could display a placeholder if there is nothing uploaded.

Anyways, its a nice-to-have idea with low priority. Your implementation idea is fine too.

**Comment by samuel-git** [comment]
Yes I think so, its hard to get good quality logos (transparent background, fitting aspect ratio, sufficient resolution, modern look..). Most of these logos would need a time consuming rework.

**Comment by flyingjoe** [comment]
Thanks for your Idea - I also think that would be a great addition. In order to do this we'd need to know who is actually a member of  a club and is allowed to change the logo - otherwise we'd propably see a lot of trolling. 
I'm closing this for now since this is really low priority.
