### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by samuel-git** [weglide/bugtracker#80]
To keep the issue list short and relevant, please submit your feature request here below.
We will work on them when we have spare time left based on upvotes/technical feasability.
Will close separate feature request issues and reference them here.

Excited to hear your Ideas!

**Comment by flyingjoe** [comment]
Dark Mode.

**Comment by henrik-the** [comment]
Upload custom waypoints to plan task.
Alternatively one big waypoint database to which every user can contribute

**Comment by frantzheld** [comment]
With the increasing number of tasks the task overview will become more and more confusing.
The single legs of one task cannot be assigned to it anymore since hundred of legs are criss-cross.

![image](https://user-images.githubusercontent.com/47079209/105635884-bc5f4480-5e65-11eb-9010-776eab80e76b.png)

To improve user-friendliness:
- Make all task legs thinner per default (or reduce opacity for a lighter appearance)
- When highlighting a task with the mouse, make it thicker/darker (this would help a lot to retract tasks, since the highlighted task would stand out of all other tasks)
- When clicking on a task on the map then open the task

With the suggested improvements the task map behavior will get quiet similar to the flight map, where the highlighted flight already stands out of all other flights:
![image](https://user-images.githubusercontent.com/47079209/105636347-4a3c2f00-5e68-11eb-9c23-d27a062e6b56.png)

**Comment by samuel-git** [comment]
@frantzheld ready for next release

**Comment by floriangaller** [comment]
make it possible to filter fligtlist by date range

e.g. display all flights of Januar 2021 by 01.01.2021-31.01.2021

**Comment by samuel-git** [comment]
@floriangaller we are working on it. Do you have ideas how this could look? Help is appreciated.

**Comment by frantzheld** [comment]
Filter tasks by region

**Comment by samuel-git** [comment]
@frantzheld done for next release

**Comment by samuel-git** [comment]
@floriangaller coming this week

**Comment by frantzheld** [comment]
**Title:**
Apply date filter by Search field.

**Description:**
The activity-range input is a nice and powerful tool to find and select dates for the flight list. I love it!
Nevertheless it's a lot faster just to type in a date if you know the exact date. (I remember this was already possible some weeks ago!?)
Maybe revive this possibility and expand it with the new range filter. 
- Single Date: `13.07.2020`
- Range: `01.01.2020-31.12.2020`
- Start: `>01.01.2020`
- End: `<31.12.2020`

Either the regional date format should be used or all common date formats should be detected (e.g. 13.07.2020 / 2020-07-17)

**Screenshots:**
![image](https://user-images.githubusercontent.com/47079209/106581099-c4447600-6542-11eb-841f-b6a8c95a5776.png)

**Comment by samuel-git** [comment]
@frantzheld this is difficult due to ambigous date formats across languages and fuzzy inputs. My take is that visual clicks might be faster (at least on touch devices). We are working on a season filter for the search.

**Comment by frantzheld** [comment]
Result row below flight list. 
![image](https://user-images.githubusercontent.com/47079209/106773742-b32e5e80-6641-11eb-9042-7124a604668b.png)
e.g. Number of flights XX, Total points: XXXXX, Total Airtime: H:MM, Pilots: XX, Total Distance: XXXXX km, Mean Speed: XXX km/h

This feature would allow users to generate individual statistics, e.g.
- My total distance in 2020
- My total airtime in the alps
- My airtime in my 2019 Vinon holiday
- My number of flights in 2018
- My clubs distance in july 2020
- Total distance flown from Lüneburg in 2020
- Number of different pilots, which have started in Zwickau in the last 3 years
- etc

**Comment by samuel-git** [comment]
Declare task until (+1 Day, +7 Days) and reverse task direction option.

**Comment by samuel-git** [comment]
@frantzheld cool idea. This also helps signaling when the "infinity" scroll comes to an end.

**Comment by frantzheld** [comment]
Show thumbnail when hovering a story picture on the map.
![image](https://user-images.githubusercontent.com/47079209/107118096-2bce2e80-687f-11eb-82da-b2fbe58279ed.png)

Show story pictures in a lightbox when clicking on it. Close lightbox when clicking again.
![image](https://user-images.githubusercontent.com/47079209/107118083-06412500-687f-11eb-8845-bcaf8d58daeb.png)

I don't know if this is feasible or if it could even be annoying. Feel free to discuss :)

**Comment by samuel-git** [comment]
@frantzheld hovering does not work on mobile devices, we try to keep the experience as universal as possible. The "lightbox" effect is already there on desktop but for the whole story at once (saves clicks).
I admit that a hovering over these icons feels natural/immersive.

**Comment by samuel-git** [comment]
Flight list summary below list is coming for next release.

**Comment by frantzheld** [comment]
Order tasks by distance.

**Comment by frantzheld** [comment]
Add "Flight as lists" button to club page and unify wording:

Aircraft page:
![image](https://user-images.githubusercontent.com/47079209/107657172-332d7780-6c85-11eb-8828-238e188dc64c.png)

Airport page:
![image](https://user-images.githubusercontent.com/47079209/107657520-87d0f280-6c85-11eb-948c-2feda39d7c4e.png)

**Comment by frantzheld** [comment]
Add statistics to club page

**Comment by samuel-git** [comment]
> Order tasks by distance.

This is not an easy task:
1. range slider with two knobs (e.g. --O----------O--------): How to determine min/max values?
2. drop down with preselected values (e.g. 100 - 200km, 200-500km): How to set these?

Ideas / preferences are appreciated.

**Comment by samuel-git** [comment]
> Dark Mode.

Coming when our design is more mature/stable. I dont like to change everything twice atm.

**Comment by samuel-git** [comment]
> Add "Flights as lists" button to club page and unify wording:

Fixed for next release.

**Comment by frantzheld** [comment]
> > Order tasks by distance.
> 
> This is not an easy task:
> 
> 1. range slider with two knobs (e.g. --O----------O--------): How to determine min/max values?
> 2. drop down with preselected values (e.g. 100 - 200km, 200-500km): How to set these?
> 
> Ideas / preferences are appreciated.

You suggest a distance range filter - that's much more than I had in my mind.

I was just looking for a really simple dropdown to change the default `order_by` from `-starts` to e.g. `-distance`, see
https://api.weglide.org/redoc#operation/get_task_by_user_v1_task_get

**Comment by AKASpam** [comment]
plz add filter for distance in addition to date, aircraft and club/airport
for example i would like to see all flights upt to 500km or 550 - 650km and so on.
maybe a keyword would be "km" if i enter 550km I see all flights to 550 kilometers, if i type 400km-550km i see all that kilometers; don´t know if < = > work (e.g. >800km)
thanks in advance!

**Comment by samuel-git** [comment]
@AKASpam this could be done with universal filters which work for flights and tasks alike. Saves half the work.
Would look similar to my proposal option 2 for task filtering but in the search bar. I like this as it eliminates the need for an extra dropdown but could be an issue with different unit settings (Imperial/Metric) @flyingjoe ?

**Comment by flyingjoe** [comment]
@samuel-git @AKASpam We'll just use < and > as indicators for such a request and suggest it accordingly. This could also be done with numeric entries where there is only a small number of hits.

**Comment by frantzheld** [comment]
![image](https://user-images.githubusercontent.com/47079209/108620871-45e73f80-742f-11eb-9f4e-c8ba4e749308.png)

### Exchange static title picture by "picture of the month".

Your title picture is really beautiful! But if you see the same picture again and again it will get boring at some time.
Users have uploaded thousands of amazing photos to their stories.
At the moment I have no idea how to use them, but maybe someone else has an idea...
Something like a voting for the picture of the month or maybe if it will be possible to like single story pictures, show the picture with the most likes of the month....

I think this feature is very low prio, but maybe you'll have a good idea of implementation at some time in the future.

**Comment by frantzheld** [comment]
Change default flight list ordering from `-points` to `-scoring_date` to get the flight list less static...
https://beta.weglide.org/flights?order_by=-scoring_date

**Comment by samuel-git** [comment]
@frantzheld not sure about this as some (invalid) flights are from the future:
![image](https://user-images.githubusercontent.com/22152728/108988458-c78bd700-7694-11eb-8a29-a495ae874b5e.png)

**Comment by frantzheld** [comment]
@samuel-git good objection... I didn't see that.
Is there a possibility to check date plausibility within the upload process? (@moldhouse)

If you'll find any comprehensive solution to exclude these flights, I'd really prefer the `-scoring_date` ordering per default.
Most users are interested in the newest flights. I know a lot of pilots checking the "Tageswertung" every 5 minutes in summer to see whats new. The "🔍 Flights"-Button might be the most used on weglide to display the most important dynamic content: the latest flights.

With the default `-points` ordering the flight list gets static and behaves more like a ranking page for all-time-records:
![image](https://user-images.githubusercontent.com/47079209/108989626-16863c00-7696-11eb-8533-73395a7394b4.png)

**Comment by moldhouse** [comment]
We now throw a 400 error if the flight is from a future date. I will delete the future flights and then we should be fine.

**Comment by moldhouse** [comment]
@samuel-git I have deleted the future flight and in my opinion, we should change the default order as suggested

**Comment by samuel-git** [comment]
@frantzheld default ordering is changed to scoring date

**Comment by samuel-git** [comment]
> @samuel-git @AKASpam We'll just use < and > as indicators for such a request and suggest it accordingly. This could also be done with numeric entries where there is only a small number of hits. 

This feature is live. Just start typing e.g. "> 1xx".
Same for "Today" or "yesterday".

Your language and unit settings are honored.

**Comment by frantzheld** [comment]
### Heatmap for story pictures
Sometimes you are looking for pictures of a special location.
It would be an amazing feature to show **all** story pictures on one map.
Since thousands of pictures would flood the map, it would be an idea to sum up the pictures to a heatmap.
When zooming in, the heatmap gets more detailed.

As an example I added screenshots of my google photos account:
![heatmap](https://user-images.githubusercontent.com/47079209/112160366-60593800-8bea-11eb-90d2-aef229812c6b.jpg)

Multiple heatmaps could be provided (all pictures, my club pictures, my own pictures).

**Comment by Cubdriver406** [comment]
If I upload an IGC file from a fellow contest pilot to WeGlide to compare our flights on a contest day WeGlide uploads HIS IGC file with MY name as the pilot. This assumes the fellow contest pilot has not already uploaded his personal IGC file into WeGlide. This also puts his IGC file into my list of flights with my name as the pilot into my profile. Is it possible to keep the IGC files identified by the correct pilot so these issues are resolved?

**Comment by samuel-git** [comment]
@Cubdriver406 We can not safely identify a pilot on the IGC file alone. We sadly can not provide a feature to upload flights for other pilots due to potential for abuse.
It is possible to upload flights for registered pilots if you know their name and date of birth and have their consent to upload in their name. Just log out of weglide and try to upload.

**Comment by samuel-git** [comment]
Okay, excuse the undecided handling of feature requests here on GitHub.
We think it is easier to open separate issues for each feature request and enable better diskussions to each issue on itself.
I will still honor the amazing proposals here and will not close this thread until everything is done.

**Comment by Cubdriver406** [comment]
Thank you for the quick response.

I was thinking it might be possible to upload another pilot's IGC file into
WeGlide the same way it can be done on SeeYou's software. If another pilot
has publicly posted their IGC file on OLC then their permission is not
needed to view the flight file. Similarly, if their IGC file is posted on
the contest website then their file is available for viewing on SeeYou and
other software.

Regards

**Comment by AKASpam** [comment]
Asking for a measuring tool.
Idea: nearby the center map and layer could be the measuring icon
Debriefing flights (Flüge) might be handy to measure glide distances by hand - or to wherever i would like to measure
if possible to implement:
Start measuring from-to
drag and change positions (of start - end point) - show distances (km)
-pretty much as simple as in google maps
if more than 2 points possible it would be great, if not 2 points are ok for the start
whenever you have time - upon implementation i´ll buy you a beer - cheers

**Comment by Cumulus7** [comment]
> @frantzheld hovering does not work on mobile devices, we try to keep the experience as universal as possible. The "lightbox" effect is already there on desktop but for the whole story at once (saves clicks).
> I admit that a hovering over these icons feels natural/immersive.

How about making it possible to at least click on the picture-Icons on the map to show the selected photo?
That does not work on Chrome (PC) or Chrome (Android).
At the moment you can only see that a picture was taken at that point in the flight but you have to manually look for it in the picture list. (or am i missing something?)

Greetings,
Markus

**Comment by samuel-git** [comment]
@Cumulus7 this is currently not possible.

An icon click would need to trigger:
1. Open the story in fullscreen
2. wait until everything is loaded
3. scroll to the picture

This could cause confusion when the user wanted to click on e.g. an airport and missed.
This is (apart from technical difficulty) the reason its not been done yet but I share your opinion that this needs to be more interactive.

**Comment by sandroLE** [comment]
**Compare flights**

The feature to compare flights of wingmans is great. But sometimes a flight of a buddy is not recognized as a wingman, if he is constantly a few kilometers ahead.  It would therefore be very helpful to be able to select several flights from a filtered list for comparison.

**Comment by samuel-git** [comment]
Hi @sandroLE,
this is rather difficult UX wise.
Please add the desired IDs comma separated to the end of the url to compare arbitrary flights in the meantime.

**Comment by samuel-git** [comment]
@frantzheld ordering by distance for tasks and some more is coming tomorrow.

**Comment by samuel-git** [comment]
> plz add filter for distance in addition to date, aircraft and club/airport
> for example i would like to see all flights upt to 500km or 550 - 650km and so on.
> maybe a keyword would be "km" if i enter 550km I see all flights to 550 kilometers, if i type 400km-550km i see all that kilometers; don´t know if < = > work (e.g. >800km)
> thanks in advance!

This feature is live. Please look here: https://docs.weglide.org/docs/how_to/filters/#possible-filters :+1:

**Comment by samuel-git** [comment]
**Will close this issue. Please open new suggestions as new issue.**
