### ISSUE TITLE
Missing flights in DMSt club ranking

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#81]
**Describe the bug**
The DMSt Club ranking is incomplete. A lot of flights are missing. For SFG Bensheim for example only two flights are counted into DMSt club ranking, even though more than two valid flights were uploaded. My Club (LSV Lüneburg) is missing completely.

**To Reproduce**
Steps to reproduce the behavior (SFG Bensheim):
1. Go to https://beta.weglide.org/ranking/dmst?season=2020&category=club&user=ALL&sc_class=ALL
2. Notice that for SFG Bensheim only two flights are scored (screenshot 1)
3. Go to https://beta.weglide.org/flights?filter=[{%22index%22:%22club%22,%22name%22:%22SFG+Bensheim%22,%22id%22:30},{%22index%22:%22order_by%22,%22name%22:%22-distance%22}]
4. See that more than two flights are relevant for club scoring (screenshot 2)

Steps to reproduce the behavior (LSV Lüneburg):
1. Notice that LSV Lüneburg is missing completely (screenshot 1)
2. Compare to screenshot 3
3. See that LSV Lüneburg should have more than 3000 points counted in 2020 club scoring

**Expected behavior**
The best three flights of each club should be counted for DMSt club ranking.

**Screenshots**
DMSt club ranking 2020: only two flights counted for SFG Bensheim:
![image](https://user-images.githubusercontent.com/47079209/105635390-d186a400-5e62-11eb-8d73-367b1c03ae74.png)

Flight list with more than two valid DMSt flights for SFG Bensheim:
![image](https://user-images.githubusercontent.com/47079209/105635260-52916b80-5e62-11eb-8a4e-de828c84bcbd.png)

Flight list with valid flights of LSV Lüneburg in 2020:
![image](https://user-images.githubusercontent.com/47079209/105635527-8caf3d00-5e63-11eb-86e8-94fb0fa583dd.png)

**Comment by moldhouse** [comment]
I think this is fixed now? Thank you very much for the detailed description.

**Comment by frantzheld** [comment]
![Screenshot_20210201_185925_com android chrome](https://user-images.githubusercontent.com/47079209/106498500-b13c9200-64bf-11eb-812f-837c6555e3b5.jpg)
Looks good! 👍
