### ISSUE TITLE
Entdeklarierte Aufgabe löschen/bearbeiten

### ISSUE THREAD

**Issue by floriangaller** [weglide/bugtracker#82]
**Describe the bug**
Eine Aufgabe welche deklariert und danch entdeklariert wurde kann nicht gelöscht oder bearbeitet werden 

**To Reproduce**
Aufgabe anlegen
deklarieren
entdeklarieren
danach kann man es nicht mehr bearbeiten löschen...

**Expected behavior**
ich denke eine entdeklarierte Aufgabe sollte sich wieder löschen lassen,...

**Screenshots**

**Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Browser Firefox

**Comment by moldhouse** [comment]
This raises some problems. For example, you could declare a task, fly the task, then undeclare and delete it and afterwards upload the flight. We would not be able to score the task, as we don't have any information about the task anymore.

**Comment by samuel-git** [comment]
To add: Someone else might still have your public task declared.

**Comment by frantzheld** [comment]
Maybe add a possibility to hide tasks?
Then the task would disappear in my task list, but it would be available internally for scoring.

**Comment by moldhouse** [comment]
Yes hiding it seems like a good compromise.

**Comment by moldhouse** [comment]
Task is now hidden on delete
