### ISSUE TITLE
Bilder in einer Geschichte in Originalgröße zeigen

### ISSUE THREAD

**Issue by Diomedea7** [weglide/bugtracker#83]
**Describe the bug**
Bilder können mit Chrome nicht in einem neuen Tab vergrößert angezeigt werden.

**To Reproduce**
Chrome > rechte Maustaste > Bild in neuem Tab öffnen > Bild erscheint NICHT in einem neuen Tab 
Vielmehr wird der Speichern-Dialog angezeigt, was unpraktisch ist.
Firefox > rechte Maustaste > Grafik anzeigen: Das funktioniert gut!   :-)

**Expected behavior**
Beste Lösung: Links-Klick mit der Maus zeigt das Bild in Originalgröße in einem Extra-Fenster an.
Okay: Rechte Maustaste > Bild in neuem Tab öffnen das Bild in einem neuen Browser-Tab.

**Device (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Browser: Chrome

**Comment by samuel-git** [comment]
@Diomedea7 wie du richtig bemerkt hast haben wir über das unterschiedliche Browserverhalten keine Kontrolle.
Die Story hat auch einen Vollbildmodus den aber viele übersehen. Wir arbeiten noch an einer perfekten Lösung.
