### ISSUE TITLE
Incorrect tasks returned from API

### ISSUE THREAD

**Issue by fousa** [weglide/bugtracker#84]
When performing the following request, no tasks are returned at this point.

```
curl "https://api.weglide.org/v1/task?order_by=modified&starred_by=220" -H "Authorization: Bearer xxxxxxx"
```

And when I look at my task dashboard, I have 3 tasks in the beta version.

![Screenshot 2021-01-30 at 15 09 07](https://user-images.githubusercontent.com/45648/106358538-2320aa00-630d-11eb-9c91-bb6527a7d74c.png)

I compared the requests that were performed by the website, and there doesn't seem to be a mismatch. The same happens with the `starred_by` parameter. It seems to return different tasks...

**Comment by fousa** [comment]
I think it has something to do with the visibility settings when creating a task.

I would assume that I can see my tasks even if they are not visible for others... Or is this an incorrect assumption?

**Comment by moldhouse** [comment]
I can not reproduce the error. 
Pasting https://api.weglide.org/v1/task?order_by=modified&starred_by=220 to my browser returns three tasks.

**Comment by samuel-git** [comment]
@fousa Maybe your token is invalid. Without valid token, only public tasks will be returned.
