### ISSUE TITLE
Inconsistent date formats

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#85]
**Describe the bug**
Date formats are inconsistent and independent of language setting.

**To Reproduce**
1. Go to flight list
2. Select single date
3. Switch to range filter
4. Select range
5. First bug: both filters are active at the same time (range+day)
6. Second bug: The day filter is displayed as DD.MM.YYYY while the range filter is displayed as YYYY-MM-DD

The described behavior is independent of the language setting.
So a day is always DD.MM.YYYY and a range is always YYYY-MM-DD no matter which language was set.

**Expected behavior**
All dates should be displayed consistently in the regional date format.

**Screenshots**
![image](https://user-images.githubusercontent.com/47079209/106583852-d247c600-6545-11eb-8feb-13ac9bd31fb2.png)

**Comment by samuel-git** [comment]
Fixed for next release, thanks!
