### ISSUE TITLE
multiple ENL windows - cannot edit them correctly in GUI to save

### ISSUE THREAD

**Issue by cdolain** [weglide/bugtracker#86]
Hi,

on the webpage using firefox i try to upload IGC and edit the  ENL events. 
There are 2 real  ENL events - the other 2 are artefacts. 
So seems like the ENL detection is not yet totally robust - which is ok as  long as I can hand-edit. 
But it's not possible in this case.
So the currently stored IGC file shows a quite shorter flight than what is really was:
https://beta.weglide.org/flights/16701

upload1 - first time uploading and how Gui looks like.....
![upload1](https://user-images.githubusercontent.com/76599408/106822998-7a61aa00-6680-11eb-8a81-c22fef98c9b1.jpg)

then editing the ENL windows - cannot save
![upload2_withError](https://user-images.githubusercontent.com/76599408/106823051-88afc600-6680-11eb-8f38-a27610c1c651.jpg)

Hope this helps - best regards and good progress so far. Keep up the pace to create a friendly  atlernative ;-) ,
Christoph

**Comment by samuel-git** [comment]
Hey, your edited window does not make sense (end is before flight?) Thats why it's not saving.
We will make the error messages clearer.
The time input is also improved for the next version.

**Comment by cdolain** [comment]
Aaaah - it's the AM vs PM.

Könnt ihr auch 24h Zeiten machen wenn man deutsches Profil hat?

Die ENL Detection wolltet ihr doch noch verbessern?
Das ist mit Cambridge aufgenommen.



Am 4. Februar 2021 02:31:18 MEZ schrieb Samuel <notifications@github.com>:
>Hey, your edited window does not make sense (end is before flight?)
>Thats why it's not saving.
>We will make the error messages clearer.
>The time input is also improved for the next version.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/weglide/bugtracker/issues/86#issuecomment-772956289

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by cdolain** [comment]
Die Zeiten vom Mauszeiger im barogramm sind im 24h Format - die vom enl Window mit AM/PM. 

Am 4. Februar 2021 16:31:52 MEZ schrieb Christoph Dolainsky <cdolain@gmx.de>:
>Aaaah - it's the AM vs PM.
>
>Könnt ihr auch 24h Zeiten machen wenn man deutsches Profil hat?
>
>Die ENL Detection wolltet ihr doch noch verbessern?
>Das ist mit Cambridge aufgenommen.
>
>
>
>Am 4. Februar 2021 02:31:18 MEZ schrieb Samuel
><notifications@github.com>:
>>Hey, your edited window does not make sense (end is before flight?)
>>Thats why it's not saving.
>>We will make the error messages clearer.
>>The time input is also improved for the next version.
>>
>>-- 
>>You are receiving this because you authored the thread.
>>Reply to this email directly or view it on GitHub:
>>https://github.com/weglide/bugtracker/issues/86#issuecomment-772956289
>
>-- 
>Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
