### ISSUE TITLE
Custom Waypoints

### ISSUE THREAD

**Issue by samuel-git** [weglide/bugtracker#87]
Upload custom waypoints to plan task.
Alternatively one big waypoint database to which every user can contribute

_Originally posted by @henrik-the in https://github.com/weglide/bugtracker/issues/80#issuecomment-766343001_

This is something we have to plan. I see three possible solutions:
1. Incorporate a form into WeGlide (needs some form of validation from others to assure quality)
2. Create a database on GitHub (not accessible for non-techies)
3. Collect waypoints from .cup files automatically (difficult to add completely new waypoints)

**Comment by morhall** [comment]
I just signed up and one of the first things I tried out after uploading a trace was planning a task.   The lack of local waypoints makes task planning in the Western US pretty much useless as most areas have significant numbers of waypoints that aren't airports. 

To me, the idea of a global database seems a bit unwieldy.  I routinely use one or two cup files and occasionally travel far enough to require additional ones.  Some of the "local" files that we use may have in excess of 2000 waypoints covering much of the SW US.  Bogging down users in Europe with database points in the US or vice versa doesn't make much sense to me.

The use cases that are important are already implemented in tools like soaringlab.eu.  I can upload my own waypoint files and as far as I know they are accessible to my profile only.  That works pretty well and seems logical.  If my club adds a few dozen waypoints for beginner tasks specific to the club, it doesn't seem like everyone else in the world would want them or care.  

Good start of an app though and I like the fact that you're integrated with LXNav Connect.

**Comment by samuel-git** [comment]
Thanks for your thorough reasoning. I agree that task planning in the US (no waypoints) is difficult at the moment.
How do you mean bogging down? Waypoints are only loaded on close up zoom for specific areas. If you are concerned about performance/visibility, that is not a problem. We could even go so far as to rank waypoints by importance and start displaying them accordingly on different zoom levels.

We had an other proposal for a possibility of filtering waypoints.

A large waypoint database has some huge benefits in my opinion:

* Not having to deal with multiple waypoint files (it's 2021 after all)
* Easy access to quality waypoints for travelling or beginners without manual research
* Easy to distribute waypoints for contests by adding them for everyone

I think the most common approach for tackling large amounts of crowdsourced POIs is a simple option to add points for locals with the option for people who have visited them to vote them up/down (verification).
This would allow for ranking them by importance and detect wrong or bad waypoints.
In addition you could create your own waypoint collection with liked waypoints and only show them on the map.

We do need to find a solution for event related "temporary" waypoints.

Of course would such a list be open for edits and free to use/download for everyone.

**Comment by samuel-git** [comment]
@morhall we are working on a hybrid solution which allows for personal waypoint collections from your own files together with collections from other people.
The shift is based on a lot of user feedback (including yours) requesting waypoint uploads for different reasons.

**Comment by deltafox44** [comment]
I don't think there are good or bad waypoints. At least in flat terrain. And no database will suit all needs. When planning a flight of  given distance (for badges for instance) or FAI triangles, it may be necessary to set a waypoint a few kms away from existing database waypoints.
Anyway, at present is is possible to plan a task by clicking anywhere on the map and WeGlide creates the waypoints (given morhall's comment above, it may be a new feature ?) and that's fine. Integration in LxCloud would be great (to avoid having to pass the task to the computer via a .tsk file on USB key).
Still, each pilot may already have a certain number of tasks from others softwares, if he wants to declare one of these tasks in WeGlide, an universal database would be useless, he needs to load his custom Waypoints/tasks file.

**Comment by samuel-git** [comment]
This feature is now released, thank you all for the good ideas!
https://magazine.weglide.org/custom-waypoint-files-task-planner/

Everyone can use all public waypoint collections when planning a task now (works perfect for competitions), uploading or editing your own waypoint files requires a premium subscription.
