### ISSUE TITLE
Declared Tasks with Emoji in task title cant be downloaded via API

### ISSUE THREAD

**Issue by henrik-the** [weglide/bugtracker#88]
**Describe the bug**
Declared Tasks with Emoji in task title cant be downloaded via API. 
API responds with "Internal Server Error"
Other tasks without Emoji in Title are downloadable.

**To Reproduce**
1. Declare this Task: https://beta.weglide.org/task/6586
2. Go to: https://api.weglide.org/docs#/task/get_task_declared_v1_task_declaration__user_id__get
3. Try to download task with: "/v1/task/declaration/{user_id}"

**Expected behavior**
Task should be downloadable or no Emojis should be allowed in title.

**Comment by samuel-git** [comment]
Haha thats a funny one! @moldhouse

**Comment by moldhouse** [comment]
Yes I already found it in the logs yesterday but could not link it to the task ID.

**Comment by moldhouse** [comment]
![IMAGE 2021-02-07 13:27:02](https://user-images.githubusercontent.com/24278651/107146386-2a1c6d80-6948-11eb-88c3-e0a3a4d47ffb.jpg)
