### ISSUE TITLE
Aircraft Type not read correctly out of IGC-File

### ISSUE THREAD

**Issue by BenjaminMeier** [weglide/bugtracker#89]
**Describe the bug**
Aircraft Wingspan and/or Subtype not read from IGC-File correctly.
DG808C with Competition class 18m was parsed as "DG 808 15m"
ASH 26E was parsed to ASH 26 without the E.

**To Reproduce**
Upload an IGC-File from Benjamin Meier or Stefan Vogel (both SG Pilatus-Luzern)

**Expected behavior**
Choose the correct type with all the information possible.. or share the information of how exactly the plane type should be defined in the igc file.

**Comment by moldhouse** [comment]
Thanks for reporting! Our aircraft naming is already public, you can find it [here](https://github.com/weglide/GliderList/blob/master/gliderlist.csv). I will try to improve on the name guessing in the coming days.

**Comment by BenjaminMeier** [comment]
On a similar topic: For https://www.weglide.org/flight/33444 the user did not select the correct type of aircraft, HB-2339 is a NIMBUS-4DM as can be checked on https://app02.bazl.admin.ch/web/bazl/de/#/lfr/search or on https://www.onlinecontest.org/olc-3.0/gliding/flightinfo.html?dsId=8267549 .

To mitigate such problems you might want to check the ENL no matter of the type, or have some kind of sanity check with the registration, at least for aircraft registered in Switzerland motorgliders: (TMG, Selflaunch and Turbos) are between HB-2000 and HB-2999, Ecolight-Motorgliders are above HB-5500 . I believe in Germany its D-Kxxx and in Austria OE-9001 to OE-9999 . (see https://de.wikipedia.org/wiki/Luftfahrzeugkennzeichen)

**Comment by moldhouse** [comment]
Thanks for the heads up. We already do this checking for German aircraft and I will add it for Switzerland and Austria as well.
