### ISSUE TITLE
Regional filter in ranking doesn't work

### ISSUE THREAD

**Issue by niggli** [weglide/bugtracker#9]
**Describe the bug**
Filtering a region in the ranking doesn't do anything. 

**To Reproduce**
1. Go to "ranking"
2. Click on "plus"
3. In filter, enter "Schweiz"
4. All the flights from all regions are still displayed

**Expected behavior**
I expect to only see flights from this region.

**Screenshots**
<img width="1276" alt="Bildschirmfoto 2020-12-24 um 22 14 21" src="https://user-images.githubusercontent.com/529670/103106395-7bd99480-4635-11eb-8705-033ed406c9d6.png">

**Device (please complete the following information):**
 - Device: MacBook Pro
 - OS: OSX Catalino
 - Browser: Safari

**Comment by moldhouse** [comment]
This should also be fixed by the latest version. 

<img width="907" alt="image" src="https://user-images.githubusercontent.com/24278651/103138403-9dd52480-46d2-11eb-91ec-6b72d3a94a2e.png">
