### ISSUE TITLE
Task download not possible if "only visible for me"

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#90]
**Describe the bug**
It is not possible to download private tasks ('only visible for me').

**To Reproduce**
1. Create Task
2. Select 'Only visible for me'
3. Save task
4. Click download button
5. See error: {"error":"task_not_found","error_description":"Task not found"}

**Expected behavior**
Task downloads should be possible for all my own tasks no matter if they are public or private.

**Device:**
 - Device: PC
 - OS: Windows 10
 - Browser chrome

**Comment by samuel-git** [comment]
Thanks, we are aware of that. It's technically not straight forward and therefore needs some time for a clean solution.

**Comment by moldhouse** [comment]
Implemented in next release
