### ISSUE TITLE
WeGlide task cup file not compatible with XCSoar

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#91]
**Describe the bug**
A downloaded task cup file is not readable by XCSoar.

**To Reproduce**
1. Download any task
2. Open it to XCSoar
3. See, that the task is empty

**Expected behavior**
WeGlide tasks should be compatible with XCSoar.

**Additional information**
I played around with a downloaded cup file and found two problems, that lead to the issue.
- The elevation is missing for all waypoints (I don't know, why this is a problem for XCSoar - maybe the issue is not on weGlide but on XCSoar)
- The task format should be: `takeoff, start, waypoint, ..., waypoint, finish, landing` but takeoff and landing are empty

I added elevation, takeoff and landing to the cup file, then the cup file was read by XCSoar.

**Screenshot**
Left: weGlide task, Right: customized task, which is compatible with XCSoar
![image](https://user-images.githubusercontent.com/47079209/107121643-e1a37800-6893-11eb-9180-bca1f2c98b92.png)

**Comment by moldhouse** [comment]
Could you provide the id of the corresponding task?

Btw, we already provide download in .tsk format via api. @samuel-git pls also add to frontend.

**Comment by moldhouse** [comment]
I will check but my understanding is that takeoff and landing may be empty in the .cup format.

**Comment by frantzheld** [comment]
My test above uses this simple task: https://beta.weglide.org/task/11502

When takeoff and landing is empty, XCSoar reads the task, but the last turnpoint is missing. So the back-and-return task Lüneburg-Hoepen-Lüneburg gets an one-way task Lüneburg-Hoepen.

**Comment by moldhouse** [comment]
I suspect this to be an error by XCSoar, as we do provide an empty field for landing airport. This fields is not used anymore, so I would rather leave it empty than write an empty value. However, I don't think this error has any implications as you can simply download in .tsk format.

**Comment by moldhouse** [comment]
http://api.weglide.org/v1/task/11502?tsk=1

**Comment by frantzheld** [comment]
.tsk works a lot better for XCSoar. Thank you! :)

There is still one issue with the .tsk file: The turnpint is read as 'Area sector' with 100km radius.
![image](https://user-images.githubusercontent.com/47079209/107145366-44068200-6941-11eb-8fc7-65c4268de654.png)
So XCSoar is creating a turnpoint within this area (like for AAT):
![image](https://user-images.githubusercontent.com/47079209/107145429-af505400-6941-11eb-80f3-850ef282f24e.png)


This is part of the .tsk file from WeGlide:
```
	<Point type="Area">
		<Waypoint name="Hoepen_58945">
			<Location latitude="53.14738806763555" longitude="9.796371459960938"/>
		</Waypoint>
		<ObservationZone radius="100000" type="SymmetricQuadrant"/>
	</Point>
```

I changed the point type from `Area` to `Turn` and the observation zone to `FAISector`:
```
	<Point type="Turn">
		<Waypoint name="Hoepen_58945">
			<Location latitude="53.14738806763555" longitude="9.796371459960938"/>
		</Waypoint>
		<ObservationZone type="FAISector"/>
	</Point>
```

Now XCSoar displays the same task as shown in the task planner:
![image](https://user-images.githubusercontent.com/47079209/107145972-816d0e80-6945-11eb-8312-d9a090a4b94b.png)

**Comment by moldhouse** [comment]
So i think the kind should be TURN? Radius is problematic since in theory, the quadrants are unlimited in size. If we set it to 10km (which would nicely display) people could be confused. However, I see that 100km is also not optimal.

**Comment by frantzheld** [comment]
Yes, `Turn` should be correct for racing tasks. `Area` is only used for assigned area tasks in gliding competitions.

The `FAISector` should be the right one for infinite radius, if the description is correct:
![image](https://user-images.githubusercontent.com/47079209/107146404-4a4c2c80-6948-11eb-9cc8-b4879ed640b2.png)

**Comment by frantzheld** [comment]
Unfortunately XCSoar does not behave as described above. As tested here, XCSoar doesn't get the turn:
![image](https://user-images.githubusercontent.com/47079209/107147013-ec214880-694b-11eb-89d5-1a67464393a9.png)

But this seems like an issue for XCSoar, not for weglide :)

**Comment by samuel-git** [comment]
.tsk support is coming with next release.

**Comment by frantzheld** [comment]
.tsk download works perfect. 👍  Thanks a lot!
