### ISSUE TITLE
Tasks - Triangle determination

### ISSUE THREAD

**Issue by HorstVissel** [weglide/bugtracker#92]
**Describe the bug**
Triangles not correctly determined when task comprises additional waypoints

**To Reproduce**
1. Go to 'https://beta.weglide.org/task/10991'
2. Indicates "788.09 km Dreieck" based on turnpoints Schwabmünchen, Kirchzarten, Wasserkuppe not taking into account starting/landing waypoint Geratshof.

**Expected behavior**
1. Go to "http://www.prosoar.de" create task with the same waypoints
2. Indicates "820.3 km FAI-triangle based on waypoints Geratshof, Kirchzarten, Wasserkuppe, Geratshof.

**Screenshots**

**Device (please complete the following information):**
 - Device: [e.g. MacBook Pro]
 - OS: [e.g. MacOS]
 - Browser [e.g. safari]

**Comment by moldhouse** [comment]
I am not quite sure why the waypoint "Schwabmünchen" is in your task. Because it is, the task is started on leg. If you don't want to start on leg, you have to remove the turnpoint "Schwabmünchen". In prosoar, you can have an arbitrary amount of waypoints and still have a triangle. My understanding is that a triangle may not have more than 5 WP, but I will check.

<img width="502" alt="image" src="https://user-images.githubusercontent.com/24278651/107148356-f1ce5c80-6952-11eb-9da8-8721a1591a77.png">

**Comment by HorstVissel** [comment]
Typically, I use these "intermediate waypoints" (here:Schwabmünchen) to ensure that I avoid airspaces (here: Memmingen) as most moving maps directly show the way to the next waypoint.

**Comment by HorstVissel** [comment]
You are probably correct based on:
https://www.fai.org/sites/default/files/sc3_-_2020_update_0.pdf

The question is whether WeGlide should show the TaskLength of a free FAI-triangle (like ProSoar and LX) or the TaskLength of a declared FAI-triangle. I think most competitors are used to the free triangle definition.

**Comment by moldhouse** [comment]
Yes this is an interesting question indeed. As we host the DMSt, the task kind which is displayed while planning should match the one that is scored. Otherwise there will be lots of confusion.

**Comment by HorstVissel** [comment]
I agree that planning should match scored, but which one is scored according to DMSt?

 As far as I am aware the DMSt-Rules only specify Declared/not Declared and FAI-triangle, but do not impose a declared FAI-triangle.

**Comment by moldhouse** [comment]
I think this is not declared precisely enough in the DMSt WO. I will try to check with DAeC.

**Comment by HorstVissel** [comment]
Any update from DAeC? As long as it is not clarified, the issue should probably not considered closed.

**Comment by moldhouse** [comment]
Yes, according to point 4.1 in the WO there is a maximum of three turnpoints. My understanding is that our scoring and planning are therefore aligned to the WO.
