### ISSUE TITLE
Missing Flights

### ISSUE THREAD

**Issue by Fuchur777** [weglide/bugtracker#93]
**Describe the bug**
I uploaded a few Flights that dont appear in my Log.
However if I upload the IGC again it sais it already exists.

**To Reproduce**
Upload 54dvjmf1.igc

**Expected behavior**
Expect to find flights in my logbook, even if they are unvalid for whatever reason

**Comment by samuel-git** [comment]
What do you mean with "my Log"?
Do you refer to the API or frontend?

For the API: You need to send your auth headers to see invalid flights.

**Comment by Fuchur777** [comment]
All front end. No API.

If I upload a flight in my account the flight does not appear in my flight
list.

If I reupload the system tells me file already exists.

VG Frank

Op zo 7 feb. 2021 17:39 schreef Samuel <notifications@github.com>:

**Comment by samuel-git** [comment]
Thanks! I will investigate. Does a reload of your flight list after upload fixes the issue?

**Comment by moldhouse** [comment]
I need some more information. When did you upload the flights the first time and can you provide the corresponding igc files? My guess is that this is a bug which we have already fixed but there are still dangling igc file objects in the db without flights.

**Comment by Fuchur777** [comment]
Was uploaded on the first few days of the beta. (23-12-2020 I believe)

IGC File and Screen captures attached.

**Comment by samuel-git** [comment]
@Fuchur777 file attachment does not work via email.
Please send us the igc files so we can delete the old ones (and enable re-upload).

**Comment by Fuchur777** [comment]
Okay so manual exercise for you. It's okay for now. Focus on the important
stuff!
I will email you under support if I need a hand with this.

BR Frank

**Comment by samuel-git** [comment]
Thanks! We got you.
