### ISSUE TITLE
Frontend flight story before flight

### ISSUE THREAD

**Issue by Fuchur777** [weglide/bugtracker#94]
https://beta.weglide.org/flights/1199

Picture stamped with time before the flight gets a after landing mark and is placed at the bottom of the story

**Comment by moldhouse** [comment]
Could you provide the original picture containing exif information?

**Comment by Fuchur777** [comment]
In this case I had to manually add the time.

Op ma 8 feb. 2021 00:35 schreef moldhouse <notifications@github.com>:

**Comment by moldhouse** [comment]
I checked the api, the returned object is 
{
    "id": 2970,
    "user_id": 59,
    "flight_id": 1199,
    "image": "59/images/nE5BT8jfDqrZb5M9ObN9JQTf.jpg",
    "start_time": "2018-08-12T08:24:00+00:00",
    "time_offset": 65352
  }

so the time was set to the day after the flight. This seems to be a frontend bug @samuel-git.

**Comment by samuel-git** [comment]
This issue is fixed for next release. 
@Fuchur777 please edit your story next week again to fix the wrong times.
Thanks for your help in resolving this!
