### ISSUE TITLE
Suche für Tastaturen ohne Umlaute anpassen

### ISSUE THREAD

**Issue by cdolain** [weglide/bugtracker#95]
hi,

versuche gerade alle Alpenfluege mit Start  Paterzell  bzw Koenigsdorf zu filtern. 
Vielleicht versteh ich ja den FIlter nicht richtig. Werden beide Kriterien immer per ODER verbunden ? wie bekommt man filter [paterzell] UND [alpen]  ? 
Man kann natuerlich ueber die Karte versuchen einen Flug raus zu picken.
Ein spezifisches Datum geht wohl als UND verknuepfung. 

Wenn es moeglich waere haette ich folgende Anfrage:
1. UND zwischen kriterien (z.b. statt dem   + ein  && oder || anbieten mit || als default
![filter_add](https://user-images.githubusercontent.com/76599408/107407084-8084da00-6b09-11eb-906f-bc81f5ebc7f7.jpg)
) 
2. neben  umlaut auch oe/ae/ue erlauben  fuer Leute ohne deutsche Tastatur 

Gruss,
Christoph

**Comment by samuel-git** [comment]
Hi, was du ansprichst ist leider für die meisten Nutzer zu komplex.
Da die Flüge der Region eh nach Startplatz gefiltert werden erreichst du was du möchtest indem du die Filter Paterzell und Königsdorf setzt.

Ersetzen der Umlaute schauen wir uns an, danke für den Hinweis.

**Comment by frantzheld** [comment]
Die Erkennung der Umlaute wär in beide Richtungen hilfreich.
Gibt man z.B. "Stölln" in die Suche ein, wird aktuell nur der Verein gefunden, während der Flugplatz nicht zu finden ist. 
![image](https://user-images.githubusercontent.com/47079209/107932585-02e42280-6f7e-11eb-85e6-7f772b6afa1e.png)

**Comment by samuel-git** [comment]
Das ist ein Fehler in unseren Date. Sollte beides mit Umlauten abgespeichert werden. Ich mache einen pull request @moldhouse .
