### ISSUE TITLE
Center multiple flights

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#96]
**Describe the bug**
When embedding a flight, the flight gets centered after loading.
When multiple flights are embedded, the centering does not work, see screenshot.
Same for Flight detail page with multiple flights: https://beta.weglide.org/flights/1109,12654,1089

**To Reproduce**
1. Go to https://beta.weglide.org/embedded/1109,12654,1089?baro=true&bbox=
2. See that flights are not centered / zoomed in
3. Zoom in manually
4. Click on Center flight
![image](https://user-images.githubusercontent.com/47079209/107652960-68d06180-6c81-11eb-8f7c-4115fa6e8211.png)
5. See that view zooms out

**Expected behavior**
Flights should be centered when loaded or when clicking the center flight button.

**Screenshots**
![image](https://user-images.githubusercontent.com/47079209/107652216-a1237000-6c80-11eb-8cd1-36cb0dbff820.png)

**Device (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Browser chrome

**Comment by samuel-git** [comment]
Fixed for next release.
