### ISSUE TITLE
Ranking URL region filter gets lost

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#97]
**Describe the bug**
The URL gets updated, when a region filter is applied for the ranking, e.g. `?region=DE_NI`
When refreshing the page or opening the URL in a new window the filter gets lost.

**To Reproduce**
1. Go to https://beta.weglide.org/ranking/dmst?season=2020&category=pilot&user=ALL&sc_class=ALL
2. Enter region
3. See that region is added to URL, e.g.: https://beta.weglide.org/ranking/dmst?region=DE_NI&&season=2020&category=pilot&user=ALL&sc_class=ALL
4. Refresh page or Copy URL to new window
5. See that region is lost

**Expected behavior**
Region filter should be applied when loading an URL containing e.g. `?region=DE_NI`

**Comment by samuel-git** [comment]
Confirmed, thanks.

**Comment by samuel-git** [comment]
Fixed for next release. New url structure opens the way for sophisticated ranking filters similar to list filters.
