### ISSUE TITLE
DMSt rectangle scoring with start on leg

### ISSUE THREAD

**Issue by frantzheld** [weglide/bugtracker#98]
**Describe the bug**
Task scoring calculation may be wrong when starting a rectangle on leg. A correct rectangle is not scored as such.

**To Reproduce**
1. Plan task as seen on screenshot 1
2. See that task is scored as rectangle
3. Plan same task with start on leg, see screenshot 2
4. See that task is scored as free

**Expected behavior**
As both tasks are identical (except for the start), they should both been scored identical (as rectangle).

**Screenshots**
Start on the edge: Scored as declared rectangle
![image](https://user-images.githubusercontent.com/47079209/107686513-9e874180-6ca5-11eb-9a2a-8038c6a2c645.png)

Start on leg: Scored as free
![image](https://user-images.githubusercontent.com/47079209/107686552-aba43080-6ca5-11eb-9e37-86e3863b7061.png)

**Comment by frantzheld** [comment]
If I split the rectangle in two triangles, you can see that both are valid DMSt triangles.

![image](https://user-images.githubusercontent.com/47079209/107689434-1c991780-6ca9-11eb-9d9e-e9211469234d.png)
![image](https://user-images.githubusercontent.com/47079209/107689508-34709b80-6ca9-11eb-8056-ffe7b77e7578.png)

Btw: Displaying the valid sector as well for rectangles would help a lot for planning. The sectors for both turnpoints of the shared leg have to be constructed as an overlap of both triangle sectors for the respective turnpoint. In this example I marked them in yellow. The shape gets a bit strange, but should be valid.
![image](https://user-images.githubusercontent.com/47079209/107691183-6aaf1a80-6cab-11eb-9a64-b5ca2377c53b.png)

**Comment by moldhouse** [comment]
@samuel-git could we draw both triangle sectors and then see only mark the overlap on the map. This would be much simpler than calculating the edges of the rectangle sectors.

**Comment by samuel-git** [comment]
This is possible with https://turfjs.org/docs/#intersect.
My concern is the real time performance as tur is notoriously slow.

**Comment by moldhouse** [comment]
Can you confirm that the problem is fixed for your task?

**Comment by frantzheld** [comment]
Yes, thank you!
![image](https://user-images.githubusercontent.com/47079209/107922844-e2619b80-6f70-11eb-87bb-c145bad1525a.png)

Closed, as original issue is fixed.
Feel free to reopen/rename if you have some time for the rectangle sector drawing :)
